package dev.brikk.house.sql.runtime

/**
 * A set of *minimum* column requirements: "whatever flows here has at least these columns".
 * User-declared trait interfaces extend this (and are marked [BrikkTrait]); the compiler
 * plugin also types the declared output of a generic pipe as a Partial, because only the
 * bound's columns plus the pipe's own additions are known before a call site fixes `T`.
 */
interface Partial

/**
 * A *full*, closed column set: the exact output of a query or pipeline stage. Generated by
 * the compiler plugin from the SQL text and the schema catalog; never written by hand.
 * Every Shape is also usable wherever a Partial it structurally satisfies is required —
 * the plugin materializes those trait interfaces as supertypes of the generated Shape.
 */
interface Shape : Partial

/**
 * Marks a function whose body is a single `Sql.<dialect>("""...""")` literal as a virtual
 * table-valued function. The plugin parses the SQL at compile time, binds `:name`
 * placeholders to the function's parameters, takes `Rel`-typed parameters as table inputs
 * (the first one is the implicit pipe source `__src` when the SQL starts with `|>`), infers
 * the output shape and types the function accordingly.
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.BINARY)
annotation class BrikkSql

/**
 * Marks a [Partial] interface as a trait the plugin should know about: generated shapes that
 * structurally satisfy it get it as a supertype, and generic pipes may use it as a bound.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class BrikkTrait

/**
 * Marks the dialect entry points on [Sql]. The plugin intercepts calls to functions carrying
 * this annotation; the value is the brikk-sql dialect name.
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.BINARY)
annotation class BrikkSqlDialect(val dialect: String)

/** Dialect entry points. Bodies are never executed: the plugin rewrites every call. */
object Sql {
    @BrikkSqlDialect("postgres")
    fun postgres(sql: String): Rel<Nothing> = notRewritten("postgres")

    @BrikkSqlDialect("doris")
    fun doris(sql: String): Rel<Nothing> = notRewritten("doris")

    @BrikkSqlDialect("clickhouse")
    fun clickhouse(sql: String): Rel<Nothing> = notRewritten("clickhouse")

    @BrikkSqlDialect("duckdb")
    fun duckdb(sql: String): Rel<Nothing> = notRewritten("duckdb")

    private fun notRewritten(dialect: String): Nothing =
        error("Sql.$dialect(...) reached at runtime: the brikk-sql compiler plugin was not applied")
}
