platform=linux-arm64
version=26.5.0
url=https://github.com/chdb-io/chdb-core/releases/download/v26.5.0/linux-aarch64-libchdb.tar.gz
archiveSha256=ba590a475ff8824bdf7d463dded08a4f987ea4687cfb0a1de262b7e7d7bf2554
