modules:
  - brikk-engine-kotlin
  - brikk-engine-kotlin-compiler-ide
  - brikk-engine-kotlin-compiler-plugin
  - brikk-engine-kotlin-intellij-support
  - brikk-engine-kotlin-intellij-tooling
  - brikk-engine-kotlin-schema-inputs
  - brikk-engine-kotlin-smoke
  - brikk-engine-kotlin-tooling
  - samples/duckdb-pipelines

plugins:
  - ./brikk-engine-kotlin-schema-inputs
  - ./brikk-engine-kotlin-tooling
  - ./brikk-engine-kotlin-intellij-tooling
