// GENERATED FILE — DO NOT EDIT.
// Generated by tools/generate_hazards_registry.py from
// brikk-sql/testResources/semantics/trino-doris-hazards.json (brikk live-probe program,
// extracted 2026-07-13): live-probe-verified trino<->doris semantics
// verdicts. Regenerate after editing the JSON; the run is byte-deterministic.
//
// Keying and collision policy: see the tool's docstring / HazardRegistry KDoc
// (raw side-name + bare-identifier alternatives; collisions keep the WORST
// verdict, ties keep JSON order).
package dev.brikk.house.sql.metadata

/** The 103 probe-verified (trino, doris) pair verdicts, in JSON order. */
internal val TRINO_DORIS_HAZARD_ENTRIES: List<FunctionHazard> = hazardsChunk0() +
    hazardsChunk1() +
    hazardsChunk2()

private fun hazardsChunk0(): List<FunctionHazard> = listOf(
    // [0] trino: 'lower' | doris: 'lower'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#lower"),
    // [1] trino: 'upper' | doris: 'upper'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#upper"),
    // [2] trino: 'concat' | doris: 'concat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both propagate NULL (Doris live-probed = NULL; Trino prior = NULL). Safe re NULL, unlike DuckDB.",
        areas = listOf("string", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#concat"),
    // [3] trino: 'greatest' | doris: 'greatest'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both return NULL if any arg is NULL (Doris live-probed; Trino prior).",
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#greatest-least"),
    // [4] trino: 'least' | doris: 'least'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both return NULL if any arg is NULL (Doris live-probed; Trino prior).",
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#greatest-least"),
    // [5] trino: 'split_part' | doris: 'split_part'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Out-of-bounds index -> NULL on both (Doris live-probed; Trino prior).",
        areas = listOf("string", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#split-part"),
    // [6] trino: 'reverse' | doris: 'reverse'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both reverse by code point (Doris live-probed; Trino prior code-point-only). DuckDB is the grapheme-aware outlier.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#reverse"),
    // [7] trino: 'regexp_replace' | doris: 'regexp_replace'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both replace ALL matches by default (Doris live-probed; Trino prior).",
        areas = listOf("regex"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#regexp-replace"),
    // [8] trino: 'ascii' | doris: 'ascii'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris ascii is byte-oriented (ascii('É')=195, first UTF-8 byte); Trino codepoint (requires varchar(1)). Doris diverges from BOTH Trino and DuckDB. Trino side from prior evidence, not re-run live — confirm with live Trino.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#ascii"),
    // [9] trino: 'trim' | doris: 'trim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris strips ASCII space only; Trino (Java isWhitespace) strips tab/LF/CR/FF/VT. Different whitespace sets. Doris live; Trino prior.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [10] trino: 'ltrim' | doris: 'ltrim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris ASCII-space-only vs Trino Java-whitespace. Doris live; Trino prior.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [11] trino: 'rtrim' | doris: 'rtrim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris ASCII-space-only vs Trino Java-whitespace. Doris live; Trino prior.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [12] trino: 'bit_count' | doris: 'bit_count'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Trino requires explicit bit-width arg; Doris infers. Doris live; Trino prior.",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [13] trino: 'fmod' | doris: 'fmod'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Trino float % uses IEEE-remainder-ish; Doris differs. Doris live; Trino prior.",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [14] trino: 'regexp_extract_all' | doris: 'regexp_extract_all'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Empty-match/array handling differs. Doris live; Trino prior.",
        areas = listOf("regex"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [15] trino: 'length' | doris: 'length'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris length()=bytes; Trino length()=characters. Doris live; Trino prior (char-based).",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [16] trino: 'abs' | doris: 'abs'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [17] trino: 'mod' | doris: 'mod'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [18] trino: 'coalesce' | doris: 'coalesce'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [19] trino: 'nullif' | doris: 'nullif'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [20] trino: 'md5' | doris: 'md5'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("hash"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [21] trino: 'acos' | doris: 'acos'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Out-of-domain acos(2): Doris returns NULL; Trino (JVM Math) returns NaN. In-domain agrees. Doris live; Trino from prior evidence + JVM domain semantics.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [22] trino: 'asin' | doris: 'asin'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Out-of-domain asin(2): Doris returns NULL; Trino returns NaN. Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [23] trino: 'ln' | doris: 'ln'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "ln(0)/ln(-1): Doris returns NULL; Trino returns NaN (prior evidence 'NaN on x<=0'). In-domain agrees to last-ULP. Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [24] trino: 'sqrt' | doris: 'sqrt'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "sqrt(-1): Doris returns NULL; Trino returns NaN (prior evidence 'NaN on negative'). Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [25] trino: 'log2' | doris: 'log2'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "log2(0): Doris returns NULL; Trino returns NaN/domain (prior). In-domain agrees. Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [26] trino: 'log10' | doris: 'log10'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "log10(-1): Doris returns NULL; Trino returns NaN (prior). In-domain also differs by last-ULP (log10(3)). Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [27] trino: 'log' | doris: 'log'
    FunctionHazard(HazardVerdict.UNCLEAR,
        hazard = "Doris single-arg log(x) = natural log (log(10)=2.302585), not log10; two-arg log(b,x) agrees to last-ULP. Trino single-arg log semantics not re-probed this session — verify before mapping. Doris live.",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [28] trino: 'exp' | doris: 'exp'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "In-domain agrees to ~15 sig digits but last-ULP differs (exp(0.5): DuckDB/Trino 1.6487212707001282 vs Doris 1.648721270700128). Safe under float-tolerant comparison. Doris live; Trino via live-DuckDB bridge (prior identical).",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [29] trino: 'cbrt' | doris: 'cbrt'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP differs (cbrt(27): DuckDB/Trino 3.0000000000000004 vs Doris 3.0). Safe under float-tolerant comparison. Doris live; Trino via live-DuckDB bridge (prior identical).",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [30] trino: 'atan' | doris: 'atan'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [31] trino: 'atan2' | doris: 'atan2'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [32] trino: 'cos' | doris: 'cos'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [33] trino: 'cosh' | doris: 'cosh'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [34] trino: 'sin' | doris: 'sin'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [35] trino: 'sinh' | doris: 'sinh'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [36] trino: 'tan' | doris: 'tan'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [37] trino: 'tanh' | doris: 'tanh'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [38] trino: 'ceil' | doris: 'ceil'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [39] trino: 'ceiling' | doris: 'ceiling'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
)

private fun hazardsChunk1(): List<FunctionHazard> = listOf(
    // [40] trino: 'floor' | doris: 'floor'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [41] trino: 'degrees' | doris: 'degrees'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [42] trino: 'radians' | doris: 'radians'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [43] trino: 'pi' | doris: 'pi'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [44] trino: 'sign' | doris: 'sign'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [45] trino: 'pow' | doris: 'pow'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [46] trino: 'power' | doris: 'power'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [47] trino: 'to_hex' | doris: 'hex'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris to_hex() returns NULL (to_hex(255)=NULL, to_hex('abc')=NULL); the working hex encoder is Doris hex(). Map Trino to_hex -> Doris hex(), never by name. Doris live.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [48] trino: 'from_hex' | doris: 'unhex'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris from_hex('616263') does NOT hex-decode (returns '363136323633'); the correct hex decoder is Doris unhex('616263')='abc' (matches Trino from_hex). Map Trino from_hex -> Doris unhex, never by name. Doris live.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [49] trino: 'format_number' | doris: 'format_number'
    FunctionHazard(HazardVerdict.NO_EQUIVALENT,
        hazard = "Doris has no format_number function ('Can not found function format_number'). Doris live.",
        areas = listOf("string", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [50] trino: 'url_encode' | doris: 'url_encode'
    FunctionHazard(HazardVerdict.UNCLEAR,
        hazard = "Doris url_encode('a b&c')='a+b%26c' (space -> '+'). Trino url_encode space-handling not re-probed this session (prior trino==duckdb 'identical' verdict did not test space; DuckDB uses %20) — verify Trino before mapping. Doris live.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [51] trino: 'starts_with' | doris: 'starts_with'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Value semantics identical but Doris returns TINYINT 0/1 vs Trino BOOLEAN — boolean type mapping required (Doris renders BOOLEAN as 0/1 over MySQL protocol).",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [52] trino: 'sha1' | doris: 'sha1'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris sha1('abc') returns hex VARCHAR (matches DuckDB digest); Trino sha1 returns VARBINARY — unhex() wrap required for parity (same pattern as md5).",
        areas = listOf("hash", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [53] trino: 'replace' | doris: 'replace'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "3-arg replace aligned; Trino 2-arg remove form replace(s,search) maps by passing '' as replacement. Doris live.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [54] trino: 'levenshtein_distance' | doris: 'levenshtein'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris has no levenshtein_distance; use Doris levenshtein (levenshtein('kitten','sitting')=3, matches). Rename only.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [55] trino: 'hamming_distance' | doris: 'hamming_distance'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "hamming_distance('abc','abd')=1 (Doris live; Trino same).",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [56] trino: 'soundex' | doris: 'soundex'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "soundex('Robert')='R163' (Doris live; Trino same). (DuckDB needs splink_udfs; irrelevant to Trino->Doris.)",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [57] trino: 'from_base64' | doris: 'from_base64'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [58] trino: 'to_base64' | doris: 'to_base64'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [59] trino: 'lpad' | doris: 'lpad'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Pad, unicode pad, over-length truncation aligned.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [60] trino: 'rpad' | doris: 'rpad'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [61] trino: 'repeat' | doris: 'repeat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "repeat('x',0)='' both.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [62] trino: 'translate' | doris: 'translate'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Extra from-chars deleted in both.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [63] trino: 'url_decode' | doris: 'url_decode'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "url_decode('a%20b')='a b' both.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [64] trino: 'concat_ws' | doris: 'concat_ws'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "NULL element skipped; NULL separator -> NULL in both.",
        areas = listOf("string", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [65] trino: 'substr' | doris: 'substr'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "substr('héllo',2,2)='él' (code-point aligned); Doris has substr.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [66] trino: 'avg' | doris: 'avg'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "avg{1,2,3,NULL}=2.0 (NULLs skipped); empty->NULL. Doris live; Trino from prior evidence (Trino==DuckDB).",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [67] trino: 'sum' | doris: 'sum'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "sum{1,2,NULL}=3; empty->NULL both. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [68] trino: 'count' | doris: 'count'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "count(x) skips NULL; count(*) counts rows. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [69] trino: 'max' | doris: 'max'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "max ignores NULL. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [70] trino: 'min' | doris: 'min'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "min ignores NULL. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [71] trino: 'bool_and' | doris: 'bool_and'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Value semantics identical but Doris renders BOOLEAN as TINYINT 0/1 over MySQL protocol vs Trino true/false — boolean type mapping required. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "boolean"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [72] trino: 'bool_or' | doris: 'bool_or'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Value semantics identical but Doris renders BOOLEAN as 0/1 vs Trino true/false — boolean type mapping. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "boolean"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [73] trino: 'any_value' | doris: 'any_value'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Order-sensitive/nondeterministic arbitrary group value; matched this probe but not guaranteed. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [74] trino: 'max_by' | doris: 'max_by'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "arg_max semantics matched (picks value at max key) but tie-breaking nondeterministic. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [75] trino: 'min_by' | doris: 'min_by'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "arg_min semantics matched (min_by(y,x) picks y at min x = 'a') but tie-breaking nondeterministic. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [76] trino: 'corr' | doris: 'corr'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff vs live DuckDB (0.9999008674099173 vs ...172) — value-equivalent. Doris live; Trino from prior evidence (Trino==DuckDB).",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [77] trino: 'covar_pop' | doris: 'covar_pop'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [78] trino: 'covar_samp' | doris: 'covar_samp'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff (2.05 vs 2.049999999999999) — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [79] trino: 'stddev_pop' | doris: 'stddev_pop'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "stddev_pop{1,2,4}=1.247219128924647 exact match vs live DuckDB. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
)

private fun hazardsChunk2(): List<FunctionHazard> = listOf(
    // [80] trino: 'stddev_samp' | doris: 'stddev_samp'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent; sample (N-1) normalization matches. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [81] trino: 'var_pop' | doris: 'var_pop'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [82] trino: 'var_samp' | doris: 'var_samp'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent; sample (N-1) matches. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [83] trino: 'stddev' | doris: 'stddev'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: DEFAULT MISMATCH. Trino stddev == stddev_samp (N-1) = 1.5275252316519468; Doris stddev == stddev_pop (N) = 1.247219128924647 over {1,2,4}. Doris's bare stddev is POPULATION, not sample. Must map Trino stddev -> Doris stddev_samp for parity, never by name.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [84] trino: 'variance' | doris: 'variance'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: DEFAULT MISMATCH. Trino variance == var_samp (N-1) = 2.3333333333333335; Doris variance == var_pop (N) = 1.555555555555556 over {1,2,4}. Doris's bare variance is POPULATION, not sample. Must map Trino variance -> Doris var_samp for parity, never by name.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [85] trino: 'skewness' | doris: 'skewness'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: different formula/default. Over {1,2,4,8}: DuckDB(=Trino sample) 1.1376243669576889 vs Doris 0.6568077344996993 (population moment). Sample-vs-population divergence. Doris live; Trino via DuckDB bridge.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [86] trino: 'kurtosis' | doris: 'kurtosis'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: different formula/default. Over {1,2,4,8}: DuckDB(=Trino sample excess) 0.7576559546313808 vs Doris -1.098979206049149 (population excess). Sign and magnitude differ. Doris live; Trino via DuckDB bridge.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [87] trino: 'regr_intercept' | doris: 'regr_intercept'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [88] trino: 'regr_slope' | doris: 'regr_slope'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff (2.05 vs 2.049999999999999) — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [89] trino: 'array_agg' | doris: 'array_agg'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Returns a LIST/ARRAY (type layer). Order is input-order-dependent and nondeterministic without ORDER BY: DuckDB preserved input order [3,1,2] while Doris returned [1,2,3] on the same UNION-ALL. Add explicit ORDER BY for deterministic parity. Doris live; Trino via DuckDB bridge.",
        areas = listOf("aggregate", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [90] trino: 'map_agg' | doris: 'map_agg'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Returns a MAP (type layer). Doris has map_agg; Trino map_agg builds key->value. Element ordering within the map is nondeterministic — conditionally-equivalent. DuckDB lacks map_agg (Trino-only bridge; compare via histogram/map). Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [91] trino: 'histogram' | doris: 'histogram'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: incompatible return type/semantics. Trino histogram returns a MAP(value->count) (matching DuckDB {a=2,b=1}); Doris histogram returns an approximate-quantile bucket JSON string. Not interchangeable by name. Doris live; Trino via DuckDB bridge.",
        areas = listOf("aggregate", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [92] trino: 'row_number' | doris: 'row_number'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "row_number() OVER(ORDER BY x) = 1,2,3 both. Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [93] trino: 'rank' | doris: 'rank'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "rank() with tie = 1,1,3 (gap). Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [94] trino: 'dense_rank' | doris: 'dense_rank'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "dense_rank() with tie = 1,1,2 (no gap). Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [95] trino: 'ntile' | doris: 'ntile'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "ntile(2) over 3 rows = 1,1,2 both. Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [96] trino: 'lag' | doris: 'lag'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "lag(x) OVER(ORDER BY x) -> NULL,1,2 both. Doris live; Trino from prior evidence.",
        areas = listOf("window", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [97] trino: 'lead' | doris: 'lead'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "lead(x) OVER(ORDER BY x) -> 2,3,NULL both. Doris live; Trino from prior evidence.",
        areas = listOf("window", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [98] trino: 'first_value' | doris: 'first_value'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "first_value(x) OVER(ORDER BY x) = 1,1,1 both. Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [99] trino: 'last_value' | doris: 'last_value'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "last_value(x) OVER(ORDER BY x) = 1,2,3 both — same default frame (running window). Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [100] trino: 'nth_value' | doris: 'nth_value'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "nth_value(x,2) OVER(ORDER BY x) = NULL,2,2 both. Doris live; Trino from prior evidence.",
        areas = listOf("window", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [101] trino: 'percent_rank' | doris: 'percent_rank'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Values identical (0,0.5,1) but Doris renders integral doubles as '0'/'1' vs '0.0'/'1.0' — numeric rendering only. Doris live; Trino from prior evidence.",
        areas = listOf("window", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [102] trino: 'cume_dist' | doris: 'cume_dist'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Values identical (0.333..,0.666..,1) but Doris renders trailing 1.0 as '1' — numeric rendering only. Doris live; Trino from prior evidence.",
        areas = listOf("window", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
)

/** trino->doris lookup: 103 keys (Trino-side names) over 103 entries. */
internal val TRINO_TO_DORIS_HAZARDS: Map<String, FunctionHazard> = buildMap {
    put("ABS", TRINO_DORIS_HAZARD_ENTRIES[16])
    put("ACOS", TRINO_DORIS_HAZARD_ENTRIES[21])
    put("ANY_VALUE", TRINO_DORIS_HAZARD_ENTRIES[73])
    put("ARRAY_AGG", TRINO_DORIS_HAZARD_ENTRIES[89])
    put("ASCII", TRINO_DORIS_HAZARD_ENTRIES[8])
    put("ASIN", TRINO_DORIS_HAZARD_ENTRIES[22])
    put("ATAN", TRINO_DORIS_HAZARD_ENTRIES[30])
    put("ATAN2", TRINO_DORIS_HAZARD_ENTRIES[31])
    put("AVG", TRINO_DORIS_HAZARD_ENTRIES[66])
    put("BIT_COUNT", TRINO_DORIS_HAZARD_ENTRIES[12])
    put("BOOL_AND", TRINO_DORIS_HAZARD_ENTRIES[71])
    put("BOOL_OR", TRINO_DORIS_HAZARD_ENTRIES[72])
    put("CBRT", TRINO_DORIS_HAZARD_ENTRIES[29])
    put("CEIL", TRINO_DORIS_HAZARD_ENTRIES[38])
    put("CEILING", TRINO_DORIS_HAZARD_ENTRIES[39])
    put("COALESCE", TRINO_DORIS_HAZARD_ENTRIES[18])
    put("CONCAT", TRINO_DORIS_HAZARD_ENTRIES[2])
    put("CONCAT_WS", TRINO_DORIS_HAZARD_ENTRIES[64])
    put("CORR", TRINO_DORIS_HAZARD_ENTRIES[76])
    put("COS", TRINO_DORIS_HAZARD_ENTRIES[32])
    put("COSH", TRINO_DORIS_HAZARD_ENTRIES[33])
    put("COUNT", TRINO_DORIS_HAZARD_ENTRIES[68])
    put("COVAR_POP", TRINO_DORIS_HAZARD_ENTRIES[77])
    put("COVAR_SAMP", TRINO_DORIS_HAZARD_ENTRIES[78])
    put("CUME_DIST", TRINO_DORIS_HAZARD_ENTRIES[102])
    put("DEGREES", TRINO_DORIS_HAZARD_ENTRIES[41])
    put("DENSE_RANK", TRINO_DORIS_HAZARD_ENTRIES[94])
    put("EXP", TRINO_DORIS_HAZARD_ENTRIES[28])
    put("FIRST_VALUE", TRINO_DORIS_HAZARD_ENTRIES[98])
    put("FLOOR", TRINO_DORIS_HAZARD_ENTRIES[40])
    put("FMOD", TRINO_DORIS_HAZARD_ENTRIES[13])
    put("FORMAT_NUMBER", TRINO_DORIS_HAZARD_ENTRIES[49])
    put("FROM_BASE64", TRINO_DORIS_HAZARD_ENTRIES[57])
    put("FROM_HEX", TRINO_DORIS_HAZARD_ENTRIES[48])
    put("GREATEST", TRINO_DORIS_HAZARD_ENTRIES[3])
    put("HAMMING_DISTANCE", TRINO_DORIS_HAZARD_ENTRIES[55])
    put("HISTOGRAM", TRINO_DORIS_HAZARD_ENTRIES[91])
    put("KURTOSIS", TRINO_DORIS_HAZARD_ENTRIES[86])
    put("LAG", TRINO_DORIS_HAZARD_ENTRIES[96])
    put("LAST_VALUE", TRINO_DORIS_HAZARD_ENTRIES[99])
    put("LEAD", TRINO_DORIS_HAZARD_ENTRIES[97])
    put("LEAST", TRINO_DORIS_HAZARD_ENTRIES[4])
    put("LENGTH", TRINO_DORIS_HAZARD_ENTRIES[15])
    put("LEVENSHTEIN_DISTANCE", TRINO_DORIS_HAZARD_ENTRIES[54])
    put("LN", TRINO_DORIS_HAZARD_ENTRIES[23])
    put("LOG", TRINO_DORIS_HAZARD_ENTRIES[27])
    put("LOG10", TRINO_DORIS_HAZARD_ENTRIES[26])
    put("LOG2", TRINO_DORIS_HAZARD_ENTRIES[25])
    put("LOWER", TRINO_DORIS_HAZARD_ENTRIES[0])
    put("LPAD", TRINO_DORIS_HAZARD_ENTRIES[59])
    put("LTRIM", TRINO_DORIS_HAZARD_ENTRIES[10])
    put("MAP_AGG", TRINO_DORIS_HAZARD_ENTRIES[90])
    put("MAX", TRINO_DORIS_HAZARD_ENTRIES[69])
    put("MAX_BY", TRINO_DORIS_HAZARD_ENTRIES[74])
    put("MD5", TRINO_DORIS_HAZARD_ENTRIES[20])
    put("MIN", TRINO_DORIS_HAZARD_ENTRIES[70])
    put("MIN_BY", TRINO_DORIS_HAZARD_ENTRIES[75])
    put("MOD", TRINO_DORIS_HAZARD_ENTRIES[17])
    put("NTH_VALUE", TRINO_DORIS_HAZARD_ENTRIES[100])
    put("NTILE", TRINO_DORIS_HAZARD_ENTRIES[95])
    put("NULLIF", TRINO_DORIS_HAZARD_ENTRIES[19])
    put("PERCENT_RANK", TRINO_DORIS_HAZARD_ENTRIES[101])
    put("PI", TRINO_DORIS_HAZARD_ENTRIES[43])
    put("POW", TRINO_DORIS_HAZARD_ENTRIES[45])
    put("POWER", TRINO_DORIS_HAZARD_ENTRIES[46])
    put("RADIANS", TRINO_DORIS_HAZARD_ENTRIES[42])
    put("RANK", TRINO_DORIS_HAZARD_ENTRIES[93])
    put("REGEXP_EXTRACT_ALL", TRINO_DORIS_HAZARD_ENTRIES[14])
    put("REGEXP_REPLACE", TRINO_DORIS_HAZARD_ENTRIES[7])
    put("REGR_INTERCEPT", TRINO_DORIS_HAZARD_ENTRIES[87])
    put("REGR_SLOPE", TRINO_DORIS_HAZARD_ENTRIES[88])
    put("REPEAT", TRINO_DORIS_HAZARD_ENTRIES[61])
    put("REPLACE", TRINO_DORIS_HAZARD_ENTRIES[53])
    put("REVERSE", TRINO_DORIS_HAZARD_ENTRIES[6])
    put("ROW_NUMBER", TRINO_DORIS_HAZARD_ENTRIES[92])
    put("RPAD", TRINO_DORIS_HAZARD_ENTRIES[60])
    put("RTRIM", TRINO_DORIS_HAZARD_ENTRIES[11])
    put("SHA1", TRINO_DORIS_HAZARD_ENTRIES[52])
    put("SIGN", TRINO_DORIS_HAZARD_ENTRIES[44])
    put("SIN", TRINO_DORIS_HAZARD_ENTRIES[34])
    put("SINH", TRINO_DORIS_HAZARD_ENTRIES[35])
    put("SKEWNESS", TRINO_DORIS_HAZARD_ENTRIES[85])
    put("SOUNDEX", TRINO_DORIS_HAZARD_ENTRIES[56])
    put("SPLIT_PART", TRINO_DORIS_HAZARD_ENTRIES[5])
    put("SQRT", TRINO_DORIS_HAZARD_ENTRIES[24])
    put("STARTS_WITH", TRINO_DORIS_HAZARD_ENTRIES[51])
    put("STDDEV", TRINO_DORIS_HAZARD_ENTRIES[83])
    put("STDDEV_POP", TRINO_DORIS_HAZARD_ENTRIES[79])
    put("STDDEV_SAMP", TRINO_DORIS_HAZARD_ENTRIES[80])
    put("SUBSTR", TRINO_DORIS_HAZARD_ENTRIES[65])
    put("SUM", TRINO_DORIS_HAZARD_ENTRIES[67])
    put("TAN", TRINO_DORIS_HAZARD_ENTRIES[36])
    put("TANH", TRINO_DORIS_HAZARD_ENTRIES[37])
    put("TO_BASE64", TRINO_DORIS_HAZARD_ENTRIES[58])
    put("TO_HEX", TRINO_DORIS_HAZARD_ENTRIES[47])
    put("TRANSLATE", TRINO_DORIS_HAZARD_ENTRIES[62])
    put("TRIM", TRINO_DORIS_HAZARD_ENTRIES[9])
    put("UPPER", TRINO_DORIS_HAZARD_ENTRIES[1])
    put("URL_DECODE", TRINO_DORIS_HAZARD_ENTRIES[63])
    put("URL_ENCODE", TRINO_DORIS_HAZARD_ENTRIES[50])
    put("VARIANCE", TRINO_DORIS_HAZARD_ENTRIES[84])
    put("VAR_POP", TRINO_DORIS_HAZARD_ENTRIES[81])
    put("VAR_SAMP", TRINO_DORIS_HAZARD_ENTRIES[82])
}

/** doris->trino lookup: 103 keys (Doris-side names) over 103 entries. */
internal val DORIS_TO_TRINO_HAZARDS: Map<String, FunctionHazard> = buildMap {
    put("ABS", TRINO_DORIS_HAZARD_ENTRIES[16])
    put("ACOS", TRINO_DORIS_HAZARD_ENTRIES[21])
    put("ANY_VALUE", TRINO_DORIS_HAZARD_ENTRIES[73])
    put("ARRAY_AGG", TRINO_DORIS_HAZARD_ENTRIES[89])
    put("ASCII", TRINO_DORIS_HAZARD_ENTRIES[8])
    put("ASIN", TRINO_DORIS_HAZARD_ENTRIES[22])
    put("ATAN", TRINO_DORIS_HAZARD_ENTRIES[30])
    put("ATAN2", TRINO_DORIS_HAZARD_ENTRIES[31])
    put("AVG", TRINO_DORIS_HAZARD_ENTRIES[66])
    put("BIT_COUNT", TRINO_DORIS_HAZARD_ENTRIES[12])
    put("BOOL_AND", TRINO_DORIS_HAZARD_ENTRIES[71])
    put("BOOL_OR", TRINO_DORIS_HAZARD_ENTRIES[72])
    put("CBRT", TRINO_DORIS_HAZARD_ENTRIES[29])
    put("CEIL", TRINO_DORIS_HAZARD_ENTRIES[38])
    put("CEILING", TRINO_DORIS_HAZARD_ENTRIES[39])
    put("COALESCE", TRINO_DORIS_HAZARD_ENTRIES[18])
    put("CONCAT", TRINO_DORIS_HAZARD_ENTRIES[2])
    put("CONCAT_WS", TRINO_DORIS_HAZARD_ENTRIES[64])
    put("CORR", TRINO_DORIS_HAZARD_ENTRIES[76])
    put("COS", TRINO_DORIS_HAZARD_ENTRIES[32])
    put("COSH", TRINO_DORIS_HAZARD_ENTRIES[33])
    put("COUNT", TRINO_DORIS_HAZARD_ENTRIES[68])
    put("COVAR_POP", TRINO_DORIS_HAZARD_ENTRIES[77])
    put("COVAR_SAMP", TRINO_DORIS_HAZARD_ENTRIES[78])
    put("CUME_DIST", TRINO_DORIS_HAZARD_ENTRIES[102])
    put("DEGREES", TRINO_DORIS_HAZARD_ENTRIES[41])
    put("DENSE_RANK", TRINO_DORIS_HAZARD_ENTRIES[94])
    put("EXP", TRINO_DORIS_HAZARD_ENTRIES[28])
    put("FIRST_VALUE", TRINO_DORIS_HAZARD_ENTRIES[98])
    put("FLOOR", TRINO_DORIS_HAZARD_ENTRIES[40])
    put("FMOD", TRINO_DORIS_HAZARD_ENTRIES[13])
    put("FORMAT_NUMBER", TRINO_DORIS_HAZARD_ENTRIES[49])
    put("FROM_BASE64", TRINO_DORIS_HAZARD_ENTRIES[57])
    put("GREATEST", TRINO_DORIS_HAZARD_ENTRIES[3])
    put("HAMMING_DISTANCE", TRINO_DORIS_HAZARD_ENTRIES[55])
    put("HEX", TRINO_DORIS_HAZARD_ENTRIES[47])
    put("HISTOGRAM", TRINO_DORIS_HAZARD_ENTRIES[91])
    put("KURTOSIS", TRINO_DORIS_HAZARD_ENTRIES[86])
    put("LAG", TRINO_DORIS_HAZARD_ENTRIES[96])
    put("LAST_VALUE", TRINO_DORIS_HAZARD_ENTRIES[99])
    put("LEAD", TRINO_DORIS_HAZARD_ENTRIES[97])
    put("LEAST", TRINO_DORIS_HAZARD_ENTRIES[4])
    put("LENGTH", TRINO_DORIS_HAZARD_ENTRIES[15])
    put("LEVENSHTEIN", TRINO_DORIS_HAZARD_ENTRIES[54])
    put("LN", TRINO_DORIS_HAZARD_ENTRIES[23])
    put("LOG", TRINO_DORIS_HAZARD_ENTRIES[27])
    put("LOG10", TRINO_DORIS_HAZARD_ENTRIES[26])
    put("LOG2", TRINO_DORIS_HAZARD_ENTRIES[25])
    put("LOWER", TRINO_DORIS_HAZARD_ENTRIES[0])
    put("LPAD", TRINO_DORIS_HAZARD_ENTRIES[59])
    put("LTRIM", TRINO_DORIS_HAZARD_ENTRIES[10])
    put("MAP_AGG", TRINO_DORIS_HAZARD_ENTRIES[90])
    put("MAX", TRINO_DORIS_HAZARD_ENTRIES[69])
    put("MAX_BY", TRINO_DORIS_HAZARD_ENTRIES[74])
    put("MD5", TRINO_DORIS_HAZARD_ENTRIES[20])
    put("MIN", TRINO_DORIS_HAZARD_ENTRIES[70])
    put("MIN_BY", TRINO_DORIS_HAZARD_ENTRIES[75])
    put("MOD", TRINO_DORIS_HAZARD_ENTRIES[17])
    put("NTH_VALUE", TRINO_DORIS_HAZARD_ENTRIES[100])
    put("NTILE", TRINO_DORIS_HAZARD_ENTRIES[95])
    put("NULLIF", TRINO_DORIS_HAZARD_ENTRIES[19])
    put("PERCENT_RANK", TRINO_DORIS_HAZARD_ENTRIES[101])
    put("PI", TRINO_DORIS_HAZARD_ENTRIES[43])
    put("POW", TRINO_DORIS_HAZARD_ENTRIES[45])
    put("POWER", TRINO_DORIS_HAZARD_ENTRIES[46])
    put("RADIANS", TRINO_DORIS_HAZARD_ENTRIES[42])
    put("RANK", TRINO_DORIS_HAZARD_ENTRIES[93])
    put("REGEXP_EXTRACT_ALL", TRINO_DORIS_HAZARD_ENTRIES[14])
    put("REGEXP_REPLACE", TRINO_DORIS_HAZARD_ENTRIES[7])
    put("REGR_INTERCEPT", TRINO_DORIS_HAZARD_ENTRIES[87])
    put("REGR_SLOPE", TRINO_DORIS_HAZARD_ENTRIES[88])
    put("REPEAT", TRINO_DORIS_HAZARD_ENTRIES[61])
    put("REPLACE", TRINO_DORIS_HAZARD_ENTRIES[53])
    put("REVERSE", TRINO_DORIS_HAZARD_ENTRIES[6])
    put("ROW_NUMBER", TRINO_DORIS_HAZARD_ENTRIES[92])
    put("RPAD", TRINO_DORIS_HAZARD_ENTRIES[60])
    put("RTRIM", TRINO_DORIS_HAZARD_ENTRIES[11])
    put("SHA1", TRINO_DORIS_HAZARD_ENTRIES[52])
    put("SIGN", TRINO_DORIS_HAZARD_ENTRIES[44])
    put("SIN", TRINO_DORIS_HAZARD_ENTRIES[34])
    put("SINH", TRINO_DORIS_HAZARD_ENTRIES[35])
    put("SKEWNESS", TRINO_DORIS_HAZARD_ENTRIES[85])
    put("SOUNDEX", TRINO_DORIS_HAZARD_ENTRIES[56])
    put("SPLIT_PART", TRINO_DORIS_HAZARD_ENTRIES[5])
    put("SQRT", TRINO_DORIS_HAZARD_ENTRIES[24])
    put("STARTS_WITH", TRINO_DORIS_HAZARD_ENTRIES[51])
    put("STDDEV", TRINO_DORIS_HAZARD_ENTRIES[83])
    put("STDDEV_POP", TRINO_DORIS_HAZARD_ENTRIES[79])
    put("STDDEV_SAMP", TRINO_DORIS_HAZARD_ENTRIES[80])
    put("SUBSTR", TRINO_DORIS_HAZARD_ENTRIES[65])
    put("SUM", TRINO_DORIS_HAZARD_ENTRIES[67])
    put("TAN", TRINO_DORIS_HAZARD_ENTRIES[36])
    put("TANH", TRINO_DORIS_HAZARD_ENTRIES[37])
    put("TO_BASE64", TRINO_DORIS_HAZARD_ENTRIES[58])
    put("TRANSLATE", TRINO_DORIS_HAZARD_ENTRIES[62])
    put("TRIM", TRINO_DORIS_HAZARD_ENTRIES[9])
    put("UNHEX", TRINO_DORIS_HAZARD_ENTRIES[48])
    put("UPPER", TRINO_DORIS_HAZARD_ENTRIES[1])
    put("URL_DECODE", TRINO_DORIS_HAZARD_ENTRIES[63])
    put("URL_ENCODE", TRINO_DORIS_HAZARD_ENTRIES[50])
    put("VARIANCE", TRINO_DORIS_HAZARD_ENTRIES[84])
    put("VAR_POP", TRINO_DORIS_HAZARD_ENTRIES[81])
    put("VAR_SAMP", TRINO_DORIS_HAZARD_ENTRIES[82])
}
