// GENERATED FILE — DO NOT EDIT.
// Generated by tools/generate_hazards_registry.py from
// brikk-sql/testResources/semantics/duckdb-doris-hazards.json (brikk live-probe program,
// extracted 2026-07-13): live-probe-verified duckdb<->doris semantics
// verdicts. Regenerate after editing the JSON; the run is byte-deterministic.
//
// Keying and collision policy: see the tool's docstring / HazardRegistry KDoc
// (raw side-name + bare-identifier alternatives; collisions keep the WORST
// verdict, ties keep JSON order).
package dev.brikk.house.sql.metadata

/** The 21 probe-verified (duckdb, doris) pair verdicts, in JSON order. */
internal val DUCKDB_DORIS_HAZARD_ENTRIES: List<FunctionHazard> = hazardsChunk0()

private fun hazardsChunk0(): List<FunctionHazard> = listOf(
    // [0] duckdb: 'lower' | doris: 'lower'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): Turkish 'İ' (U+0130) -> DuckDB simple fold 'i' (U+0069); Doris full fold 'i' + combining dot (U+0069 U+0307). ASCII and most non-ASCII aligned; case-folding of special uppercase forms diverges.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#lower"),
    // [1] duckdb: 'upper' | doris: 'upper'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): German 'ß' (U+00DF) -> DuckDB 'ẞ' (U+1E9E) vs Doris 'SS' (length-changing full fold). ASCII aligned.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#upper"),
    // [2] duckdb: 'concat' | doris: 'concat'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): NULL handling. DuckDB SKIPS NULL args (concat('a',NULL,'c')='ac', concat(NULL,NULL)=''); Doris PROPAGATES NULL (both -> NULL). Never translate by name when any arg may be NULL.",
        areas = listOf("string", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#concat"),
    // [3] duckdb: 'greatest' | doris: 'greatest'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): DuckDB SKIPS NULLs (greatest(1,NULL,2)=2); Doris returns NULL if ANY arg is NULL. Never translate by name when args may be NULL.",
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#greatest-least"),
    // [4] duckdb: 'least' | doris: 'least'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): DuckDB SKIPS NULLs (least(1,NULL,2)=1); Doris returns NULL if ANY arg is NULL. Never translate by name when args may be NULL.",
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#greatest-least"),
    // [5] duckdb: 'split_part' | doris: 'split_part'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): out-of-bounds index -> DuckDB returns empty string ''; Doris returns NULL. In-bounds aligned. Do not translate by name without a NULLIF/coalesce wrap.",
        areas = listOf("string", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#split-part"),
    // [6] duckdb: 'reverse' | doris: 'reverse'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): DuckDB reverse is GRAPHEME-cluster-aware (decomposed 'e'+U+0301 stays together); Doris reverses CODE POINTS (combining mark floats to front). Precomposed and ASCII aligned.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#reverse"),
    // [7] duckdb: 'ascii' | doris: 'ascii'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): ascii('É' U+00C9) -> DuckDB 201 (Unicode codepoint of first char); Doris 195 (first UTF-8 byte, 0xC3). Diverges for any non-ASCII first char. ASCII aligned.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#ascii"),
    // [8] duckdb: 'regexp_replace' | doris: 'regexp_replace'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified (DuckDB↔Doris live): DuckDB replaces the FIRST match without a 'g' flag (regexp_replace('aaa','a','b')='baa'); Doris replaces ALL matches ('bbb'). A parity translation must force global replace.",
        areas = listOf("regex"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#regexp-replace"),
    // [9] duckdb: 'trim' | doris: 'trim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "DuckDB default trim strips space + EM SPACE (U+2003) + NBSP (U+00A0); Doris strips ASCII space only (keeps tab/EM/NBSP). Probe-verified live.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [10] duckdb: 'ltrim' | doris: 'ltrim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Same whitespace-set divergence as trim (Doris ASCII-space-only vs DuckDB space+EM+NBSP).",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [11] duckdb: 'rtrim' | doris: 'rtrim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Same whitespace-set divergence as trim.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [12] duckdb: 'bit_count' | doris: 'bit_count'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified: bit_count(-1) -> DuckDB 32 (INT32 width), Doris 8. Bit-width inference differs by operand type.",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [13] duckdb: 'fmod' | doris: 'fmod'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified: fmod(-5.3,2) -> DuckDB 0.70 vs Doris -1.30 (sign/definition differ for negative operands).",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [14] duckdb: 'regexp_extract_all' | doris: 'regexp_extract_all'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified: DuckDB returns the match array (['1','2','3']); Doris returned empty — signature/empty-match handling differs. Verify group-index semantics before translating.",
        areas = listOf("regex"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [15] duckdb: 'length' | doris: 'length'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified: Doris length() counts BYTES (length('世界')=6, length('héllo')=6); DuckDB counts CHARACTERS (2, 5). Use char_length for parity. Diverges from both engines.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [16] duckdb: 'abs' | doris: 'abs'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [17] duckdb: 'mod' | doris: 'mod'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [18] duckdb: 'coalesce' | doris: 'coalesce'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [19] duckdb: 'nullif' | doris: 'nullif'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [20] duckdb: 'md5' | doris: 'md5'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("hash"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
)

/** duckdb->doris lookup: 21 keys (DuckDB-side names) over 21 entries. */
internal val DUCKDB_TO_DORIS_HAZARDS: Map<String, FunctionHazard> = buildMap {
    put("ABS", DUCKDB_DORIS_HAZARD_ENTRIES[16])
    put("ASCII", DUCKDB_DORIS_HAZARD_ENTRIES[7])
    put("BIT_COUNT", DUCKDB_DORIS_HAZARD_ENTRIES[12])
    put("COALESCE", DUCKDB_DORIS_HAZARD_ENTRIES[18])
    put("CONCAT", DUCKDB_DORIS_HAZARD_ENTRIES[2])
    put("FMOD", DUCKDB_DORIS_HAZARD_ENTRIES[13])
    put("GREATEST", DUCKDB_DORIS_HAZARD_ENTRIES[3])
    put("LEAST", DUCKDB_DORIS_HAZARD_ENTRIES[4])
    put("LENGTH", DUCKDB_DORIS_HAZARD_ENTRIES[15])
    put("LOWER", DUCKDB_DORIS_HAZARD_ENTRIES[0])
    put("LTRIM", DUCKDB_DORIS_HAZARD_ENTRIES[10])
    put("MD5", DUCKDB_DORIS_HAZARD_ENTRIES[20])
    put("MOD", DUCKDB_DORIS_HAZARD_ENTRIES[17])
    put("NULLIF", DUCKDB_DORIS_HAZARD_ENTRIES[19])
    put("REGEXP_EXTRACT_ALL", DUCKDB_DORIS_HAZARD_ENTRIES[14])
    put("REGEXP_REPLACE", DUCKDB_DORIS_HAZARD_ENTRIES[8])
    put("REVERSE", DUCKDB_DORIS_HAZARD_ENTRIES[6])
    put("RTRIM", DUCKDB_DORIS_HAZARD_ENTRIES[11])
    put("SPLIT_PART", DUCKDB_DORIS_HAZARD_ENTRIES[5])
    put("TRIM", DUCKDB_DORIS_HAZARD_ENTRIES[9])
    put("UPPER", DUCKDB_DORIS_HAZARD_ENTRIES[1])
}

/** doris->duckdb lookup: 21 keys (Doris-side names) over 21 entries. */
internal val DORIS_TO_DUCKDB_HAZARDS: Map<String, FunctionHazard> = buildMap {
    put("ABS", DUCKDB_DORIS_HAZARD_ENTRIES[16])
    put("ASCII", DUCKDB_DORIS_HAZARD_ENTRIES[7])
    put("BIT_COUNT", DUCKDB_DORIS_HAZARD_ENTRIES[12])
    put("COALESCE", DUCKDB_DORIS_HAZARD_ENTRIES[18])
    put("CONCAT", DUCKDB_DORIS_HAZARD_ENTRIES[2])
    put("FMOD", DUCKDB_DORIS_HAZARD_ENTRIES[13])
    put("GREATEST", DUCKDB_DORIS_HAZARD_ENTRIES[3])
    put("LEAST", DUCKDB_DORIS_HAZARD_ENTRIES[4])
    put("LENGTH", DUCKDB_DORIS_HAZARD_ENTRIES[15])
    put("LOWER", DUCKDB_DORIS_HAZARD_ENTRIES[0])
    put("LTRIM", DUCKDB_DORIS_HAZARD_ENTRIES[10])
    put("MD5", DUCKDB_DORIS_HAZARD_ENTRIES[20])
    put("MOD", DUCKDB_DORIS_HAZARD_ENTRIES[17])
    put("NULLIF", DUCKDB_DORIS_HAZARD_ENTRIES[19])
    put("REGEXP_EXTRACT_ALL", DUCKDB_DORIS_HAZARD_ENTRIES[14])
    put("REGEXP_REPLACE", DUCKDB_DORIS_HAZARD_ENTRIES[8])
    put("REVERSE", DUCKDB_DORIS_HAZARD_ENTRIES[6])
    put("RTRIM", DUCKDB_DORIS_HAZARD_ENTRIES[11])
    put("SPLIT_PART", DUCKDB_DORIS_HAZARD_ENTRIES[5])
    put("TRIM", DUCKDB_DORIS_HAZARD_ENTRIES[9])
    put("UPPER", DUCKDB_DORIS_HAZARD_ENTRIES[1])
}
