// GENERATED FILE — DO NOT EDIT.
// Generated by tools/generate_trino_functions.py from vendor/data/trino-functions-481.tsv:
// Trino 481's own `SHOW FUNCTIONS` registry, dumped via an in-JVM
// DistributedQueryRunner harness pinned to that version (see vendor/README.md).
// Trino is Apache-2.0 licensed. See ATTRIBUTIONS.md.
//
// Modeling notes (SHOW FUNCTIONS caveats):
//  - variadic=false everywhere: SHOW FUNCTIONS does not flag variadics, so an
//    overload's arity is a LOWER bound (concat/greatest/least/coalesce accept
//    more arguments than the listed overloads suggest). Do not hard-enforce a
//    max arity from this catalog.
//  - parametric types (varchar(x), decimal(p,s)) and type variables (E, T, K, V,
//    unknown) are kept as literal strings — treat as "any" when mapping.
//  - operators (::, ||, %, CAST, TRY_CAST, subscript, ...) are grammar-level,
//    not functions, and are intentionally absent.
package dev.brikk.house.sql.metadata

/** Trino 481 built-in functions: 320 definitions, 654 overloads. */
val TRINO_FUNCTION_CATALOG: FunctionCatalog = FunctionCatalog(
    trinoChunk0() + trinoChunk1() + trinoChunk2(),
)

private fun trinoChunk0(): List<FunctionDef> = listOf(
    // scalar (257)
    FunctionDef("abs", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("decimal(p,s)"), "decimal(p,s)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("integer"), "integer"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("real"), "real"),
        FunctionOverload(listOf("smallint"), "smallint"),
        FunctionOverload(listOf("tinyint"), "tinyint"),
    )),
    FunctionDef("acos", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("all_match", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "function(t,boolean)"), "boolean"),
    )),
    FunctionDef("any_match", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "function(t,boolean)"), "boolean"),
    )),
    FunctionDef("array_distinct", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)"), "array(e)"),
    )),
    FunctionDef("array_except", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "array(e)"), "array(e)"),
    )),
    FunctionDef("array_first", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)"), "e"),
        FunctionOverload(listOf("array(e)", "function(e,boolean)"), "e"),
    )),
    FunctionDef("array_histogram", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)"), "map(t,bigint)"),
    )),
    FunctionDef("array_intersect", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "array(e)"), "array(e)"),
    )),
    FunctionDef("array_join", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "varchar"), "varchar"),
        FunctionOverload(listOf("array(e)", "varchar", "varchar"), "varchar"),
    )),
    FunctionDef("array_last", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)"), "e"),
    )),
    FunctionDef("array_max", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)"), "t"),
    )),
    FunctionDef("array_min", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)"), "t"),
    )),
    FunctionDef("array_position", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "t"), "bigint"),
    )),
    FunctionDef("array_remove", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "e"), "array(e)"),
    )),
    FunctionDef("array_sort", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)"), "array(e)"),
        FunctionOverload(listOf("array(t)", "function(t,t,integer)"), "array(t)"),
    )),
    FunctionDef("array_union", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "array(e)"), "array(e)"),
    )),
    FunctionDef("arrays_overlap", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "array(e)"), "boolean"),
    )),
    FunctionDef("asin", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("at_timezone", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("timestamp(p) with time zone", "varchar(x)"), "timestamp(p) with time zone"),
    )),
    FunctionDef("atan", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("atan2", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
    )),
    FunctionDef("bar", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "bigint"), "varchar"),
        FunctionOverload(listOf("double", "bigint", "color", "color"), "varchar"),
    )),
    FunctionDef("beta_cdf", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double", "double"), "double"),
    )),
    FunctionDef("bit_count", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint"), "bigint"),
    )),
    FunctionDef("bitwise_and", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint"), "bigint"),
    )),
    FunctionDef("bitwise_left_shift", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "integer"), "bigint"),
        FunctionOverload(listOf("integer", "integer"), "integer"),
        FunctionOverload(listOf("smallint", "integer"), "smallint"),
        FunctionOverload(listOf("tinyint", "integer"), "tinyint"),
    )),
    FunctionDef("bitwise_not", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
    )),
    FunctionDef("bitwise_or", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint"), "bigint"),
    )),
    FunctionDef("bitwise_right_shift", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "integer"), "bigint"),
        FunctionOverload(listOf("integer", "integer"), "integer"),
        FunctionOverload(listOf("smallint", "integer"), "smallint"),
        FunctionOverload(listOf("tinyint", "integer"), "tinyint"),
    )),
    FunctionDef("bitwise_right_shift_arithmetic", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "integer"), "bigint"),
        FunctionOverload(listOf("integer", "integer"), "integer"),
        FunctionOverload(listOf("smallint", "integer"), "smallint"),
        FunctionOverload(listOf("tinyint", "integer"), "tinyint"),
    )),
    FunctionDef("bitwise_xor", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint"), "bigint"),
    )),
    FunctionDef("cardinality", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)"), "bigint"),
        FunctionOverload(listOf("hyperloglog"), "bigint"),
        FunctionOverload(listOf("map(k,v)"), "bigint"),
        FunctionOverload(listOf("setdigest"), "bigint"),
    )),
    FunctionDef("cbrt", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("ceil", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("decimal(p,s)"), "decimal(rp,0)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("integer"), "integer"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("real"), "real"),
        FunctionOverload(listOf("smallint"), "smallint"),
        FunctionOverload(listOf("tinyint"), "tinyint"),
    )),
    FunctionDef("ceiling", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("decimal(p,s)"), "decimal(rp,0)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("integer"), "integer"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("real"), "real"),
        FunctionOverload(listOf("smallint"), "smallint"),
        FunctionOverload(listOf("tinyint"), "tinyint"),
    )),
    FunctionDef("chr", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "varchar(1)"),
    )),
    FunctionDef("codepoint", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(1)"), "integer"),
    )),
    FunctionDef("color", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "color", "color"), "color"),
        FunctionOverload(listOf("double", "double", "double", "color", "color"), "color"),
        FunctionOverload(listOf("varchar(x)"), "color"),
    )),
    FunctionDef("combinations", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "integer"), "array(array(t))"),
    )),
    FunctionDef("concat", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("E", "array(E)"), "array(E)"),
        FunctionOverload(listOf("array(E)"), "array(E)"),
        FunctionOverload(listOf("array(E)", "E"), "array(E)"),
        FunctionOverload(listOf("char(x)", "char(y)"), "char(u)"),
        FunctionOverload(listOf("varbinary"), "varbinary"),
        FunctionOverload(listOf("varchar"), "varchar"),
    )),
    FunctionDef("concat_ws", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar", "array(varchar)"), "varchar"),
        FunctionOverload(listOf("varchar", "varchar"), "varchar"),
    )),
    FunctionDef("contains", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "t"), "boolean"),
        FunctionOverload(listOf("varchar", "ipaddress"), "boolean"),
    )),
    FunctionDef("contains_sequence", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "array(t)"), "boolean"),
    )),
    FunctionDef("cos", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("cosh", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("cosine_distance", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(double)", "array(double)"), "double"),
        FunctionOverload(listOf("map(varchar,double)", "map(varchar,double)"), "double"),
    )),
    FunctionDef("cosine_similarity", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(double)", "array(double)"), "double"),
        FunctionOverload(listOf("map(varchar,double)", "map(varchar,double)"), "double"),
    )),
    FunctionDef("crc32", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "bigint"),
    )),
    FunctionDef("create_hll", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "hyperloglog"),
    )),
    FunctionDef("current_date", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "date"),
    )),
    FunctionDef("current_groups", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "array(varchar)"),
    )),
    FunctionDef("current_timezone", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "varchar"),
    )),
    FunctionDef("custom_add", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint"), "bigint"),
    )),
    FunctionDef("date", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("timestamp(p)"), "date"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "date"),
        FunctionOverload(listOf("varchar(x)"), "date"),
    )),
    FunctionDef("date_add", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "bigint", "date"), "date"),
        FunctionOverload(listOf("varchar(x)", "bigint", "time(p)"), "time(p)"),
        FunctionOverload(listOf("varchar(x)", "bigint", "time(p) with time zone"), "time(p) with time zone"),
        FunctionOverload(listOf("varchar(x)", "bigint", "timestamp(p)"), "timestamp(p)"),
        FunctionOverload(listOf("varchar(x)", "bigint", "timestamp(p) with time zone"), "timestamp(p) with time zone"),
    )),
    FunctionDef("date_diff", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "date", "date"), "bigint"),
        FunctionOverload(listOf("varchar(x)", "time(p)", "time(p)"), "bigint"),
        FunctionOverload(listOf("varchar(x)", "time(p) with time zone", "time(p) with time zone"), "bigint"),
        FunctionOverload(listOf("varchar(x)", "timestamp(p)", "timestamp(p)"), "bigint"),
        FunctionOverload(listOf("varchar(x)", "timestamp(p) with time zone", "timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("date_format", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("timestamp(p)", "varchar(x)"), "varchar"),
        FunctionOverload(listOf("timestamp(p) with time zone", "varchar(x)"), "varchar"),
    )),
    FunctionDef("date_parse", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "timestamp(3)"),
    )),
    FunctionDef("date_trunc", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "date"), "date"),
        FunctionOverload(listOf("varchar(x)", "time(p)"), "time(p)"),
        FunctionOverload(listOf("varchar(x)", "time(p) with time zone"), "time(p) with time zone"),
        FunctionOverload(listOf("varchar(x)", "timestamp(p)"), "timestamp(p)"),
        FunctionOverload(listOf("varchar(x)", "timestamp(p) with time zone"), "timestamp(p) with time zone"),
    )),
    FunctionDef("day", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("interval day to second"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("day_of_month", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("interval day to second"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("day_of_week", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("day_of_year", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("degrees", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("dot_product", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(double)", "array(double)"), "double"),
    )),
    FunctionDef("dow", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("doy", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("e", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "double"),
    )),
    FunctionDef("element_at", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "bigint"), "e"),
        FunctionOverload(listOf("map(K,V)", "K"), "V"),
    )),
    FunctionDef("empty_approx_set", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "hyperloglog"),
    )),
    FunctionDef("euclidean_distance", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(double)", "array(double)"), "double"),
    )),
    FunctionDef("exp", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("filter", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "function(t,boolean)"), "array(t)"),
    )),
    FunctionDef("flatten", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(array(E))"), "array(E)"),
    )),
    FunctionDef("floor", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("decimal(p,s)"), "decimal(rp,0)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("integer"), "integer"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("real"), "real"),
        FunctionOverload(listOf("smallint"), "smallint"),
        FunctionOverload(listOf("tinyint"), "tinyint"),
    )),
    FunctionDef("format_datetime", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("timestamp(p)", "varchar(x)"), "varchar"),
        FunctionOverload(listOf("timestamp(p) with time zone", "varchar(x)"), "varchar"),
    )),
    FunctionDef("format_number", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "varchar"),
        FunctionOverload(listOf("double"), "varchar"),
    )),
    FunctionDef("from_base", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "bigint"), "bigint"),
    )),
    FunctionDef("from_base32", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
        FunctionOverload(listOf("varchar(x)"), "varbinary"),
    )),
    FunctionDef("from_base64", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
        FunctionOverload(listOf("varchar(x)"), "varbinary"),
    )),
    FunctionDef("from_base64url", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
        FunctionOverload(listOf("varchar(x)"), "varbinary"),
    )),
    FunctionDef("from_big_endian_32", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "integer"),
    )),
    FunctionDef("from_big_endian_64", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "bigint"),
    )),
    FunctionDef("from_hex", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
        FunctionOverload(listOf("varchar(x)"), "varbinary"),
    )),
    FunctionDef("from_ieee754_32", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "real"),
    )),
    FunctionDef("from_ieee754_64", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "double"),
    )),
    FunctionDef("from_iso8601_date", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "date"),
    )),
    FunctionDef("from_iso8601_timestamp", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "timestamp(3) with time zone"),
    )),
    FunctionDef("from_iso8601_timestamp_nanos", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "timestamp(9) with time zone"),
    )),
    FunctionDef("from_unixtime", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "timestamp(3) with time zone"),
        FunctionOverload(listOf("double", "bigint", "bigint"), "timestamp(3) with time zone"),
        FunctionOverload(listOf("double", "varchar(x)"), "timestamp(3) with time zone"),
    )),
    FunctionDef("from_unixtime_nanos", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "timestamp(9) with time zone"),
        FunctionOverload(listOf("decimal(p,s)"), "timestamp(9) with time zone"),
    )),
    FunctionDef("from_utf8", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varchar"),
        FunctionOverload(listOf("varbinary", "bigint"), "varchar"),
        FunctionOverload(listOf("varbinary", "varchar(x)"), "varchar"),
    )),
    FunctionDef("greatest", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("E"), "E"),
    )),
    FunctionDef("hamming_distance", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "bigint"),
    )),
    FunctionDef("hash_counts", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("setdigest"), "map(bigint,smallint)"),
    )),
    FunctionDef("hmac_md5", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary", "varbinary"), "varbinary"),
    )),
    FunctionDef("hmac_sha1", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary", "varbinary"), "varbinary"),
    )),
    FunctionDef("hmac_sha256", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary", "varbinary"), "varbinary"),
    )),
    FunctionDef("hmac_sha512", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary", "varbinary"), "varbinary"),
    )),
    FunctionDef("hour", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("interval day to second"), "bigint"),
        FunctionOverload(listOf("time(p)"), "bigint"),
        FunctionOverload(listOf("time(p) with time zone"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("human_readable_seconds", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "varchar"),
    )),
    FunctionDef("infinity", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "double"),
    )),
    FunctionDef("intersection_cardinality", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("setdigest", "setdigest"), "bigint"),
    )),
    FunctionDef("inverse_beta_cdf", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double", "double"), "double"),
    )),
    FunctionDef("inverse_normal_cdf", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double", "double"), "double"),
    )),
    FunctionDef("is_finite", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "boolean"),
        FunctionOverload(listOf("number"), "boolean"),
        FunctionOverload(listOf("real"), "boolean"),
    )),
    FunctionDef("is_infinite", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "boolean"),
        FunctionOverload(listOf("number"), "boolean"),
    )),
    FunctionDef("is_json_scalar", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("json"), "boolean"),
        FunctionOverload(listOf("varchar(x)"), "boolean"),
    )),
    FunctionDef("is_nan", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "boolean"),
        FunctionOverload(listOf("number"), "boolean"),
        FunctionOverload(listOf("real"), "boolean"),
    )),
    FunctionDef("jaccard_index", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("setdigest", "setdigest"), "double"),
    )),
    FunctionDef("json_array_contains", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("json", "bigint"), "boolean"),
        FunctionOverload(listOf("json", "boolean"), "boolean"),
        FunctionOverload(listOf("json", "double"), "boolean"),
        FunctionOverload(listOf("json", "varchar(x)"), "boolean"),
        FunctionOverload(listOf("varchar(x)", "bigint"), "boolean"),
        FunctionOverload(listOf("varchar(x)", "boolean"), "boolean"),
        FunctionOverload(listOf("varchar(x)", "double"), "boolean"),
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "boolean"),
    )),
    FunctionDef("json_array_get", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("json", "bigint"), "json"),
        FunctionOverload(listOf("varchar(x)", "bigint"), "json"),
    )),
    FunctionDef("json_array_length", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("json"), "bigint"),
        FunctionOverload(listOf("varchar(x)"), "bigint"),
    )),
    FunctionDef("json_extract", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("json", "jsonpath"), "json"),
        FunctionOverload(listOf("varchar(x)", "jsonpath"), "json"),
    )),
    FunctionDef("json_extract_scalar", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("json", "jsonpath"), "varchar"),
        FunctionOverload(listOf("varchar(x)", "jsonpath"), "varchar(x)"),
    )),
    FunctionDef("json_format", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("json"), "varchar"),
    )),
    FunctionDef("json_parse", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "json"),
    )),
    FunctionDef("json_size", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("json", "jsonpath"), "bigint"),
        FunctionOverload(listOf("varchar(x)", "jsonpath"), "bigint"),
    )),
    FunctionDef("last_day_of_month", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "date"),
        FunctionOverload(listOf("timestamp(p)"), "date"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "date"),
    )),
    FunctionDef("least", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("E"), "E"),
    )),
    FunctionDef("length", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)"), "bigint"),
        FunctionOverload(listOf("varbinary"), "bigint"),
        FunctionOverload(listOf("varchar(x)"), "bigint"),
    )),
    FunctionDef("levenshtein_distance", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "bigint"),
    )),
    FunctionDef("ln", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("log", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
    )),
    FunctionDef("log10", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("log2", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("lower", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)"), "char(x)"),
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("lpad", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)", "bigint", "varchar(y)"), "varchar"),
        FunctionOverload(listOf("varbinary", "bigint", "varbinary"), "varbinary"),
        FunctionOverload(listOf("varchar(x)", "bigint", "varchar(y)"), "varchar"),
    )),
    FunctionDef("ltrim", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)"), "varchar(x)"),
        FunctionOverload(listOf("char(x)", "codepoints"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "codepoints"), "varchar(x)"),
    )),
    FunctionDef("luhn_check", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar"), "boolean"),
    )),
    FunctionDef("map", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "map(unknown,unknown)"),
        FunctionOverload(listOf("array(K)", "array(V)"), "map(K,V)"),
    )),
    FunctionDef("map_concat", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("map(K,V)"), "map(K,V)"),
    )),
    FunctionDef("map_entries", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("map(k,v)"), "array(row(k,v))"),
    )),
    FunctionDef("map_filter", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("map(K,V)", "function(K,V,boolean)"), "map(K,V)"),
    )),
)

private fun trinoChunk1(): List<FunctionDef> = listOf(
    FunctionDef("map_from_entries", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(row(k,v))"), "map(k,v)"),
    )),
    FunctionDef("map_keys", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("map(k,v)"), "array(k)"),
    )),
    FunctionDef("map_values", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("map(k,v)"), "array(v)"),
    )),
    FunctionDef("map_zip_with", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("map(K,V1)", "map(K,V2)", "function(K,V1,V2,V3)"), "map(K,V3)"),
    )),
    FunctionDef("md5", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
    )),
    FunctionDef("millisecond", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("interval day to second"), "bigint"),
        FunctionOverload(listOf("time(p)"), "bigint"),
        FunctionOverload(listOf("time(p) with time zone"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("minute", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("interval day to second"), "bigint"),
        FunctionOverload(listOf("time(p)"), "bigint"),
        FunctionOverload(listOf("time(p) with time zone"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("mod", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint"), "bigint"),
        FunctionOverload(listOf("decimal(a_precision,a_scale)", "decimal(b_precision,b_scale)"), "decimal(r_precision,r_scale)"),
        FunctionOverload(listOf("double", "double"), "double"),
        FunctionOverload(listOf("integer", "integer"), "integer"),
        FunctionOverload(listOf("number", "number"), "number"),
        FunctionOverload(listOf("real", "real"), "real"),
        FunctionOverload(listOf("smallint", "smallint"), "smallint"),
        FunctionOverload(listOf("tinyint", "tinyint"), "tinyint"),
    )),
    FunctionDef("month", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("interval year to month"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("multimap_from_entries", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(row(k,v))"), "map(k,array(v))"),
    )),
    FunctionDef("murmur3", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
    )),
    FunctionDef("nan", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "double"),
    )),
    FunctionDef("ngrams", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "integer"), "array(array(t))"),
    )),
    FunctionDef("none_match", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(t)", "function(t,boolean)"), "boolean"),
    )),
    FunctionDef("normal_cdf", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double", "double"), "double"),
    )),
    FunctionDef("normalize", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "varchar"),
    )),
    FunctionDef("now", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "timestamp(3) with time zone"),
    )),
    FunctionDef("parse_data_size", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "decimal(38,0)"),
    )),
    FunctionDef("parse_datetime", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "timestamp(3) with time zone"),
    )),
    FunctionDef("parse_duration", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "interval day to second"),
    )),
    FunctionDef("parse_presto_data_size", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "decimal(38,0)"),
    )),
    FunctionDef("pi", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "double"),
    )),
    FunctionDef("pow", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
    )),
    FunctionDef("power", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
    )),
    FunctionDef("quantile_at_value", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("qdigest(bigint)", "bigint"), "double"),
        FunctionOverload(listOf("qdigest(double)", "double"), "double"),
        FunctionOverload(listOf("qdigest(real)", "real"), "double"),
    )),
    FunctionDef("quarter", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("radians", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("rand", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "double"),
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("bigint", "bigint"), "bigint"),
        FunctionOverload(listOf("integer"), "integer"),
        FunctionOverload(listOf("integer", "integer"), "integer"),
        FunctionOverload(listOf("smallint"), "smallint"),
        FunctionOverload(listOf("smallint", "smallint"), "smallint"),
        FunctionOverload(listOf("tinyint"), "tinyint"),
        FunctionOverload(listOf("tinyint", "tinyint"), "tinyint"),
    )),
    FunctionDef("random", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "double"),
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("bigint", "bigint"), "bigint"),
        FunctionOverload(listOf("integer"), "integer"),
        FunctionOverload(listOf("integer", "integer"), "integer"),
        FunctionOverload(listOf("smallint"), "smallint"),
        FunctionOverload(listOf("smallint", "smallint"), "smallint"),
        FunctionOverload(listOf("tinyint"), "tinyint"),
        FunctionOverload(listOf("tinyint", "tinyint"), "tinyint"),
    )),
    FunctionDef("reduce", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(T)", "S", "function(S,T,S)", "function(S,R)"), "R"),
    )),
    FunctionDef("regexp_count", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "joniregexp"), "bigint"),
    )),
    FunctionDef("regexp_extract", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "joniregexp"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "joniregexp", "bigint"), "varchar(x)"),
    )),
    FunctionDef("regexp_extract_all", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "joniregexp"), "array(varchar(x))"),
        FunctionOverload(listOf("varchar(x)", "joniregexp", "bigint"), "array(varchar(x))"),
    )),
    FunctionDef("regexp_like", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "joniregexp"), "boolean"),
    )),
    FunctionDef("regexp_position", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "joniregexp"), "integer"),
        FunctionOverload(listOf("varchar(x)", "joniregexp", "integer"), "integer"),
        FunctionOverload(listOf("varchar(x)", "joniregexp", "integer", "integer"), "integer"),
    )),
    FunctionDef("regexp_replace", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar", "joniregexp", "function(array(varchar),varchar(x))"), "varchar"),
        FunctionOverload(listOf("varchar(x)", "joniregexp"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "joniregexp", "varchar(y)"), "varchar(z)"),
    )),
    FunctionDef("regexp_split", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "joniregexp"), "array(varchar(x))"),
    )),
    FunctionDef("render", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "color"), "varchar(35)"),
        FunctionOverload(listOf("boolean"), "varchar(16)"),
        FunctionOverload(listOf("double", "color"), "varchar(41)"),
        FunctionOverload(listOf("varchar(x)", "color"), "varchar(y)"),
    )),
    FunctionDef("repeat", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("t", "bigint"), "array(t)"),
    )),
    FunctionDef("replace", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "varchar(y)", "varchar(z)"), "varchar(u)"),
    )),
    FunctionDef("reverse", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)"), "array(e)"),
        FunctionOverload(listOf("char(x)"), "char(x)"),
        FunctionOverload(listOf("varbinary"), "varbinary"),
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("rgb", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint", "bigint"), "color"),
    )),
    FunctionDef("round", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("bigint", "integer"), "bigint"),
        FunctionOverload(listOf("decimal(p,s)"), "decimal(rp,rs)"),
        FunctionOverload(listOf("decimal(p,s)", "integer"), "decimal(rp,s)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("double", "integer"), "double"),
        FunctionOverload(listOf("integer"), "integer"),
        FunctionOverload(listOf("integer", "integer"), "integer"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("number", "integer"), "number"),
        FunctionOverload(listOf("real"), "real"),
        FunctionOverload(listOf("real", "integer"), "real"),
        FunctionOverload(listOf("smallint"), "smallint"),
        FunctionOverload(listOf("smallint", "integer"), "smallint"),
        FunctionOverload(listOf("tinyint"), "tinyint"),
        FunctionOverload(listOf("tinyint", "integer"), "tinyint"),
    )),
    FunctionDef("rpad", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary", "bigint", "varbinary"), "varbinary"),
        FunctionOverload(listOf("varchar(x)", "bigint", "varchar(y)"), "varchar"),
    )),
    FunctionDef("rtrim", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)"), "varchar(x)"),
        FunctionOverload(listOf("char(x)", "codepoints"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "codepoints"), "varchar(x)"),
    )),
    FunctionDef("second", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("interval day to second"), "bigint"),
        FunctionOverload(listOf("time(p)"), "bigint"),
        FunctionOverload(listOf("time(p) with time zone"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("sequence", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint"), "array(bigint)"),
        FunctionOverload(listOf("bigint", "bigint", "bigint"), "array(bigint)"),
        FunctionOverload(listOf("date", "date"), "array(date)"),
        FunctionOverload(listOf("date", "date", "interval day to second"), "array(date)"),
        FunctionOverload(listOf("date", "date", "interval year to month"), "array(date)"),
        FunctionOverload(listOf("timestamp(p)", "timestamp(p)", "interval day to second"), "array(timestamp(p))"),
        FunctionOverload(listOf("timestamp(p)", "timestamp(p)", "interval year to month"), "array(timestamp(p))"),
    )),
    FunctionDef("sha1", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
    )),
    FunctionDef("sha256", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
    )),
    FunctionDef("sha512", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
    )),
    FunctionDef("shuffle", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)"), "array(e)"),
    )),
    FunctionDef("sign", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("decimal(p,s)"), "decimal(1,0)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("integer"), "integer"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("real"), "real"),
        FunctionOverload(listOf("smallint"), "smallint"),
        FunctionOverload(listOf("tinyint"), "tinyint"),
    )),
    FunctionDef("sin", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("sinh", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("slice", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "bigint", "bigint"), "array(e)"),
    )),
    FunctionDef("soundex", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar"), "varchar(4)"),
    )),
    FunctionDef("split", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "array(varchar(x))"),
        FunctionOverload(listOf("varchar(x)", "varchar(y)", "bigint"), "array(varchar(x))"),
    )),
    FunctionDef("split_part", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)", "bigint"), "varchar(x)"),
    )),
    FunctionDef("split_to_map", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar", "varchar", "varchar"), "map(varchar,varchar)"),
    )),
    FunctionDef("split_to_multimap", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar", "varchar", "varchar"), "map(varchar,array(varchar))"),
    )),
    FunctionDef("spooky_hash_v2_32", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
    )),
    FunctionDef("spooky_hash_v2_64", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
    )),
    FunctionDef("sqrt", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("starts_with", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "boolean"),
    )),
    FunctionDef("strpos", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "bigint"),
        FunctionOverload(listOf("varchar(x)", "varchar(y)", "bigint"), "bigint"),
    )),
    FunctionDef("substr", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)", "bigint"), "varchar(x)"),
        FunctionOverload(listOf("char(x)", "bigint", "bigint"), "varchar(x)"),
        FunctionOverload(listOf("varbinary", "bigint"), "varbinary"),
        FunctionOverload(listOf("varbinary", "bigint", "bigint"), "varbinary"),
        FunctionOverload(listOf("varchar(x)", "bigint"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "bigint", "bigint"), "varchar(x)"),
    )),
    FunctionDef("substring", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)", "bigint"), "varchar(x)"),
        FunctionOverload(listOf("char(x)", "bigint", "bigint"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "bigint"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "bigint", "bigint"), "varchar(x)"),
    )),
    FunctionDef("t_cdf", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
    )),
    FunctionDef("t_pdf", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
    )),
    FunctionDef("tan", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("tanh", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("timezone", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("time(p) with time zone"), "varchar"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "varchar"),
    )),
    FunctionDef("timezone_hour", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("time(p) with time zone"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("timezone_minute", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("time(p) with time zone"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("to_base", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint"), "varchar(64)"),
    )),
    FunctionDef("to_base32", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varchar"),
    )),
    FunctionDef("to_base64", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varchar"),
    )),
    FunctionDef("to_base64url", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varchar"),
    )),
    FunctionDef("to_big_endian_32", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("integer"), "varbinary"),
    )),
    FunctionDef("to_big_endian_64", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint"), "varbinary"),
    )),
    FunctionDef("to_hex", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varchar"),
    )),
    FunctionDef("to_ieee754_32", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("real"), "varbinary"),
    )),
    FunctionDef("to_ieee754_64", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double"), "varbinary"),
    )),
    FunctionDef("to_iso8601", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "varchar(16)"),
        FunctionOverload(listOf("timestamp(p)"), "varchar(n)"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "varchar(n)"),
    )),
    FunctionDef("to_milliseconds", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("interval day to second"), "bigint"),
    )),
    FunctionDef("to_unixtime", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("timestamp(p) with time zone"), "double"),
    )),
    FunctionDef("to_utf8", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)"), "varbinary"),
        FunctionOverload(listOf("varchar(x)"), "varbinary"),
    )),
    FunctionDef("transform", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(T)", "function(T,U)"), "array(U)"),
    )),
    FunctionDef("transform_keys", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("map(K1,V)", "function(K1,V,K2)"), "map(K2,V)"),
    )),
    FunctionDef("transform_values", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("map(K,V1)", "function(K,V1,V2)"), "map(K,V2)"),
    )),
    FunctionDef("translate", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)", "varchar(z)"), "varchar"),
    )),
    FunctionDef("trim", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)"), "varchar(x)"),
        FunctionOverload(listOf("char(x)", "codepoints"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "codepoints"), "varchar(x)"),
    )),
    FunctionDef("trim_array", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(e)", "bigint"), "array(e)"),
    )),
    FunctionDef("truncate", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("decimal(p,s)"), "decimal(rp,0)"),
        FunctionOverload(listOf("decimal(p,s)", "integer"), "decimal(p,s)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("real"), "real"),
    )),
    FunctionDef("typeof", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("t"), "varchar"),
    )),
    FunctionDef("upper", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("char(x)"), "char(x)"),
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("url_decode", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("url_encode", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "varchar(y)"),
    )),
    FunctionDef("url_extract_fragment", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("url_extract_host", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("url_extract_parameter", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)", "varchar(y)"), "varchar(x)"),
    )),
    FunctionDef("url_extract_path", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("url_extract_port", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "bigint"),
    )),
    FunctionDef("url_extract_protocol", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("url_extract_query", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
    )),
    FunctionDef("uuid", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf(), "uuid"),
    )),
    FunctionDef("value_at_quantile", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("qdigest(bigint)", "double"), "bigint"),
        FunctionOverload(listOf("qdigest(double)", "double"), "double"),
        FunctionOverload(listOf("qdigest(real)", "double"), "real"),
        FunctionOverload(listOf("tdigest", "double"), "double"),
    )),
    FunctionDef("values_at_quantiles", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("qdigest(bigint)", "array(double)"), "array(bigint)"),
        FunctionOverload(listOf("qdigest(double)", "array(double)"), "array(double)"),
        FunctionOverload(listOf("qdigest(real)", "array(double)"), "array(real)"),
        FunctionOverload(listOf("tdigest", "array(double)"), "array(double)"),
    )),
    FunctionDef("variant_is_null", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("variant"), "boolean"),
    )),
    FunctionDef("week", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("week_of_year", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("width_bucket", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("double", "array(double)"), "bigint"),
        FunctionOverload(listOf("double", "double", "double", "bigint"), "bigint"),
    )),
    FunctionDef("wilson_interval_lower", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint", "double"), "double"),
    )),
    FunctionDef("wilson_interval_upper", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint", "double"), "double"),
    )),
    FunctionDef("with_timezone", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("timestamp(p)", "varchar(x)"), "timestamp(p) with time zone"),
    )),
    FunctionDef("word_stem", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varchar(x)"), "varchar(x)"),
        FunctionOverload(listOf("varchar(x)", "varchar(2)"), "varchar(x)"),
    )),
    FunctionDef("xxhash64", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("varbinary"), "varbinary"),
    )),
    FunctionDef("year", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("interval year to month"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("year_of_week", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("yow", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("date"), "bigint"),
        FunctionOverload(listOf("timestamp(p)"), "bigint"),
        FunctionOverload(listOf("timestamp(p) with time zone"), "bigint"),
    )),
    FunctionDef("zip", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(T1)", "array(T2)"), "array(row(T1,T2))"),
        FunctionOverload(listOf("array(T1)", "array(T2)", "array(T3)"), "array(row(T1,T2,T3))"),
        FunctionOverload(listOf("array(T1)", "array(T2)", "array(T3)", "array(T4)"), "array(row(T1,T2,T3,T4))"),
        FunctionOverload(listOf("array(T1)", "array(T2)", "array(T3)", "array(T4)", "array(T5)"), "array(row(T1,T2,T3,T4,T5))"),
    )),
    FunctionDef("zip_with", FunctionKind.SCALAR, overloads = listOf(
        FunctionOverload(listOf("array(T)", "array(U)", "function(T,U,R)"), "array(R)"),
    )),
    // aggregate (49)
    FunctionDef("any_value", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("t"), "t"),
    )),
    FunctionDef("approx_distinct", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("boolean"), "bigint"),
        FunctionOverload(listOf("boolean", "double"), "bigint"),
        FunctionOverload(listOf("t"), "bigint"),
        FunctionOverload(listOf("t", "double"), "bigint"),
        FunctionOverload(listOf("unknown"), "bigint"),
        FunctionOverload(listOf("unknown", "double"), "bigint"),
    )),
    FunctionDef("approx_most_frequent", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint", "bigint"), "map(bigint,bigint)"),
        FunctionOverload(listOf("bigint", "varchar", "bigint"), "map(varchar,bigint)"),
    )),
)

private fun trinoChunk2(): List<FunctionDef> = listOf(
    FunctionDef("approx_percentile", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint", "array(double)"), "array(bigint)"),
        FunctionOverload(listOf("bigint", "double"), "bigint"),
        FunctionOverload(listOf("bigint", "double", "array(double)"), "array(bigint)"),
        FunctionOverload(listOf("bigint", "double", "double"), "bigint"),
        FunctionOverload(listOf("bigint", "double", "double", "double"), "bigint"),
        FunctionOverload(listOf("double", "array(double)"), "array(double)"),
        FunctionOverload(listOf("double", "double"), "double"),
        FunctionOverload(listOf("double", "double", "array(double)"), "array(double)"),
        FunctionOverload(listOf("double", "double", "double"), "double"),
        FunctionOverload(listOf("double", "double", "double", "double"), "double"),
        FunctionOverload(listOf("real", "array(double)"), "array(real)"),
        FunctionOverload(listOf("real", "double"), "real"),
        FunctionOverload(listOf("real", "double", "array(double)"), "array(real)"),
        FunctionOverload(listOf("real", "double", "double"), "real"),
        FunctionOverload(listOf("real", "double", "double", "double"), "real"),
    )),
    FunctionDef("approx_set", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "hyperloglog"),
        FunctionOverload(listOf("double"), "hyperloglog"),
        FunctionOverload(listOf("varchar(x)"), "hyperloglog"),
    )),
    FunctionDef("arbitrary", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("t"), "t"),
    )),
    FunctionDef("array_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("t"), "array(t)"),
    )),
    FunctionDef("avg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("decimal(p,s)"), "decimal(p,s)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("interval day to second"), "interval day to second"),
        FunctionOverload(listOf("interval year to month"), "interval year to month"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("real"), "real"),
    )),
    FunctionDef("bitwise_and_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
    )),
    FunctionDef("bitwise_or_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
    )),
    FunctionDef("bitwise_xor_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
    )),
    FunctionDef("bool_and", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("boolean"), "boolean"),
    )),
    FunctionDef("bool_or", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("boolean"), "boolean"),
    )),
    FunctionDef("checksum", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("t"), "varbinary"),
    )),
    FunctionDef("corr", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
        FunctionOverload(listOf("real", "real"), "real"),
    )),
    FunctionDef("count", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf(), "bigint"),
        FunctionOverload(listOf("t"), "bigint"),
    )),
    FunctionDef("count_if", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("boolean"), "bigint"),
    )),
    FunctionDef("covar_pop", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
        FunctionOverload(listOf("real", "real"), "real"),
    )),
    FunctionDef("covar_samp", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
        FunctionOverload(listOf("real", "real"), "real"),
    )),
    FunctionDef("custom_sum", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
    )),
    FunctionDef("every", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("boolean"), "boolean"),
    )),
    FunctionDef("geometric_mean", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("real"), "real"),
    )),
    FunctionDef("histogram", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("t"), "map(t,bigint)"),
    )),
    FunctionDef("kurtosis", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("listagg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("varchar", "varchar", "boolean", "varchar", "boolean"), "varchar"),
    )),
    FunctionDef("make_set_digest", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("t"), "setdigest"),
    )),
    FunctionDef("map_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("k", "v"), "map(k,v)"),
    )),
    FunctionDef("map_union", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("map(k,v)"), "map(k,v)"),
    )),
    FunctionDef("max", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("e", "bigint"), "array(e)"),
        FunctionOverload(listOf("t"), "t"),
    )),
    FunctionDef("max_by", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("v", "k"), "v"),
        FunctionOverload(listOf("v", "k", "bigint"), "array(v)"),
    )),
    FunctionDef("merge", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("hyperloglog"), "hyperloglog"),
        FunctionOverload(listOf("qdigest(v)"), "qdigest(v)"),
        FunctionOverload(listOf("tdigest"), "tdigest"),
    )),
    FunctionDef("merge_set_digest", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("setdigest"), "setdigest"),
    )),
    FunctionDef("min", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("e", "bigint"), "array(e)"),
        FunctionOverload(listOf("t"), "t"),
    )),
    FunctionDef("min_by", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("v", "k"), "v"),
        FunctionOverload(listOf("v", "k", "bigint"), "array(v)"),
    )),
    FunctionDef("multimap_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("k", "v"), "map(k,array(v))"),
    )),
    FunctionDef("numeric_histogram", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint", "double"), "map(double,double)"),
        FunctionOverload(listOf("bigint", "double", "double"), "map(double,double)"),
        FunctionOverload(listOf("bigint", "real"), "map(real,real)"),
        FunctionOverload(listOf("bigint", "real", "double"), "map(real,real)"),
    )),
    FunctionDef("qdigest_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "qdigest(bigint)"),
        FunctionOverload(listOf("bigint", "bigint"), "qdigest(bigint)"),
        FunctionOverload(listOf("bigint", "bigint", "double"), "qdigest(bigint)"),
        FunctionOverload(listOf("double"), "qdigest(double)"),
        FunctionOverload(listOf("double", "bigint"), "qdigest(double)"),
        FunctionOverload(listOf("double", "bigint", "double"), "qdigest(double)"),
        FunctionOverload(listOf("real"), "qdigest(real)"),
        FunctionOverload(listOf("real", "bigint"), "qdigest(real)"),
        FunctionOverload(listOf("real", "bigint", "double"), "qdigest(real)"),
    )),
    FunctionDef("reduce_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("T", "S", "function(S,T,S)", "function(S,S,S)"), "S"),
    )),
    FunctionDef("regr_intercept", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
        FunctionOverload(listOf("real", "real"), "real"),
    )),
    FunctionDef("regr_slope", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("double", "double"), "double"),
        FunctionOverload(listOf("real", "real"), "real"),
    )),
    FunctionDef("skewness", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("stddev", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("stddev_pop", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("stddev_samp", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("sum", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
        FunctionOverload(listOf("decimal(p,s)"), "decimal(38,s)"),
        FunctionOverload(listOf("double"), "double"),
        FunctionOverload(listOf("interval day to second"), "interval day to second"),
        FunctionOverload(listOf("interval year to month"), "interval year to month"),
        FunctionOverload(listOf("number"), "number"),
        FunctionOverload(listOf("real"), "real"),
    )),
    FunctionDef("tdigest_agg", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("double"), "tdigest"),
        FunctionOverload(listOf("double", "double"), "tdigest"),
    )),
    FunctionDef("var_pop", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("var_samp", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
    )),
    FunctionDef("variance", FunctionKind.AGGREGATE, overloads = listOf(
        FunctionOverload(listOf("bigint"), "double"),
        FunctionOverload(listOf("double"), "double"),
    )),
    // window (12)
    FunctionDef("cume_dist", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf(), "double"),
    )),
    FunctionDef("custom_rank", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf(), "bigint"),
    )),
    FunctionDef("dense_rank", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf(), "bigint"),
    )),
    FunctionDef("first_value", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf("t"), "t"),
    )),
    FunctionDef("lag", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf("t"), "t"),
        FunctionOverload(listOf("t", "bigint"), "t"),
        FunctionOverload(listOf("t", "bigint", "t"), "t"),
    )),
    FunctionDef("last_value", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf("t"), "t"),
    )),
    FunctionDef("lead", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf("t"), "t"),
        FunctionOverload(listOf("t", "bigint"), "t"),
        FunctionOverload(listOf("t", "bigint", "t"), "t"),
    )),
    FunctionDef("nth_value", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf("t", "bigint"), "t"),
    )),
    FunctionDef("ntile", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf("bigint"), "bigint"),
    )),
    FunctionDef("percent_rank", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf(), "double"),
    )),
    FunctionDef("rank", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf(), "bigint"),
    )),
    FunctionDef("row_number", FunctionKind.WINDOW, overloads = listOf(
        FunctionOverload(listOf(), "bigint"),
    )),
    // table_valued (2)
    FunctionDef("exclude_columns", FunctionKind.TABLE_VALUED, overloads = listOf(
        FunctionOverload(listOf("unknown", "unknown"), "unknown"),
    )),
    FunctionDef("sequence", FunctionKind.TABLE_VALUED, overloads = listOf(
        FunctionOverload(listOf("bigint", "bigint", "bigint"), "unknown"),
    )),
)
