// GENERATED FILE — DO NOT EDIT.
// Generated by tools/generate_hazards_registry.py from
// brikk-sql/testResources/semantics/doris-starrocks-hazards.json (brikk behavior-matrix probe (tools/probe_behavior_matrix.py),
// extracted 20260830T073810Z): live-probe-verified doris<->starrocks semantics
// verdicts. Regenerate after editing the JSON; the run is byte-deterministic.
//
// Keying and collision policy: see the tool's docstring / HazardRegistry KDoc
// (raw side-name + bare-identifier alternatives; collisions keep the WORST
// verdict, ties keep JSON order).
package dev.brikk.house.sql.metadata

/** The 82 probe-verified (doris->starrocks) verdicts, in JSON order. */
internal val DORIS_TO_STARROCKS_HAZARD_ENTRIES: List<FunctionHazard> = dorisStarrocksChunk0() +
    dorisStarrocksChunk1() +
    dorisStarrocksChunk2()

private fun dorisStarrocksChunk0(): List<FunctionHazard> = listOf(
    // [0] doris: 'abs' | starrocks: 'abs'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#abs",
        sourceName = "abs",
        targetName = "abs"),
    // [1] doris: 'abs_min' | starrocks: 'abs_min'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#abs_min",
        sourceName = "abs_min",
        targetName = "abs_min"),
    // [2] doris: 'any_value' | starrocks: 'any_value'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#any_value",
        sourceName = "any_value",
        targetName = "any_value"),
    // [3] doris: 'array_avg' | starrocks: 'array_avg'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. array_avg([1, 2, 3]) -> starrocks=2.0 doris=2",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_avg",
        sourceName = "array_avg",
        targetName = "array_avg"),
    // [4] doris: 'array_contains' | starrocks: 'array_contains'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array", "null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_contains",
        sourceName = "array_contains",
        targetName = "array_contains"),
    // [5] doris: 'array_distinct' | starrocks: 'array_distinct'
    FunctionHazard(HazardVerdict.UNCLEAR,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_distinct",
        sourceName = "array_distinct",
        targetName = "array_distinct"),
    // [6] doris: 'array_empty' | starrocks: 'array_empty'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "0 diverging / 0 identical vectors; e.g. array_length([]) -> starrocks=0 doris=<ERR:ERROR 1105 (HY000) at line 1: errCode = 2, detailMessage = Can not found function 'array_length'>",
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_empty",
        sourceName = "array_empty",
        targetName = "array_empty"),
    // [7] doris: 'array_join' | starrocks: 'array_join'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_join",
        sourceName = "array_join",
        targetName = "array_join"),
    // [8] doris: 'array_length' | starrocks: 'array_length'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "0 diverging / 0 identical vectors; e.g. array_length([10, 20, 30]) -> starrocks=3 doris=<ERR:ERROR 1105 (HY000) at line 1: errCode = 2, detailMessage = Can not found function 'array_length'>",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_length",
        sourceName = "array_length",
        targetName = "array_length"),
    // [9] doris: 'array_max' | starrocks: 'array_max'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_max",
        sourceName = "array_max",
        targetName = "array_max"),
    // [10] doris: 'array_position' | starrocks: 'array_position'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_position",
        sourceName = "array_position",
        targetName = "array_position"),
    // [11] doris: 'array_slice' | starrocks: 'array_slice'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. array_slice([1, 2, 3, 4, 5], 2, 2) -> starrocks=[2,3] doris=[2, 3]",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_slice",
        sourceName = "array_slice",
        targetName = "array_slice"),
    // [12] doris: 'array_sort' | starrocks: 'array_sort'
    FunctionHazard(HazardVerdict.UNCLEAR,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_sort",
        sourceName = "array_sort",
        targetName = "array_sort"),
    // [13] doris: 'arrays_overlap' | starrocks: 'arrays_overlap'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#arrays_overlap",
        sourceName = "arrays_overlap",
        targetName = "arrays_overlap"),
    // [14] doris: 'ascii' | starrocks: 'ascii'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#ascii",
        sourceName = "ascii",
        targetName = "ascii"),
    // [15] doris: 'avg' | starrocks: 'avg'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#avg",
        sourceName = "avg",
        targetName = "avg"),
    // [16] doris: 'bin' | starrocks: 'bin'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#bin",
        sourceName = "bin",
        targetName = "bin"),
    // [17] doris: 'cast_overflow' | starrocks: 'cast_overflow'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#cast_overflow",
        sourceName = "cast_overflow",
        targetName = "cast_overflow"),
    // [18] doris: 'ceil' | starrocks: 'ceil'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#ceil",
        sourceName = "ceil",
        targetName = "ceil"),
    // [19] doris: 'char_length' | starrocks: 'char_length'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#char_length",
        sourceName = "char_length",
        targetName = "char_length"),
    // [20] doris: 'coalesce' | starrocks: 'coalesce'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#coalesce",
        sourceName = "coalesce",
        targetName = "coalesce"),
    // [21] doris: 'concat' | starrocks: 'concat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#concat",
        sourceName = "concat",
        targetName = "concat"),
    // [22] doris: 'concat_empty' | starrocks: 'concat_empty'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#concat_empty",
        sourceName = "concat_empty",
        targetName = "concat_empty"),
    // [23] doris: 'concat_num' | starrocks: 'concat_num'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#concat_num",
        sourceName = "concat_num",
        targetName = "concat_num"),
    // [24] doris: 'concat_ws' | starrocks: 'concat_ws'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#concat_ws",
        sourceName = "concat_ws",
        targetName = "concat_ws"),
    // [25] doris: 'count_distinct' | starrocks: 'count_distinct'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#count_distinct",
        sourceName = "count_distinct",
        targetName = "count_distinct"),
    // [26] doris: 'date_add' | starrocks: 'date_add'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. date_add('2024-01-31', INTERVAL 1 MONTH) -> starrocks=2024-02-29 00:00:00 doris=2024-02-29",
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#date_add",
        sourceName = "date_add",
        targetName = "date_add"),
    // [27] doris: 'date_format' | starrocks: 'date_format'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#date_format",
        sourceName = "date_format",
        targetName = "date_format"),
    // [28] doris: 'date_sub' | starrocks: 'date_sub'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. date_sub('2024-03-31', INTERVAL 1 MONTH) -> starrocks=2024-02-29 00:00:00 doris=2024-02-29",
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#date_sub",
        sourceName = "date_sub",
        targetName = "date_sub"),
    // [29] doris: 'date_trunc' | starrocks: 'date_trunc'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#date_trunc",
        sourceName = "date_trunc",
        targetName = "date_trunc"),
    // [30] doris: 'datediff' | starrocks: 'datediff'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#datediff",
        sourceName = "datediff",
        targetName = "datediff"),
    // [31] doris: 'day_of_week' | starrocks: 'day_of_week'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#day_of_week",
        sourceName = "day_of_week",
        targetName = "day_of_week"),
    // [32] doris: 'day_of_year' | starrocks: 'day_of_year'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#day_of_year",
        sourceName = "day_of_year",
        targetName = "day_of_year"),
    // [33] doris: 'divide_zero_float' | starrocks: 'divide_zero_float'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#divide_zero_float",
        sourceName = "divide_zero_float",
        targetName = "divide_zero_float"),
    // [34] doris: 'divide_zero_int' | starrocks: 'divide_zero_int'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#divide_zero_int",
        sourceName = "divide_zero_int",
        targetName = "divide_zero_int"),
    // [35] doris: 'element_at' | starrocks: 'element_at'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "1 diverging / 1 identical vectors; e.g. element_at([10, 20, 30], -1) -> starrocks=NULL doris=30",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#element_at",
        sourceName = "element_at",
        targetName = "element_at"),
    // [36] doris: 'floor' | starrocks: 'floor'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#floor",
        sourceName = "floor",
        targetName = "floor"),
    // [37] doris: 'from_unixtime' | starrocks: 'from_unixtime'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#from_unixtime",
        sourceName = "from_unixtime",
        targetName = "from_unixtime"),
    // [38] doris: 'get_json_string' | starrocks: 'get_json_string'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#get_json_string",
        sourceName = "get_json_string",
        targetName = "get_json_string"),
    // [39] doris: 'greatest' | starrocks: 'greatest'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#greatest",
        sourceName = "greatest",
        targetName = "greatest"),
)

private fun dorisStarrocksChunk1(): List<FunctionHazard> = listOf(
    // [40] doris: 'group_concat' | starrocks: 'group_concat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#group_concat",
        sourceName = "group_concat",
        targetName = "group_concat"),
    // [41] doris: 'hour' | starrocks: 'hour'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#hour",
        sourceName = "hour",
        targetName = "hour"),
    // [42] doris: 'if' | starrocks: 'if'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#if",
        sourceName = "if",
        targetName = "if"),
    // [43] doris: 'ifnull' | starrocks: 'ifnull'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#ifnull",
        sourceName = "ifnull",
        targetName = "ifnull"),
    // [44] doris: 'instr' | starrocks: 'instr'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#instr",
        sourceName = "instr",
        targetName = "instr"),
    // [45] doris: 'json_extract' | starrocks: 'json_extract'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "0 diverging / 0 identical vectors; e.g. json_extract('{\"a\": 1}', '\$.a') -> starrocks=<ERR:ERROR 1064 (HY000) at line 1: Getting analyzing error from line 1, column 7 to line 1, column 37. Detail message: No matching function with signature: json_extract(varchar, varchar).> doris=1",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#json_extract",
        sourceName = "json_extract",
        targetName = "json_extract"),
    // [46] doris: 'json_length' | starrocks: 'json_length'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#json_length",
        sourceName = "json_length",
        targetName = "json_length"),
    // [47] doris: 'last_day' | starrocks: 'last_day'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#last_day",
        sourceName = "last_day",
        targetName = "last_day"),
    // [48] doris: 'least' | starrocks: 'least'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#least",
        sourceName = "least",
        targetName = "least"),
    // [49] doris: 'left' | starrocks: 'left'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#left",
        sourceName = "left",
        targetName = "left"),
    // [50] doris: 'length' | starrocks: 'length'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null", "string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#length",
        sourceName = "length",
        targetName = "length"),
    // [51] doris: 'locate' | starrocks: 'locate'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#locate",
        sourceName = "locate",
        targetName = "locate"),
    // [52] doris: 'lower' | starrocks: 'lower'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#lower",
        sourceName = "lower",
        targetName = "lower"),
    // [53] doris: 'lpad' | starrocks: 'lpad'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#lpad",
        sourceName = "lpad",
        targetName = "lpad"),
    // [54] doris: 'ltrim' | starrocks: 'ltrim'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#ltrim",
        sourceName = "ltrim",
        targetName = "ltrim"),
    // [55] doris: 'min' | starrocks: 'min'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#min",
        sourceName = "min",
        targetName = "min"),
    // [56] doris: 'mod' | starrocks: 'mod'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#mod",
        sourceName = "mod",
        targetName = "mod"),
    // [57] doris: 'mod_zero' | starrocks: 'mod_zero'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#mod_zero",
        sourceName = "mod_zero",
        targetName = "mod_zero"),
    // [58] doris: 'months_add' | starrocks: 'months_add'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. months_add('2024-01-31', 1) -> starrocks=2024-02-29 00:00:00 doris=2024-02-29",
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#months_add",
        sourceName = "months_add",
        targetName = "months_add"),
    // [59] doris: 'nullif' | starrocks: 'nullif'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#nullif",
        sourceName = "nullif",
        targetName = "nullif"),
    // [60] doris: 'pmod' | starrocks: 'pmod'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#pmod",
        sourceName = "pmod",
        targetName = "pmod"),
    // [61] doris: 'pow' | starrocks: 'pow'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#pow",
        sourceName = "pow",
        targetName = "pow"),
    // [62] doris: 'power_big' | starrocks: 'power_big'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#power_big",
        sourceName = "power_big",
        targetName = "power_big"),
    // [63] doris: 'regexp_extract' | starrocks: 'regexp_extract'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("regex"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#regexp_extract",
        sourceName = "regexp_extract",
        targetName = "regexp_extract"),
    // [64] doris: 'regexp_replace' | starrocks: 'regexp_replace'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("regex"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#regexp_replace",
        sourceName = "regexp_replace",
        targetName = "regexp_replace"),
    // [65] doris: 'repeat' | starrocks: 'repeat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#repeat",
        sourceName = "repeat",
        targetName = "repeat"),
    // [66] doris: 'replace' | starrocks: 'replace'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#replace",
        sourceName = "replace",
        targetName = "replace"),
    // [67] doris: 'reverse' | starrocks: 'reverse'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#reverse",
        sourceName = "reverse",
        targetName = "reverse"),
    // [68] doris: 'right' | starrocks: 'right'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#right",
        sourceName = "right",
        targetName = "right"),
    // [69] doris: 'round' | starrocks: 'round'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#round",
        sourceName = "round",
        targetName = "round"),
    // [70] doris: 'rpad' | starrocks: 'rpad'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#rpad",
        sourceName = "rpad",
        targetName = "rpad"),
    // [71] doris: 'split_part' | starrocks: 'split_part'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#split_part",
        sourceName = "split_part",
        targetName = "split_part"),
    // [72] doris: 'stddev' | starrocks: 'stddev'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#stddev",
        sourceName = "stddev",
        targetName = "stddev"),
    // [73] doris: 'substring' | starrocks: 'substring'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#substring",
        sourceName = "substring",
        targetName = "substring"),
    // [74] doris: 'substring_oob' | starrocks: 'substring_oob'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#substring_oob",
        sourceName = "substring_oob",
        targetName = "substring_oob"),
    // [75] doris: 'sum' | starrocks: 'sum'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#sum",
        sourceName = "sum",
        targetName = "sum"),
    // [76] doris: 'to_date' | starrocks: 'to_date'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#to_date",
        sourceName = "to_date",
        targetName = "to_date"),
    // [77] doris: 'trim' | starrocks: 'trim'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#trim",
        sourceName = "trim",
        targetName = "trim"),
    // [78] doris: 'truncate' | starrocks: 'truncate'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#truncate",
        sourceName = "truncate",
        targetName = "truncate"),
    // [79] doris: 'unix_timestamp' | starrocks: 'unix_timestamp'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#unix_timestamp",
        sourceName = "unix_timestamp",
        targetName = "unix_timestamp"),
)

private fun dorisStarrocksChunk2(): List<FunctionHazard> = listOf(
    // [80] doris: 'upper' | starrocks: 'upper'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null", "string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#upper",
        sourceName = "upper",
        targetName = "upper"),
    // [81] doris: 'variance' | starrocks: 'variance'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#variance",
        sourceName = "variance",
        targetName = "variance"),
)


/** The 82 probe-verified (starrocks->doris) verdicts, in JSON order. */
internal val STARROCKS_TO_DORIS_HAZARD_ENTRIES: List<FunctionHazard> = starrocksDorisChunk0() +
    starrocksDorisChunk1() +
    starrocksDorisChunk2()

private fun starrocksDorisChunk0(): List<FunctionHazard> = listOf(
    // [0] doris: 'abs' | starrocks: 'abs'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#abs",
        sourceName = "abs",
        targetName = "abs"),
    // [1] doris: 'abs_min' | starrocks: 'abs_min'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#abs_min",
        sourceName = "abs_min",
        targetName = "abs_min"),
    // [2] doris: 'any_value' | starrocks: 'any_value'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#any_value",
        sourceName = "any_value",
        targetName = "any_value"),
    // [3] doris: 'array_avg' | starrocks: 'array_avg'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. array_avg([1, 2, 3]) -> starrocks=2.0 doris=2",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_avg",
        sourceName = "array_avg",
        targetName = "array_avg"),
    // [4] doris: 'array_contains' | starrocks: 'array_contains'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array", "null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_contains",
        sourceName = "array_contains",
        targetName = "array_contains"),
    // [5] doris: 'array_distinct' | starrocks: 'array_distinct'
    FunctionHazard(HazardVerdict.UNCLEAR,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_distinct",
        sourceName = "array_distinct",
        targetName = "array_distinct"),
    // [6] doris: 'array_empty' | starrocks: 'array_empty'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "0 diverging / 0 identical vectors; e.g. array_length([]) -> starrocks=0 doris=<ERR:ERROR 1105 (HY000) at line 1: errCode = 2, detailMessage = Can not found function 'array_length'>",
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_empty",
        sourceName = "array_empty",
        targetName = "array_empty"),
    // [7] doris: 'array_join' | starrocks: 'array_join'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_join",
        sourceName = "array_join",
        targetName = "array_join"),
    // [8] doris: 'array_length' | starrocks: 'array_length'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "0 diverging / 0 identical vectors; e.g. array_length([10, 20, 30]) -> starrocks=3 doris=<ERR:ERROR 1105 (HY000) at line 1: errCode = 2, detailMessage = Can not found function 'array_length'>",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_length",
        sourceName = "array_length",
        targetName = "array_length"),
    // [9] doris: 'array_max' | starrocks: 'array_max'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_max",
        sourceName = "array_max",
        targetName = "array_max"),
    // [10] doris: 'array_position' | starrocks: 'array_position'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_position",
        sourceName = "array_position",
        targetName = "array_position"),
    // [11] doris: 'array_slice' | starrocks: 'array_slice'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. array_slice([1, 2, 3, 4, 5], 2, 2) -> starrocks=[2,3] doris=[2, 3]",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_slice",
        sourceName = "array_slice",
        targetName = "array_slice"),
    // [12] doris: 'array_sort' | starrocks: 'array_sort'
    FunctionHazard(HazardVerdict.UNCLEAR,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#array_sort",
        sourceName = "array_sort",
        targetName = "array_sort"),
    // [13] doris: 'arrays_overlap' | starrocks: 'arrays_overlap'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#arrays_overlap",
        sourceName = "arrays_overlap",
        targetName = "arrays_overlap"),
    // [14] doris: 'ascii' | starrocks: 'ascii'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#ascii",
        sourceName = "ascii",
        targetName = "ascii"),
    // [15] doris: 'avg' | starrocks: 'avg'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#avg",
        sourceName = "avg",
        targetName = "avg"),
    // [16] doris: 'bin' | starrocks: 'bin'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#bin",
        sourceName = "bin",
        targetName = "bin"),
    // [17] doris: 'cast_overflow' | starrocks: 'cast_overflow'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#cast_overflow",
        sourceName = "cast_overflow",
        targetName = "cast_overflow"),
    // [18] doris: 'ceil' | starrocks: 'ceil'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#ceil",
        sourceName = "ceil",
        targetName = "ceil"),
    // [19] doris: 'char_length' | starrocks: 'char_length'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#char_length",
        sourceName = "char_length",
        targetName = "char_length"),
    // [20] doris: 'coalesce' | starrocks: 'coalesce'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#coalesce",
        sourceName = "coalesce",
        targetName = "coalesce"),
    // [21] doris: 'concat' | starrocks: 'concat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#concat",
        sourceName = "concat",
        targetName = "concat"),
    // [22] doris: 'concat_empty' | starrocks: 'concat_empty'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#concat_empty",
        sourceName = "concat_empty",
        targetName = "concat_empty"),
    // [23] doris: 'concat_num' | starrocks: 'concat_num'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#concat_num",
        sourceName = "concat_num",
        targetName = "concat_num"),
    // [24] doris: 'concat_ws' | starrocks: 'concat_ws'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#concat_ws",
        sourceName = "concat_ws",
        targetName = "concat_ws"),
    // [25] doris: 'count_distinct' | starrocks: 'count_distinct'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#count_distinct",
        sourceName = "count_distinct",
        targetName = "count_distinct"),
    // [26] doris: 'date_add' | starrocks: 'date_add'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. date_add('2024-01-31', INTERVAL 1 MONTH) -> starrocks=2024-02-29 00:00:00 doris=2024-02-29",
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#date_add",
        sourceName = "date_add",
        targetName = "date_add"),
    // [27] doris: 'date_format' | starrocks: 'date_format'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#date_format",
        sourceName = "date_format",
        targetName = "date_format"),
    // [28] doris: 'date_sub' | starrocks: 'date_sub'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. date_sub('2024-03-31', INTERVAL 1 MONTH) -> starrocks=2024-02-29 00:00:00 doris=2024-02-29",
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#date_sub",
        sourceName = "date_sub",
        targetName = "date_sub"),
    // [29] doris: 'date_trunc' | starrocks: 'date_trunc'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#date_trunc",
        sourceName = "date_trunc",
        targetName = "date_trunc"),
    // [30] doris: 'datediff' | starrocks: 'datediff'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#datediff",
        sourceName = "datediff",
        targetName = "datediff"),
    // [31] doris: 'day_of_week' | starrocks: 'day_of_week'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#day_of_week",
        sourceName = "day_of_week",
        targetName = "day_of_week"),
    // [32] doris: 'day_of_year' | starrocks: 'day_of_year'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#day_of_year",
        sourceName = "day_of_year",
        targetName = "day_of_year"),
    // [33] doris: 'divide_zero_float' | starrocks: 'divide_zero_float'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#divide_zero_float",
        sourceName = "divide_zero_float",
        targetName = "divide_zero_float"),
    // [34] doris: 'divide_zero_int' | starrocks: 'divide_zero_int'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#divide_zero_int",
        sourceName = "divide_zero_int",
        targetName = "divide_zero_int"),
    // [35] doris: 'element_at' | starrocks: 'element_at'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "1 diverging / 1 identical vectors; e.g. element_at([10, 20, 30], -1) -> starrocks=NULL doris=30",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#element_at",
        sourceName = "element_at",
        targetName = "element_at"),
    // [36] doris: 'floor' | starrocks: 'floor'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#floor",
        sourceName = "floor",
        targetName = "floor"),
    // [37] doris: 'from_unixtime' | starrocks: 'from_unixtime'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#from_unixtime",
        sourceName = "from_unixtime",
        targetName = "from_unixtime"),
    // [38] doris: 'get_json_string' | starrocks: 'get_json_string'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#get_json_string",
        sourceName = "get_json_string",
        targetName = "get_json_string"),
    // [39] doris: 'greatest' | starrocks: 'greatest'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#greatest",
        sourceName = "greatest",
        targetName = "greatest"),
)

private fun starrocksDorisChunk1(): List<FunctionHazard> = listOf(
    // [40] doris: 'group_concat' | starrocks: 'group_concat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#group_concat",
        sourceName = "group_concat",
        targetName = "group_concat"),
    // [41] doris: 'hour' | starrocks: 'hour'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#hour",
        sourceName = "hour",
        targetName = "hour"),
    // [42] doris: 'if' | starrocks: 'if'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#if",
        sourceName = "if",
        targetName = "if"),
    // [43] doris: 'ifnull' | starrocks: 'ifnull'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#ifnull",
        sourceName = "ifnull",
        targetName = "ifnull"),
    // [44] doris: 'instr' | starrocks: 'instr'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#instr",
        sourceName = "instr",
        targetName = "instr"),
    // [45] doris: 'json_extract' | starrocks: 'json_extract'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "0 diverging / 0 identical vectors; e.g. json_extract('{\"a\": 1}', '\$.a') -> starrocks=<ERR:ERROR 1064 (HY000) at line 1: Getting analyzing error from line 1, column 7 to line 1, column 37. Detail message: No matching function with signature: json_extract(varchar, varchar).> doris=1",
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#json_extract",
        sourceName = "json_extract",
        targetName = "json_extract"),
    // [46] doris: 'json_length' | starrocks: 'json_length'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("array"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#json_length",
        sourceName = "json_length",
        targetName = "json_length"),
    // [47] doris: 'last_day' | starrocks: 'last_day'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#last_day",
        sourceName = "last_day",
        targetName = "last_day"),
    // [48] doris: 'least' | starrocks: 'least'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#least",
        sourceName = "least",
        targetName = "least"),
    // [49] doris: 'left' | starrocks: 'left'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#left",
        sourceName = "left",
        targetName = "left"),
    // [50] doris: 'length' | starrocks: 'length'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null", "string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#length",
        sourceName = "length",
        targetName = "length"),
    // [51] doris: 'locate' | starrocks: 'locate'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#locate",
        sourceName = "locate",
        targetName = "locate"),
    // [52] doris: 'lower' | starrocks: 'lower'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#lower",
        sourceName = "lower",
        targetName = "lower"),
    // [53] doris: 'lpad' | starrocks: 'lpad'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#lpad",
        sourceName = "lpad",
        targetName = "lpad"),
    // [54] doris: 'ltrim' | starrocks: 'ltrim'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#ltrim",
        sourceName = "ltrim",
        targetName = "ltrim"),
    // [55] doris: 'min' | starrocks: 'min'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#min",
        sourceName = "min",
        targetName = "min"),
    // [56] doris: 'mod' | starrocks: 'mod'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#mod",
        sourceName = "mod",
        targetName = "mod"),
    // [57] doris: 'mod_zero' | starrocks: 'mod_zero'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#mod_zero",
        sourceName = "mod_zero",
        targetName = "mod_zero"),
    // [58] doris: 'months_add' | starrocks: 'months_add'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "1 diverging / 0 identical vectors; e.g. months_add('2024-01-31', 1) -> starrocks=2024-02-29 00:00:00 doris=2024-02-29",
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#months_add",
        sourceName = "months_add",
        targetName = "months_add"),
    // [59] doris: 'nullif' | starrocks: 'nullif'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#nullif",
        sourceName = "nullif",
        targetName = "nullif"),
    // [60] doris: 'pmod' | starrocks: 'pmod'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#pmod",
        sourceName = "pmod",
        targetName = "pmod"),
    // [61] doris: 'pow' | starrocks: 'pow'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#pow",
        sourceName = "pow",
        targetName = "pow"),
    // [62] doris: 'power_big' | starrocks: 'power_big'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#power_big",
        sourceName = "power_big",
        targetName = "power_big"),
    // [63] doris: 'regexp_extract' | starrocks: 'regexp_extract'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("regex"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#regexp_extract",
        sourceName = "regexp_extract",
        targetName = "regexp_extract"),
    // [64] doris: 'regexp_replace' | starrocks: 'regexp_replace'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("regex"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#regexp_replace",
        sourceName = "regexp_replace",
        targetName = "regexp_replace"),
    // [65] doris: 'repeat' | starrocks: 'repeat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#repeat",
        sourceName = "repeat",
        targetName = "repeat"),
    // [66] doris: 'replace' | starrocks: 'replace'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#replace",
        sourceName = "replace",
        targetName = "replace"),
    // [67] doris: 'reverse' | starrocks: 'reverse'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#reverse",
        sourceName = "reverse",
        targetName = "reverse"),
    // [68] doris: 'right' | starrocks: 'right'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#right",
        sourceName = "right",
        targetName = "right"),
    // [69] doris: 'round' | starrocks: 'round'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#round",
        sourceName = "round",
        targetName = "round"),
    // [70] doris: 'rpad' | starrocks: 'rpad'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#rpad",
        sourceName = "rpad",
        targetName = "rpad"),
    // [71] doris: 'split_part' | starrocks: 'split_part'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#split_part",
        sourceName = "split_part",
        targetName = "split_part"),
    // [72] doris: 'stddev' | starrocks: 'stddev'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#stddev",
        sourceName = "stddev",
        targetName = "stddev"),
    // [73] doris: 'substring' | starrocks: 'substring'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#substring",
        sourceName = "substring",
        targetName = "substring"),
    // [74] doris: 'substring_oob' | starrocks: 'substring_oob'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("boundary"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#substring_oob",
        sourceName = "substring_oob",
        targetName = "substring_oob"),
    // [75] doris: 'sum' | starrocks: 'sum'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#sum",
        sourceName = "sum",
        targetName = "sum"),
    // [76] doris: 'to_date' | starrocks: 'to_date'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#to_date",
        sourceName = "to_date",
        targetName = "to_date"),
    // [77] doris: 'trim' | starrocks: 'trim'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#trim",
        sourceName = "trim",
        targetName = "trim"),
    // [78] doris: 'truncate' | starrocks: 'truncate'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("rounding"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#truncate",
        sourceName = "truncate",
        targetName = "truncate"),
    // [79] doris: 'unix_timestamp' | starrocks: 'unix_timestamp'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("datetime"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#unix_timestamp",
        sourceName = "unix_timestamp",
        targetName = "unix_timestamp"),
)

private fun starrocksDorisChunk2(): List<FunctionHazard> = listOf(
    // [80] doris: 'upper' | starrocks: 'upper'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null", "string"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#upper",
        sourceName = "upper",
        targetName = "upper"),
    // [81] doris: 'variance' | starrocks: 'variance'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("agg"),
        provenance = "probe-runs/20260830T073810Z-starrocks-doris.tsv#variance",
        sourceName = "variance",
        targetName = "variance"),
)


/** doris->starrocks lookup: 82 keys (Doris-side names) over 82 entries. */
internal val DORIS_TO_STARROCKS_HAZARDS: Map<String, FunctionHazard> = buildMap {
    put("ABS", DORIS_TO_STARROCKS_HAZARD_ENTRIES[0])
    put("ABS_MIN", DORIS_TO_STARROCKS_HAZARD_ENTRIES[1])
    put("ANY_VALUE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[2])
    put("ARRAYS_OVERLAP", DORIS_TO_STARROCKS_HAZARD_ENTRIES[13])
    put("ARRAY_AVG", DORIS_TO_STARROCKS_HAZARD_ENTRIES[3])
    put("ARRAY_CONTAINS", DORIS_TO_STARROCKS_HAZARD_ENTRIES[4])
    put("ARRAY_DISTINCT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[5])
    put("ARRAY_EMPTY", DORIS_TO_STARROCKS_HAZARD_ENTRIES[6])
    put("ARRAY_JOIN", DORIS_TO_STARROCKS_HAZARD_ENTRIES[7])
    put("ARRAY_LENGTH", DORIS_TO_STARROCKS_HAZARD_ENTRIES[8])
    put("ARRAY_MAX", DORIS_TO_STARROCKS_HAZARD_ENTRIES[9])
    put("ARRAY_POSITION", DORIS_TO_STARROCKS_HAZARD_ENTRIES[10])
    put("ARRAY_SLICE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[11])
    put("ARRAY_SORT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[12])
    put("ASCII", DORIS_TO_STARROCKS_HAZARD_ENTRIES[14])
    put("AVG", DORIS_TO_STARROCKS_HAZARD_ENTRIES[15])
    put("BIN", DORIS_TO_STARROCKS_HAZARD_ENTRIES[16])
    put("CAST_OVERFLOW", DORIS_TO_STARROCKS_HAZARD_ENTRIES[17])
    put("CEIL", DORIS_TO_STARROCKS_HAZARD_ENTRIES[18])
    put("CHAR_LENGTH", DORIS_TO_STARROCKS_HAZARD_ENTRIES[19])
    put("COALESCE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[20])
    put("CONCAT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[21])
    put("CONCAT_EMPTY", DORIS_TO_STARROCKS_HAZARD_ENTRIES[22])
    put("CONCAT_NUM", DORIS_TO_STARROCKS_HAZARD_ENTRIES[23])
    put("CONCAT_WS", DORIS_TO_STARROCKS_HAZARD_ENTRIES[24])
    put("COUNT_DISTINCT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[25])
    put("DATEDIFF", DORIS_TO_STARROCKS_HAZARD_ENTRIES[30])
    put("DATE_ADD", DORIS_TO_STARROCKS_HAZARD_ENTRIES[26])
    put("DATE_FORMAT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[27])
    put("DATE_SUB", DORIS_TO_STARROCKS_HAZARD_ENTRIES[28])
    put("DATE_TRUNC", DORIS_TO_STARROCKS_HAZARD_ENTRIES[29])
    put("DAY_OF_WEEK", DORIS_TO_STARROCKS_HAZARD_ENTRIES[31])
    put("DAY_OF_YEAR", DORIS_TO_STARROCKS_HAZARD_ENTRIES[32])
    put("DIVIDE_ZERO_FLOAT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[33])
    put("DIVIDE_ZERO_INT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[34])
    put("ELEMENT_AT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[35])
    put("FLOOR", DORIS_TO_STARROCKS_HAZARD_ENTRIES[36])
    put("FROM_UNIXTIME", DORIS_TO_STARROCKS_HAZARD_ENTRIES[37])
    put("GET_JSON_STRING", DORIS_TO_STARROCKS_HAZARD_ENTRIES[38])
    put("GREATEST", DORIS_TO_STARROCKS_HAZARD_ENTRIES[39])
    put("GROUP_CONCAT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[40])
    put("HOUR", DORIS_TO_STARROCKS_HAZARD_ENTRIES[41])
    put("IF", DORIS_TO_STARROCKS_HAZARD_ENTRIES[42])
    put("IFNULL", DORIS_TO_STARROCKS_HAZARD_ENTRIES[43])
    put("INSTR", DORIS_TO_STARROCKS_HAZARD_ENTRIES[44])
    put("JSON_EXTRACT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[45])
    put("JSON_LENGTH", DORIS_TO_STARROCKS_HAZARD_ENTRIES[46])
    put("LAST_DAY", DORIS_TO_STARROCKS_HAZARD_ENTRIES[47])
    put("LEAST", DORIS_TO_STARROCKS_HAZARD_ENTRIES[48])
    put("LEFT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[49])
    put("LENGTH", DORIS_TO_STARROCKS_HAZARD_ENTRIES[50])
    put("LOCATE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[51])
    put("LOWER", DORIS_TO_STARROCKS_HAZARD_ENTRIES[52])
    put("LPAD", DORIS_TO_STARROCKS_HAZARD_ENTRIES[53])
    put("LTRIM", DORIS_TO_STARROCKS_HAZARD_ENTRIES[54])
    put("MIN", DORIS_TO_STARROCKS_HAZARD_ENTRIES[55])
    put("MOD", DORIS_TO_STARROCKS_HAZARD_ENTRIES[56])
    put("MOD_ZERO", DORIS_TO_STARROCKS_HAZARD_ENTRIES[57])
    put("MONTHS_ADD", DORIS_TO_STARROCKS_HAZARD_ENTRIES[58])
    put("NULLIF", DORIS_TO_STARROCKS_HAZARD_ENTRIES[59])
    put("PMOD", DORIS_TO_STARROCKS_HAZARD_ENTRIES[60])
    put("POW", DORIS_TO_STARROCKS_HAZARD_ENTRIES[61])
    put("POWER_BIG", DORIS_TO_STARROCKS_HAZARD_ENTRIES[62])
    put("REGEXP_EXTRACT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[63])
    put("REGEXP_REPLACE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[64])
    put("REPEAT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[65])
    put("REPLACE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[66])
    put("REVERSE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[67])
    put("RIGHT", DORIS_TO_STARROCKS_HAZARD_ENTRIES[68])
    put("ROUND", DORIS_TO_STARROCKS_HAZARD_ENTRIES[69])
    put("RPAD", DORIS_TO_STARROCKS_HAZARD_ENTRIES[70])
    put("SPLIT_PART", DORIS_TO_STARROCKS_HAZARD_ENTRIES[71])
    put("STDDEV", DORIS_TO_STARROCKS_HAZARD_ENTRIES[72])
    put("SUBSTRING", DORIS_TO_STARROCKS_HAZARD_ENTRIES[73])
    put("SUBSTRING_OOB", DORIS_TO_STARROCKS_HAZARD_ENTRIES[74])
    put("SUM", DORIS_TO_STARROCKS_HAZARD_ENTRIES[75])
    put("TO_DATE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[76])
    put("TRIM", DORIS_TO_STARROCKS_HAZARD_ENTRIES[77])
    put("TRUNCATE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[78])
    put("UNIX_TIMESTAMP", DORIS_TO_STARROCKS_HAZARD_ENTRIES[79])
    put("UPPER", DORIS_TO_STARROCKS_HAZARD_ENTRIES[80])
    put("VARIANCE", DORIS_TO_STARROCKS_HAZARD_ENTRIES[81])
}

/** starrocks->doris lookup: 82 keys (StarRocks-side names) over 82 entries. */
internal val STARROCKS_TO_DORIS_HAZARDS: Map<String, FunctionHazard> = buildMap {
    put("ABS", STARROCKS_TO_DORIS_HAZARD_ENTRIES[0])
    put("ABS_MIN", STARROCKS_TO_DORIS_HAZARD_ENTRIES[1])
    put("ANY_VALUE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[2])
    put("ARRAYS_OVERLAP", STARROCKS_TO_DORIS_HAZARD_ENTRIES[13])
    put("ARRAY_AVG", STARROCKS_TO_DORIS_HAZARD_ENTRIES[3])
    put("ARRAY_CONTAINS", STARROCKS_TO_DORIS_HAZARD_ENTRIES[4])
    put("ARRAY_DISTINCT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[5])
    put("ARRAY_EMPTY", STARROCKS_TO_DORIS_HAZARD_ENTRIES[6])
    put("ARRAY_JOIN", STARROCKS_TO_DORIS_HAZARD_ENTRIES[7])
    put("ARRAY_LENGTH", STARROCKS_TO_DORIS_HAZARD_ENTRIES[8])
    put("ARRAY_MAX", STARROCKS_TO_DORIS_HAZARD_ENTRIES[9])
    put("ARRAY_POSITION", STARROCKS_TO_DORIS_HAZARD_ENTRIES[10])
    put("ARRAY_SLICE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[11])
    put("ARRAY_SORT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[12])
    put("ASCII", STARROCKS_TO_DORIS_HAZARD_ENTRIES[14])
    put("AVG", STARROCKS_TO_DORIS_HAZARD_ENTRIES[15])
    put("BIN", STARROCKS_TO_DORIS_HAZARD_ENTRIES[16])
    put("CAST_OVERFLOW", STARROCKS_TO_DORIS_HAZARD_ENTRIES[17])
    put("CEIL", STARROCKS_TO_DORIS_HAZARD_ENTRIES[18])
    put("CHAR_LENGTH", STARROCKS_TO_DORIS_HAZARD_ENTRIES[19])
    put("COALESCE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[20])
    put("CONCAT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[21])
    put("CONCAT_EMPTY", STARROCKS_TO_DORIS_HAZARD_ENTRIES[22])
    put("CONCAT_NUM", STARROCKS_TO_DORIS_HAZARD_ENTRIES[23])
    put("CONCAT_WS", STARROCKS_TO_DORIS_HAZARD_ENTRIES[24])
    put("COUNT_DISTINCT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[25])
    put("DATEDIFF", STARROCKS_TO_DORIS_HAZARD_ENTRIES[30])
    put("DATE_ADD", STARROCKS_TO_DORIS_HAZARD_ENTRIES[26])
    put("DATE_FORMAT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[27])
    put("DATE_SUB", STARROCKS_TO_DORIS_HAZARD_ENTRIES[28])
    put("DATE_TRUNC", STARROCKS_TO_DORIS_HAZARD_ENTRIES[29])
    put("DAY_OF_WEEK", STARROCKS_TO_DORIS_HAZARD_ENTRIES[31])
    put("DAY_OF_YEAR", STARROCKS_TO_DORIS_HAZARD_ENTRIES[32])
    put("DIVIDE_ZERO_FLOAT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[33])
    put("DIVIDE_ZERO_INT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[34])
    put("ELEMENT_AT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[35])
    put("FLOOR", STARROCKS_TO_DORIS_HAZARD_ENTRIES[36])
    put("FROM_UNIXTIME", STARROCKS_TO_DORIS_HAZARD_ENTRIES[37])
    put("GET_JSON_STRING", STARROCKS_TO_DORIS_HAZARD_ENTRIES[38])
    put("GREATEST", STARROCKS_TO_DORIS_HAZARD_ENTRIES[39])
    put("GROUP_CONCAT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[40])
    put("HOUR", STARROCKS_TO_DORIS_HAZARD_ENTRIES[41])
    put("IF", STARROCKS_TO_DORIS_HAZARD_ENTRIES[42])
    put("IFNULL", STARROCKS_TO_DORIS_HAZARD_ENTRIES[43])
    put("INSTR", STARROCKS_TO_DORIS_HAZARD_ENTRIES[44])
    put("JSON_EXTRACT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[45])
    put("JSON_LENGTH", STARROCKS_TO_DORIS_HAZARD_ENTRIES[46])
    put("LAST_DAY", STARROCKS_TO_DORIS_HAZARD_ENTRIES[47])
    put("LEAST", STARROCKS_TO_DORIS_HAZARD_ENTRIES[48])
    put("LEFT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[49])
    put("LENGTH", STARROCKS_TO_DORIS_HAZARD_ENTRIES[50])
    put("LOCATE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[51])
    put("LOWER", STARROCKS_TO_DORIS_HAZARD_ENTRIES[52])
    put("LPAD", STARROCKS_TO_DORIS_HAZARD_ENTRIES[53])
    put("LTRIM", STARROCKS_TO_DORIS_HAZARD_ENTRIES[54])
    put("MIN", STARROCKS_TO_DORIS_HAZARD_ENTRIES[55])
    put("MOD", STARROCKS_TO_DORIS_HAZARD_ENTRIES[56])
    put("MOD_ZERO", STARROCKS_TO_DORIS_HAZARD_ENTRIES[57])
    put("MONTHS_ADD", STARROCKS_TO_DORIS_HAZARD_ENTRIES[58])
    put("NULLIF", STARROCKS_TO_DORIS_HAZARD_ENTRIES[59])
    put("PMOD", STARROCKS_TO_DORIS_HAZARD_ENTRIES[60])
    put("POW", STARROCKS_TO_DORIS_HAZARD_ENTRIES[61])
    put("POWER_BIG", STARROCKS_TO_DORIS_HAZARD_ENTRIES[62])
    put("REGEXP_EXTRACT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[63])
    put("REGEXP_REPLACE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[64])
    put("REPEAT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[65])
    put("REPLACE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[66])
    put("REVERSE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[67])
    put("RIGHT", STARROCKS_TO_DORIS_HAZARD_ENTRIES[68])
    put("ROUND", STARROCKS_TO_DORIS_HAZARD_ENTRIES[69])
    put("RPAD", STARROCKS_TO_DORIS_HAZARD_ENTRIES[70])
    put("SPLIT_PART", STARROCKS_TO_DORIS_HAZARD_ENTRIES[71])
    put("STDDEV", STARROCKS_TO_DORIS_HAZARD_ENTRIES[72])
    put("SUBSTRING", STARROCKS_TO_DORIS_HAZARD_ENTRIES[73])
    put("SUBSTRING_OOB", STARROCKS_TO_DORIS_HAZARD_ENTRIES[74])
    put("SUM", STARROCKS_TO_DORIS_HAZARD_ENTRIES[75])
    put("TO_DATE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[76])
    put("TRIM", STARROCKS_TO_DORIS_HAZARD_ENTRIES[77])
    put("TRUNCATE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[78])
    put("UNIX_TIMESTAMP", STARROCKS_TO_DORIS_HAZARD_ENTRIES[79])
    put("UPPER", STARROCKS_TO_DORIS_HAZARD_ENTRIES[80])
    put("VARIANCE", STARROCKS_TO_DORIS_HAZARD_ENTRIES[81])
}
