// GENERATED FILE — DO NOT EDIT.
// Generated by tools/generate_hazards_registry.py from
// brikk-sql/testResources/semantics/trino-doris-hazards.json (brikk live-probe program,
// extracted 2026-07-13): live-probe-verified trino<->doris semantics
// verdicts. Regenerate after editing the JSON; the run is byte-deterministic.
//
// Keying and collision policy: see the tool's docstring / HazardRegistry KDoc
// (raw side-name + bare-identifier alternatives; collisions keep the WORST
// verdict, ties keep JSON order).
package dev.brikk.house.sql.metadata

/** The 166 probe-verified (trino, doris) pair verdicts, in JSON order. */
internal val TRINO_DORIS_HAZARD_ENTRIES: List<FunctionHazard> = hazardsChunk0() +
    hazardsChunk1() +
    hazardsChunk2() +
    hazardsChunk3() +
    hazardsChunk4()

private fun hazardsChunk0(): List<FunctionHazard> = listOf(
    // [0] trino: 'lower' | doris: 'lower'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#lower"),
    // [1] trino: 'upper' | doris: 'upper'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#upper"),
    // [2] trino: 'concat' | doris: 'concat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both propagate NULL (Doris live-probed = NULL; Trino prior = NULL). Safe re NULL, unlike DuckDB.",
        areas = listOf("string", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#concat"),
    // [3] trino: 'greatest' | doris: 'greatest'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both return NULL if any arg is NULL (Doris live-probed; Trino prior).",
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#greatest-least"),
    // [4] trino: 'least' | doris: 'least'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both return NULL if any arg is NULL (Doris live-probed; Trino prior).",
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#greatest-least"),
    // [5] trino: 'split_part' | doris: 'split_part'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Out-of-bounds index -> NULL on both (Doris live-probed; Trino prior).",
        areas = listOf("string", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#split-part"),
    // [6] trino: 'reverse' | doris: 'reverse'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both reverse by code point (Doris live-probed; Trino prior code-point-only). DuckDB is the grapheme-aware outlier.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#reverse"),
    // [7] trino: 'regexp_replace' | doris: 'regexp_replace'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Both replace ALL matches by default (Doris live-probed; Trino prior).",
        areas = listOf("regex"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#regexp-replace"),
    // [8] trino: 'ascii' | doris: 'ascii'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris ascii is byte-oriented (ascii('É')=195, first UTF-8 byte); Trino codepoint (requires varchar(1)). Doris diverges from BOTH Trino and DuckDB. Trino side from prior evidence, not re-run live — confirm with live Trino.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#ascii"),
    // [9] trino: 'trim' | doris: 'trim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris strips ASCII space only; Trino (Java isWhitespace) strips tab/LF/CR/FF/VT. Different whitespace sets. Doris live; Trino prior.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [10] trino: 'ltrim' | doris: 'ltrim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris ASCII-space-only vs Trino Java-whitespace. Doris live; Trino prior.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [11] trino: 'rtrim' | doris: 'rtrim'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris ASCII-space-only vs Trino Java-whitespace. Doris live; Trino prior.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [12] trino: 'bit_count' | doris: 'bit_count'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Trino requires explicit bit-width arg; Doris infers. Doris live; Trino prior.",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [13] trino: 'fmod' | doris: 'fmod'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Trino float % uses IEEE-remainder-ish; Doris differs. Doris live; Trino prior.",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [14] trino: 'regexp_extract_all' | doris: 'regexp_extract_all'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Empty-match/array handling differs. Doris live; Trino prior.",
        areas = listOf("regex"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [15] trino: 'length' | doris: 'length'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris length()=bytes; Trino length()=characters. Doris live; Trino prior (char-based).",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [16] trino: 'abs' | doris: 'abs'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [17] trino: 'mod' | doris: 'mod'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [18] trino: 'coalesce' | doris: 'coalesce'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [19] trino: 'nullif' | doris: 'nullif'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [20] trino: 'md5' | doris: 'md5'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("hash"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch2"),
    // [21] trino: 'acos' | doris: 'acos'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Out-of-domain acos(2): Doris returns NULL; Trino (JVM Math) returns NaN. In-domain agrees. Doris live; Trino from prior evidence + JVM domain semantics.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [22] trino: 'asin' | doris: 'asin'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Out-of-domain asin(2): Doris returns NULL; Trino returns NaN. Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [23] trino: 'ln' | doris: 'ln'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "ln(0)/ln(-1): Doris returns NULL; Trino returns NaN (prior evidence 'NaN on x<=0'). In-domain agrees to last-ULP. Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [24] trino: 'sqrt' | doris: 'sqrt'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "sqrt(-1): Doris returns NULL; Trino returns NaN (prior evidence 'NaN on negative'). Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [25] trino: 'log2' | doris: 'log2'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "log2(0): Doris returns NULL; Trino returns NaN/domain (prior). In-domain agrees. Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [26] trino: 'log10' | doris: 'log10'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "log10(-1): Doris returns NULL; Trino returns NaN (prior). In-domain also differs by last-ULP (log10(3)). Doris live; Trino from prior evidence.",
        areas = listOf("numeric", "domain"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [27] trino: 'log' | doris: 'log'
    FunctionHazard(HazardVerdict.UNCLEAR,
        hazard = "Doris single-arg log(x) = natural log (log(10)=2.302585), not log10; two-arg log(b,x) agrees to last-ULP. Trino single-arg log semantics not re-probed this session — verify before mapping. Doris live.",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [28] trino: 'exp' | doris: 'exp'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "In-domain agrees to ~15 sig digits but last-ULP differs (exp(0.5): DuckDB/Trino 1.6487212707001282 vs Doris 1.648721270700128). Safe under float-tolerant comparison. Doris live; Trino via live-DuckDB bridge (prior identical).",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [29] trino: 'cbrt' | doris: 'cbrt'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP differs (cbrt(27): DuckDB/Trino 3.0000000000000004 vs Doris 3.0). Safe under float-tolerant comparison. Doris live; Trino via live-DuckDB bridge (prior identical).",
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [30] trino: 'atan' | doris: 'atan'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [31] trino: 'atan2' | doris: 'atan2'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [32] trino: 'cos' | doris: 'cos'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [33] trino: 'cosh' | doris: 'cosh'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [34] trino: 'sin' | doris: 'sin'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [35] trino: 'sinh' | doris: 'sinh'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [36] trino: 'tan' | doris: 'tan'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [37] trino: 'tanh' | doris: 'tanh'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [38] trino: 'ceil' | doris: 'ceil'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [39] trino: 'ceiling' | doris: 'ceiling'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
)

private fun hazardsChunk1(): List<FunctionHazard> = listOf(
    // [40] trino: 'floor' | doris: 'floor'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [41] trino: 'degrees' | doris: 'degrees'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [42] trino: 'radians' | doris: 'radians'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [43] trino: 'pi' | doris: 'pi'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [44] trino: 'sign' | doris: 'sign'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [45] trino: 'pow' | doris: 'pow'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [46] trino: 'power' | doris: 'power'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch3-numeric"),
    // [47] trino: 'to_hex' | doris: 'hex'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris to_hex() returns NULL (to_hex(255)=NULL, to_hex('abc')=NULL); the working hex encoder is Doris hex(). Map Trino to_hex -> Doris hex(), never by name. Doris live.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [48] trino: 'from_hex' | doris: 'unhex'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris from_hex('616263') does NOT hex-decode (returns '363136323633'); the correct hex decoder is Doris unhex('616263')='abc' (matches Trino from_hex). Map Trino from_hex -> Doris unhex, never by name. Doris live.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [49] trino: 'format_number' | doris: 'format_number'
    FunctionHazard(HazardVerdict.NO_EQUIVALENT,
        hazard = "Doris has no format_number function ('Can not found function format_number'). Doris live.",
        areas = listOf("string", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [50] trino: 'url_encode' | doris: 'url_encode'
    FunctionHazard(HazardVerdict.UNCLEAR,
        hazard = "Doris url_encode('a b&c')='a+b%26c' (space -> '+'). Trino url_encode space-handling not re-probed this session (prior trino==duckdb 'identical' verdict did not test space; DuckDB uses %20) — verify Trino before mapping. Doris live.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [51] trino: 'starts_with' | doris: 'starts_with'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Value semantics identical but Doris returns TINYINT 0/1 vs Trino BOOLEAN — boolean type mapping required (Doris renders BOOLEAN as 0/1 over MySQL protocol).",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [52] trino: 'sha1' | doris: 'sha1'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris sha1('abc') returns hex VARCHAR (matches DuckDB digest); Trino sha1 returns VARBINARY — unhex() wrap required for parity (same pattern as md5).",
        areas = listOf("hash", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [53] trino: 'replace' | doris: 'replace'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "3-arg replace aligned; Trino 2-arg remove form replace(s,search) maps by passing '' as replacement. Doris live.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [54] trino: 'levenshtein_distance' | doris: 'levenshtein'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris has no levenshtein_distance; use Doris levenshtein (levenshtein('kitten','sitting')=3, matches). Rename only.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [55] trino: 'hamming_distance' | doris: 'hamming_distance'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "hamming_distance('abc','abd')=1 (Doris live; Trino same).",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [56] trino: 'soundex' | doris: 'soundex'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "soundex('Robert')='R163' (Doris live; Trino same). (DuckDB needs splink_udfs; irrelevant to Trino->Doris.)",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [57] trino: 'from_base64' | doris: 'from_base64'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [58] trino: 'to_base64' | doris: 'to_base64'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [59] trino: 'lpad' | doris: 'lpad'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Pad, unicode pad, over-length truncation aligned.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [60] trino: 'rpad' | doris: 'rpad'
    FunctionHazard(HazardVerdict.IDENTICAL,
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [61] trino: 'repeat' | doris: 'repeat'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "repeat('x',0)='' both.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [62] trino: 'translate' | doris: 'translate'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Extra from-chars deleted in both.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [63] trino: 'url_decode' | doris: 'url_decode'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "url_decode('a%20b')='a b' both.",
        areas = listOf("string"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [64] trino: 'concat_ws' | doris: 'concat_ws'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "NULL element skipped; NULL separator -> NULL in both.",
        areas = listOf("string", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [65] trino: 'substr' | doris: 'substr'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "substr('héllo',2,2)='él' (code-point aligned); Doris has substr.",
        areas = listOf("string", "unicode"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch4-string"),
    // [66] trino: 'avg' | doris: 'avg'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "avg{1,2,3,NULL}=2.0 (NULLs skipped); empty->NULL. Doris live; Trino from prior evidence (Trino==DuckDB).",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [67] trino: 'sum' | doris: 'sum'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "sum{1,2,NULL}=3; empty->NULL both. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [68] trino: 'count' | doris: 'count'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "count(x) skips NULL; count(*) counts rows. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [69] trino: 'max' | doris: 'max'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "max ignores NULL. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [70] trino: 'min' | doris: 'min'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "min ignores NULL. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [71] trino: 'bool_and' | doris: 'bool_and'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Value semantics identical but Doris renders BOOLEAN as TINYINT 0/1 over MySQL protocol vs Trino true/false — boolean type mapping required. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "boolean"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [72] trino: 'bool_or' | doris: 'bool_or'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Value semantics identical but Doris renders BOOLEAN as 0/1 vs Trino true/false — boolean type mapping. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "boolean"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [73] trino: 'any_value' | doris: 'any_value'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Order-sensitive/nondeterministic arbitrary group value; matched this probe but not guaranteed. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [74] trino: 'max_by' | doris: 'max_by'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "arg_max semantics matched (picks value at max key) but tie-breaking nondeterministic. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [75] trino: 'min_by' | doris: 'min_by'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "arg_min semantics matched (min_by(y,x) picks y at min x = 'a') but tie-breaking nondeterministic. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [76] trino: 'corr' | doris: 'corr'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff vs live DuckDB (0.9999008674099173 vs ...172) — value-equivalent. Doris live; Trino from prior evidence (Trino==DuckDB).",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [77] trino: 'covar_pop' | doris: 'covar_pop'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [78] trino: 'covar_samp' | doris: 'covar_samp'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff (2.05 vs 2.049999999999999) — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [79] trino: 'stddev_pop' | doris: 'stddev_pop'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "stddev_pop{1,2,4}=1.247219128924647 exact match vs live DuckDB. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
)

private fun hazardsChunk2(): List<FunctionHazard> = listOf(
    // [80] trino: 'stddev_samp' | doris: 'stddev_samp'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent; sample (N-1) normalization matches. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [81] trino: 'var_pop' | doris: 'var_pop'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [82] trino: 'var_samp' | doris: 'var_samp'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent; sample (N-1) matches. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [83] trino: 'stddev' | doris: 'stddev'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: DEFAULT MISMATCH. Trino stddev == stddev_samp (N-1) = 1.5275252316519468; Doris stddev == stddev_pop (N) = 1.247219128924647 over {1,2,4}. Doris's bare stddev is POPULATION, not sample. Must map Trino stddev -> Doris stddev_samp for parity, never by name.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [84] trino: 'variance' | doris: 'variance'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: DEFAULT MISMATCH. Trino variance == var_samp (N-1) = 2.3333333333333335; Doris variance == var_pop (N) = 1.555555555555556 over {1,2,4}. Doris's bare variance is POPULATION, not sample. Must map Trino variance -> Doris var_samp for parity, never by name.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [85] trino: 'skewness' | doris: 'skewness'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: different formula/default. Over {1,2,4,8}: DuckDB(=Trino sample) 1.1376243669576889 vs Doris 0.6568077344996993 (population moment). Sample-vs-population divergence. Doris live; Trino via DuckDB bridge.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [86] trino: 'kurtosis' | doris: 'kurtosis'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: different formula/default. Over {1,2,4,8}: DuckDB(=Trino sample excess) 0.7576559546313808 vs Doris -1.098979206049149 (population excess). Sign and magnitude differ. Doris live; Trino via DuckDB bridge.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [87] trino: 'regr_intercept' | doris: 'regr_intercept'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [88] trino: 'regr_slope' | doris: 'regr_slope'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Last-ULP float diff (2.05 vs 2.049999999999999) — value-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [89] trino: 'array_agg' | doris: 'array_agg'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Returns a LIST/ARRAY (type layer). Order is input-order-dependent and nondeterministic without ORDER BY: DuckDB preserved input order [3,1,2] while Doris returned [1,2,3] on the same UNION-ALL. Add explicit ORDER BY for deterministic parity. Doris live; Trino via DuckDB bridge.",
        areas = listOf("aggregate", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [90] trino: 'map_agg' | doris: 'map_agg'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Returns a MAP (type layer). Doris has map_agg; Trino map_agg builds key->value. Element ordering within the map is nondeterministic — conditionally-equivalent. DuckDB lacks map_agg (Trino-only bridge; compare via histogram/map). Doris live; Trino from prior evidence.",
        areas = listOf("aggregate", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [91] trino: 'histogram' | doris: 'histogram'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Probe-verified live: incompatible return type/semantics. Trino histogram returns a MAP(value->count) (matching DuckDB {a=2,b=1}); Doris histogram returns an approximate-quantile bucket JSON string. Not interchangeable by name. Doris live; Trino via DuckDB bridge.",
        areas = listOf("aggregate", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [92] trino: 'row_number' | doris: 'row_number'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "row_number() OVER(ORDER BY x) = 1,2,3 both. Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [93] trino: 'rank' | doris: 'rank'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "rank() with tie = 1,1,3 (gap). Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [94] trino: 'dense_rank' | doris: 'dense_rank'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "dense_rank() with tie = 1,1,2 (no gap). Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [95] trino: 'ntile' | doris: 'ntile'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "ntile(2) over 3 rows = 1,1,2 both. Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [96] trino: 'lag' | doris: 'lag'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "lag(x) OVER(ORDER BY x) -> NULL,1,2 both. Doris live; Trino from prior evidence.",
        areas = listOf("window", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [97] trino: 'lead' | doris: 'lead'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "lead(x) OVER(ORDER BY x) -> 2,3,NULL both. Doris live; Trino from prior evidence.",
        areas = listOf("window", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [98] trino: 'first_value' | doris: 'first_value'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "first_value(x) OVER(ORDER BY x) = 1,1,1 both. Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [99] trino: 'last_value' | doris: 'last_value'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "last_value(x) OVER(ORDER BY x) = 1,2,3 both — same default frame (running window). Doris live; Trino from prior evidence.",
        areas = listOf("window"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [100] trino: 'nth_value' | doris: 'nth_value'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "nth_value(x,2) OVER(ORDER BY x) = NULL,2,2 both. Doris live; Trino from prior evidence.",
        areas = listOf("window", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [101] trino: 'percent_rank' | doris: 'percent_rank'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Values identical (0,0.5,1) but Doris renders integral doubles as '0'/'1' vs '0.0'/'1.0' — numeric rendering only. Doris live; Trino from prior evidence.",
        areas = listOf("window", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [102] trino: 'cume_dist' | doris: 'cume_dist'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Values identical (0.333..,0.666..,1) but Doris renders trailing 1.0 as '1' — numeric rendering only. Doris live; Trino from prior evidence.",
        areas = listOf("window", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch5-agg"),
    // [103] trino: 'date_add' | doris: 'date_add'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "SIGNATURE MISMATCH: Trino date_add(VARCHAR unit, BIGINT n, timestamp) (e.g. date_add('day',1,ts)); Doris date_add(date, INTERVAL n unit) / date_add(date, n). Different arg order and arity — must remap unit-string form to INTERVAL, never push by name. (Prior trino-duckdb corpus also flags date_add same-name/incompatible-signature.) Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [104] trino: 'date_format' | doris: 'date_format'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "BOTH use MySQL-style '%'-specifiers (NOT Joda): Trino date_format(ts,'%Y-%m-%d')='2024-01-02' and Doris date_format(TIMESTAMP '2024-01-02 03:04:05','%Y-%m-%d')='2024-01-02' (probe-verified live on Doris; Trino from prior evidence). %H:%i:%s and %M(month name) align. NOTE the family trap: Trino format_datetime/parse_datetime use Joda 'yyyy' — those do NOT map to Doris date_format. Doris also partially tolerates 'yyyy-MM-dd' but bare 'yyyy' is a literal, so map ONLY via '%' specs. Conditionally-equivalent on the '%'-spec dialect.",
        areas = listOf("datetime", "format"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [105] trino: 'date_trunc' | doris: 'date_trunc'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Values align for the intersection unit set (day..year): date_trunc('month',ts)='2024-02-01 00:00:00', 'quarter'->'2024-01-01' both. Trino returns TIMESTAMP; Doris DATETIME (Doris renders no fractional part, Trino/DuckDB '.0'). Week unit Monday-start on both. Conditionally-equivalent, verify unit set. Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [106] trino: 'date' | doris: 'date'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "date('2024-02-29')='2024-02-29' — DuckDB bridge SAME as Doris; Trino date(x) cast-to-date equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [107] trino: 'day' | doris: 'day'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "day(DATE '2024-02-29')=29 (DuckDB bridge==Doris). Doris live; Trino from prior evidence (prior corpus: year/month/day aligned).",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [108] trino: 'month' | doris: 'month'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "month(DATE '2024-02-29')=2 (bridge==Doris). Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [109] trino: 'year' | doris: 'year'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "year(DATE '2024-02-29')=2024 (bridge==Doris). Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [110] trino: 'quarter' | doris: 'quarter'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "quarter(DATE '2024-02-29')=1 (bridge==Doris). Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [111] trino: 'week' | doris: 'week'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "WEEK-MODE MISMATCH: Trino week/week_of_year is ISO-8601 (Mon-start, week 01 contains Jan 4) so week('2023-01-01')=52; Doris default week() is mode 0 (Sunday-start) -> week('2023-01-01')=1, week('2024-01-01')=0. Prior trino-duckdb corpus confirms Trino week is ISO==DuckDB(52). Divergent unless Doris week mode pinned to ISO (weekofyear or week(d,3)). Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [112] trino: 'minute' | doris: 'minute'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "minute(TIMESTAMP '2024-01-02 03:04:05')=4 (bridge==Doris). Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [113] trino: 'second' | doris: 'second'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "second(...)=5 (bridge==Doris). Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [114] trino: 'hour' | doris: 'hour'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "hour(...)=3 (bridge==Doris). Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [115] trino: 'dow' | doris: 'dayofweek'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "NUMBERING MISMATCH: Trino day_of_week/dow is ISO 1..7 Monday=1..Sunday=7; Doris dayofweek is 1..7 Sunday=1..Saturday=7 (MySQL). Sunday '2024-01-07': Trino dow=7, Doris dayofweek=1. Monday '2024-01-08': Trino=1, Doris=2. Off by rotation — divergent. (Prior corpus: Trino dow 1..7 Mon=1 vs DuckDB 0..6 Sun=0.) Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [116] trino: 'doy' | doris: 'dayofyear'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "day_of_year/doy: leap-day '2024-02-29'=60 (bridge==Doris; prior corpus Trino doy==DuckDB). Rename only. Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [117] trino: 'yow' | doris: 'yearweek'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "WEEK-YEAR MODE MISMATCH: Trino year_of_week/yow is ISO week-year: yow('2023-01-01')=2022; Doris yearweek('2023-01-01')=202301 (default mode 0, embeds week too and picks year 2023). Different value AND encoding (Doris packs YYYYWW). To get the ISO year-of-week from Doris use a mode-3 yearweek/2 and strip week. Divergent. Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [118] trino: 'year_of_week' | doris: 'year_of_week'
    FunctionHazard(HazardVerdict.NO_EQUIVALENT,
        hazard = "Trino year_of_week returns the ISO week-year (2022 for '2023-01-01'). Doris has NO year_of_week function; its yearweek packs YYYYWW under a different (mode-0) week definition. No direct name equivalent — express via Doris yearweek(d,3) DIV 100. Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [119] trino: 'from_unixtime' | doris: 'from_unixtime'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "from_unixtime(0)='1970-01-01 00:00:00' on Doris (probe-verified live); Trino from_unixtime(double) returns TIMESTAMP(3) WITH TIME ZONE in the session zone (prior corpus: same absolute instant, rendering session-zone dependent). SESSION-ZONE dependent — the harness cannot pre-SET zone, so equivalence holds only for the same session zone. Doris also has a 2-arg from_unixtime(sec,fmt) (from_unixtime(0,'yyyy-MM-dd')='1970-01-01'). Conditionally-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("datetime", "session"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
)

private fun hazardsChunk3(): List<FunctionHazard> = listOf(
    // [120] trino: 'from_iso8601_date' | doris: 'from_iso8601_date'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "from_iso8601_date('2024-02-29')='2024-02-29' on Doris (probe-verified live); Trino from_iso8601_date parses an ISO date to DATE identically. Both leap-day safe. Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [121] trino: 'to_iso8601' | doris: 'to_iso8601'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "to_iso8601(DATE '2024-02-29')='2024-02-29' both (aligned). For TIMESTAMP: Doris to_iso8601(TIMESTAMP '2024-02-29 03:04:05')='2024-02-29T03:04:05.000000' (6 fractional digits, no zone); Trino to_iso8601(timestamp) yields '...T03:04:05.000' (3 digits) and for tz-aware types appends the offset. Fractional-precision/zone rendering differs — conditionally-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("datetime", "format"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [122] trino: 'now' | doris: 'now'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Both return current instant; Trino now() is TIMESTAMP WITH TIME ZONE (session zone, ISO render); Doris now()='2026-07-13 07:38:31' (space sep, second precision, session-zone). SESSION-ZONE dependent — cannot pre-SET in harness. Value-equivalent instant, format/precision/zone differ. Doris live; Trino from prior evidence.",
        areas = listOf("datetime", "session"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [123] trino: 'current_date' | doris: 'current_date'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "current_date rendered identically live ('2026-07-13'); Trino current_date is date in session zone. SESSION-ZONE dependent — equivalence only for matching session zone. Doris live; Trino from prior evidence.",
        areas = listOf("datetime", "session"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [124] trino: 'last_day_of_month' | doris: 'last_day'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Rename: Trino last_day_of_month(DATE '2024-02-15')='2024-02-29'; Doris last_day(DATE '2024-02-15')='2024-02-29' (probe-verified live, leap-Feb). Doris live; Trino from prior evidence.",
        areas = listOf("datetime"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch6-datetime"),
    // [125] trino: 'array_distinct' | doris: 'array_distinct'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris live: array_distinct([1,1,2,3,3])=[1,2,3] (size 3, e1=1 — preserves first-occurrence order). Trino array_distinct also preserves order (==DuckDB list_distinct set-wise, but DuckDB returns reversed [3,2,1]). Set/length identical; ORDER matches Trino but the DuckDB bridge reorders — order-preservation must be verified per element, not by raw render. Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [126] trino: 'array_first' | doris: 'array_first'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "SIGNATURE trap. Doris live: array_first is a LAMBDA/predicate fn — array_first(x->x>0,[10,20,30])=10 (first element matching the predicate; the array is the SECOND arg). Trino array_first(array) returns the plain first element with no predicate. Arity/semantics differ -> map by rewriting to array_first(x->true, arr) or element_at(arr,1). Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [127] trino: 'array_last' | doris: 'array_last'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "SIGNATURE trap (same as array_first). Doris live: array_last(x->x>0,[10,20,30])=30 — lambda predicate first, array second. Trino array_last(array) is the plain last element. Map via array_last(x->true,arr) or element_at(arr,-1). Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [128] trino: 'array_intersect' | doris: 'array_intersect'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris live: array_intersect([1,2,3],[2,3,4])=[2,3] (e1=2, size 2). Matches Trino (prior corpus: Trino array_intersect==DuckDB list_intersect identical). Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [129] trino: 'array_position' | doris: 'array_position'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris live: array_position([10,20,30],20)=2 (1-based), and NOT-FOUND array_position([10,20,30],99)=0. Trino array_position is also 1-based and returns 0 when absent (matches). NOTE the DuckDB bridge differs on not-found (list_position returns NULL, not 0) — do not adjudicate via DuckDB here. Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [130] trino: 'array_sort' | doris: 'array_sort'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris live: array_sort([3,1,2]) ascending -> e1=1,e3=3; NULL-bearing array_sort([3,NULL,1]) keeps NULL (size preserved =3). Trino array_sort places NULLs last; verify NULL ordering per element before relying on it. Ascending default aligns. Doris live; Trino from prior evidence.",
        areas = listOf("array", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [131] trino: 'array_except' | doris: 'array_except'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris live: array_except([1,2,3,4],[2,4])=[1,3] (size 2, e1=1). Trino array_except is the same set-difference. (Prior corpus marked it no-equivalent on the DuckDB side — DuckDB lacks it — but Doris HAS it and matches Trino.) Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [132] trino: 'array_remove' | doris: 'array_remove'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris live: array_remove([1,2,3,2],2)=[1,3] (size 2, e1=1) — removes ALL occurrences. Trino array_remove is the same. (Prior corpus: DuckDB lacks it, needed list_filter workaround; Doris HAS it and matches Trino.) Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [133] trino: 'array_union' | doris: 'array_union'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris live: array_union([1,2,3],[3,4]) -> size 4 (distinct union). Trino array_union is the same. (Prior corpus: DuckDB needed list_distinct(list_concat(...)); Doris HAS array_union by name and matches Trino.) Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [134] trino: 'arrays_overlap' | doris: 'arrays_overlap'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris live: arrays_overlap([1,2],[2,3])=1 (overlap) and arrays_overlap([1,2],[3,4])=0 (disjoint). Value semantics match Trino, but Doris returns TINYINT 0/1 while Trino returns BOOLEAN — boolean type mapping required (Doris renders BOOLEAN as 0/1 over the MySQL protocol). Doris live; Trino from prior evidence.",
        areas = listOf("array", "boolean"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [135] trino: 'cardinality' | doris: 'array_size'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris live: array length is array_size([1,2,3])=3; Doris cardinality also works on arrays, but the portable name is array_size (Doris has NO array_length). Trino cardinality(array) returns element count -> value matches via array_size, but the name maps to array_size (or element count). Map-cardinality (Trino) also -> not covered here. Rename required. Doris live; Trino from prior evidence.",
        areas = listOf("array", "map"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [136] trino: 'element_at' | doris: 'element_at'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris live: element_at([10,20,30],2)=20 (1-based) but OUT-OF-BOUNDS element_at([10,20,30],9)=NULL (returns NULL, does not throw). Trino element_at on an array THROWS on out-of-bounds index (does NOT return NULL) — divergent on the OOB path. In-bounds 1-based access aligns. Doris live; Trino from prior evidence.",
        areas = listOf("array", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [137] trino: 'contains' | doris: 'array_contains'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris live: 'contains' does NOT exist ('Can not found function contains'); the array-membership fn is array_contains([1,2,3],2) -> 1 (TINYINT). Trino contains(array,elem) returns BOOLEAN true. Both a NAME map (contains->array_contains) AND a boolean 0/1-vs-true/false type map are required. Doris live; Trino from prior evidence.",
        areas = listOf("array", "boolean"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [138] trino: 'array_join' | doris: 'array_join'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris live: array_join([1,2,3],'-')='1-2-3'; with a NULL element array_join([1,NULL,3],'-')='1-3' (NULL SKIPPED when no 3rd nullReplacement arg). Trino array_join(x,sep) ALSO skips NULLs by default, but the 3-arg form array_join(x,sep,nullStr) semantics/prior corpus marks array_join->DuckDB array_to_string as divergent (DuckDB array_to_string has no null-replacement 3rd arg). Value of the 2-arg NULL-skip aligns Doris<->Trino; adjudicated divergent to carry the 3-arg/DuckDB-bridge hazard forward. Doris live; Trino from prior evidence.",
        areas = listOf("array", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [139] trino: 'array_max' | doris: 'array_max'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "NULL-propagation divergence. Doris live: array_max([1,2,3])=3 and array_max([1,NULL,2])=2 (Doris SKIPS NULL elements). Trino array_max PROPAGATES NULL — array_max(array[1,null,2]) returns NULL if any element is NULL. So on a NULL-bearing array Doris(2) != Trino(NULL). Non-NULL arrays align. Doris live; Trino from prior evidence.",
        areas = listOf("array", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [140] trino: 'array_min' | doris: 'array_min'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "NULL-propagation divergence (same as array_max). Doris live: array_min([3,1,2])=1 and array_min([1,NULL,2])=1 (Doris SKIPS NULL). Trino array_min propagates NULL -> NULL when any element is NULL. Non-NULL arrays align; NULL-bearing arrays diverge. Doris live; Trino from prior evidence.",
        areas = listOf("array", "null"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [141] trino: 'split' | doris: 'split_by_string'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "Doris live: split_by_string('a,b,c',',') -> size 3 works; Doris has split_by_string (and split_part), NOT a Trino-style split(str,delim,limit). Prior corpus already marks Trino split->DuckDB string_split as divergent (Trino split has a 3-arg limit form and empty-delimiter behavior differs). Map Trino split -> Doris split_by_string, never by name; verify empty-delimiter and limit-arg per case. Doris live; Trino from prior evidence.",
        areas = listOf("string", "array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [142] trino: 'shuffle' | doris: 'shuffle'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris live: shuffle([1,2,3]) returns a size-3 array (nondeterministic permutation). Trino shuffle is likewise a random permutation. Equal as a multiset but element ORDER is nondeterministic per call -> conditionally-equivalent (nondeterministic; compare as multiset only). (Prior corpus: DuckDB has no shuffle -> no-equivalent on the DuckDB side; Doris HAS shuffle.) Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [143] trino: 'sequence' | doris: 'sequence'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris live: sequence(1,5) -> size 5, last element =5 (INCLUSIVE stop). Trino sequence(1,5) is also inclusive [1..5]. (DuckDB bridge: generate_series is inclusive/range is exclusive — use generate_series, per prior corpus conditionally-equivalent.) Doris matches Trino inclusive semantics. Doris live; Trino from prior evidence.",
        areas = listOf("array"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [144] trino: 'cosine_similarity' | doris: 'cosine_similarity'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris live: cosine_similarity([1,2,3],[1,2,3])=1.0. Matches Trino/DuckDB (list_cosine_similarity=1.0) on the value; float representation/ULP may differ. Doris live; Trino from prior evidence.",
        areas = listOf("array", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [145] trino: 'cosine_distance' | doris: 'cosine_distance'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris live: cosine_distance([1,2,3],[4,5,6])=0.02536809 vs DuckDB/Trino list_cosine_distance=0.025368153802923787 — same value, differs only in the last ULP digits / render precision (Doris ~8 sig figs). Float ULP diff -> conditionally-equivalent. Doris live; Trino from prior evidence.",
        areas = listOf("array", "numeric"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [146] trino: 'cardinality_map' | doris: 'cardinality'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Map cardinality maps by name: Doris cardinality(map) and Trino cardinality(map) both return the entry count (matches DuckDB cardinality(MAP)=2). Only the ARRAY overload of cardinality needs the array_size rename (see the cardinality/array_size pair). Doris live; Trino from prior evidence.",
        areas = listOf("map"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch7-array"),
    // [147] trino: 'json_extract' | doris: 'json_extract'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "Doris live == DuckDB live (json_extract('{\"a\":\"x\"}','\$.a')='\"x\"' with QUOTES retained; \$.b='[10,20]'; \$.b[0]='10'; nested \$.c.d='\"x\"'; missing path NULL). Prior corpus (trino-duckdb-hazards.json) records Trino json_extract == DuckDB json_extract (conditionally-equivalent, both return a JSON value with quotes retained). Chaining: Trino==DuckDB==Doris live -> identical. Trino json_extract_scalar (unquoted) maps to Doris json_extract_string. Doris live; Trino from prior evidence.",
        areas = listOf("json"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch8-json"),
    // [148] trino: 'json_parse' | doris: 'json_parse'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris json_parse probe-verified live: json_parse('[1,2,3]')='[1,2,3]' and json_parse('{\"a\":1}')='{\"a\":1}' (VARCHAR text -> JSON value), matching Trino json_parse's happy-path role. DIVERGENCE in error handling: Trino json_parse THROWS on malformed input; Doris json_parse('not json')='null' (returns JSON null silently, does NOT error). Value-equivalent on valid JSON, differs on invalid input (Doris swallows the error). Doris live; Trino from prior evidence.",
        areas = listOf("json"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch8-json"),
    // [149] trino: 'json_format' | doris: 'json_format'
    FunctionHazard(HazardVerdict.NO_EQUIVALENT,
        hazard = "Trino json_format(JSON)->VARCHAR (serialize a JSON value to its text form). No Doris function by that name (DuckDB also lacks it — prior corpus marks Trino json_format as no-equivalent). Doris achieves the same via CAST(json AS string) / to-string rendering, but there is no named json_format built-in. Prior corpus: no-equivalent. Doris live inventory checked; Trino from prior evidence.",
        areas = listOf("json"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch8-json"),
    // [150] trino: 'e' | doris: 'e'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "RE-ADJUDICATED vs Doris (prior corpus said no-equivalent because DuckDB has no e()). Doris HAS e(): e()=2.718281828459045, exactly Trino's e() (Euler's number). Doris live; Trino from prior evidence. Identical.",
        areas = listOf("math"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [151] trino: 'crc32' | doris: 'crc32'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "RE-ADJUDICATED vs Doris (prior corpus no-equivalent vs DuckDB). Doris crc32('abc')=891568578 which equals the standard CRC-32 of 'abc' (zlib.crc32('abc')=891568578), matching Trino's crc32(varbinary) numeric result. Doris live; Trino from prior evidence. Identical (Trino takes varbinary, Doris varchar — same underlying bytes for ASCII).",
        areas = listOf("hash"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [152] trino: 'normal_cdf' | doris: 'normal_cdf'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "RE-ADJUDICATED vs Doris (prior no-equivalent vs DuckDB). Doris normal_cdf(0,1,0.5)=0.6914624612740131 = 0.5*(1+erf(0.5/sqrt(2))) = Phi(0.5), and the arg order (mean, sd, value) matches Trino's normal_cdf(mean, sd, value). Doris live; Trino from prior evidence. Identical.",
        areas = listOf("math", "statistics"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [153] trino: 'regexp_count' | doris: 'regexp_count'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "RE-ADJUDICATED vs Doris (prior no-equivalent vs DuckDB — DuckDB lacks it). Doris regexp_count('a1b2c3','[0-9]')=3, matching Trino's regexp_count(string, pattern) count of non-overlapping matches. Doris live; Trino from prior evidence. Identical.",
        areas = listOf("string", "regex"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [154] trino: 'regexp_extract' | doris: 'regexp_extract'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Doris live via bridge (Trino==DuckDB prior). Doris regexp_extract REQUIRES a group index: regexp_extract('abc123','([0-9]+)',0)='123' (whole match, group 0), ('...',1)='123', and ('([a-z]+)([0-9]+)',2)='123' — group semantics match Trino. But Trino's 2-arg regexp_extract(str, pattern) (whole match) has NO direct Doris arity — Doris errors on the 2-arg form. Conditionally-equivalent: use the explicit-group 3-arg form on Doris.",
        areas = listOf("string", "regex"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [155] trino: 'truncate' | doris: 'truncate'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "RE-ADJUDICATED vs Doris. Doris truncate(3.14159,2)=3.14 matches Trino truncate(x,n) (truncate toward zero to n decimals). Prior corpus already marked truncate identical for Trino==DuckDB rename; confirmed live on Doris. Doris live; Trino from prior evidence. Identical.",
        areas = listOf("math"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [156] trino: 'width_bucket' | doris: 'width_bucket'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "RE-ADJUDICATED vs Doris (prior no-equivalent vs DuckDB 'different shape'). Doris width_bucket(5.0,0.0,10.0,5)=3, exactly Trino's width_bucket(operand, bound1, bound2, bucketCount): 5 buckets over (0,10] width 2, 5.0 falls in (4,6]=bucket 3. Signature and result match. Doris live; Trino from prior evidence. Identical.",
        areas = listOf("math", "statistics"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [157] trino: 'parse_data_size' | doris: 'parse_data_size'
    FunctionHazard(HazardVerdict.IDENTICAL,
        hazard = "RE-ADJUDICATED vs Doris (prior no-equivalent vs DuckDB). Doris parse_data_size('1kB')=1024, matching Trino parse_data_size (kB=1024 bytes, decimal result). Doris live; Trino from prior evidence. Identical for the value; Trino returns decimal(38,0), Doris returns the integer 1024 (same magnitude).",
        areas = listOf("string", "units"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [158] trino: 'rand' | doris: 'rand'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Non-deterministic RNG. Doris has random()/rand() returning double in [0,1) (probe-verified [0,1)). Trino rand()/random() same distribution; bounded Trino forms random(n)/random(m,n) also exist. Never pushable/comparable value-for-value. Doris live; Trino from prior evidence.",
        areas = listOf("random", "nondeterministic"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [159] trino: 'random' | doris: 'random'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Non-deterministic. Doris random() returns double in [0,1) (probe-verified). Trino random() same; Trino also has bounded random(n) (0..n) and random(m,n) integer forms whose exact bound semantics were not probed on Doris. Never pushable. Doris live; Trino from prior evidence.",
        areas = listOf("random", "nondeterministic"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
)

private fun hazardsChunk4(): List<FunctionHazard> = listOf(
    // [160] trino: 'uuid' | doris: 'uuid'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Both produce a canonical 36-char UUID string (Doris length=36). Non-deterministic — same shape, never pushable/comparable value-for-value. Doris live; Trino from prior evidence.",
        areas = listOf("random", "nondeterministic"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [161] trino: 'map' | doris: 'map'
    FunctionHazard(HazardVerdict.DIVERGENT,
        hazard = "CONSTRUCTOR SIGNATURE differs. Trino map(array(K),array(V)) takes two parallel arrays (like DuckDB; Trino==DuckDB prior). Doris map(k1,v1,k2,v2) takes flattened alternating scalars. Probe-verified: Doris does not build the same map from the two-array form (map_keys(map([1,2],['a','b']))=[[1, 2]] on Doris vs [1,2] expected). Must translate the constructor. Doris live; Trino from prior evidence.",
        areas = listOf("map", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [162] trino: 'map_keys' | doris: 'map_keys'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Same semantics once the map is built with each engine's own constructor. Doris map_keys(map(1,'a',2,'b'))='[1, 2]' matches Trino/DuckDB key set; array_size=2. Conditionally-equivalent due to the divergent map() constructor and array render. Doris live; Trino from prior evidence.",
        areas = listOf("map", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [163] trino: 'map_values' | doris: 'map_values'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Same value set; Doris map_values(map(1,'a',2,'b'))='[\"a\", \"b\"]' (JSON-quoted render) matches Trino/DuckDB values element-wise. Depends on divergent map() constructor and render. Doris live; Trino from prior evidence.",
        areas = listOf("map", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [164] trino: 'map_entries' | doris: 'map_entries'
    FunctionHazard(HazardVerdict.CONDITIONALLY_EQUIVALENT,
        hazard = "Element type: Trino map_entries returns array(row(K,V)); Doris returns array of struct with fields key/value: map_entries(map(1,'a',2,'b'))='[{\"key\":1, \"value\":\"a\"}, {\"key\":2, \"value\":\"b\"}]'. Compatible shape (unnamed row vs named key/value struct) — needs a type-layer mapping, plus the divergent map() constructor. Doris live; Trino from prior evidence.",
        areas = listOf("map", "collection"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
    // [165] trino: 'unnest' | doris: 'unnest'
    FunctionHazard(HazardVerdict.UNCLEAR,
        hazard = "table function (row-generating), not scalar-probeable through the shared-expr harness; needs a table-function harness for a row-set/ordering comparison.",
        areas = listOf("table-function"),
        provenance = "REPORT-doris-differential-probe-2026-07-13.md#batch9-misc"),
)

/** trino->doris lookup: 166 keys (Trino-side names) over 166 entries. */
internal val TRINO_TO_DORIS_HAZARDS: Map<String, FunctionHazard> = buildMap {
    put("ABS", TRINO_DORIS_HAZARD_ENTRIES[16])
    put("ACOS", TRINO_DORIS_HAZARD_ENTRIES[21])
    put("ANY_VALUE", TRINO_DORIS_HAZARD_ENTRIES[73])
    put("ARRAYS_OVERLAP", TRINO_DORIS_HAZARD_ENTRIES[134])
    put("ARRAY_AGG", TRINO_DORIS_HAZARD_ENTRIES[89])
    put("ARRAY_DISTINCT", TRINO_DORIS_HAZARD_ENTRIES[125])
    put("ARRAY_EXCEPT", TRINO_DORIS_HAZARD_ENTRIES[131])
    put("ARRAY_FIRST", TRINO_DORIS_HAZARD_ENTRIES[126])
    put("ARRAY_INTERSECT", TRINO_DORIS_HAZARD_ENTRIES[128])
    put("ARRAY_JOIN", TRINO_DORIS_HAZARD_ENTRIES[138])
    put("ARRAY_LAST", TRINO_DORIS_HAZARD_ENTRIES[127])
    put("ARRAY_MAX", TRINO_DORIS_HAZARD_ENTRIES[139])
    put("ARRAY_MIN", TRINO_DORIS_HAZARD_ENTRIES[140])
    put("ARRAY_POSITION", TRINO_DORIS_HAZARD_ENTRIES[129])
    put("ARRAY_REMOVE", TRINO_DORIS_HAZARD_ENTRIES[132])
    put("ARRAY_SORT", TRINO_DORIS_HAZARD_ENTRIES[130])
    put("ARRAY_UNION", TRINO_DORIS_HAZARD_ENTRIES[133])
    put("ASCII", TRINO_DORIS_HAZARD_ENTRIES[8])
    put("ASIN", TRINO_DORIS_HAZARD_ENTRIES[22])
    put("ATAN", TRINO_DORIS_HAZARD_ENTRIES[30])
    put("ATAN2", TRINO_DORIS_HAZARD_ENTRIES[31])
    put("AVG", TRINO_DORIS_HAZARD_ENTRIES[66])
    put("BIT_COUNT", TRINO_DORIS_HAZARD_ENTRIES[12])
    put("BOOL_AND", TRINO_DORIS_HAZARD_ENTRIES[71])
    put("BOOL_OR", TRINO_DORIS_HAZARD_ENTRIES[72])
    put("CARDINALITY", TRINO_DORIS_HAZARD_ENTRIES[135])
    put("CARDINALITY_MAP", TRINO_DORIS_HAZARD_ENTRIES[146])
    put("CBRT", TRINO_DORIS_HAZARD_ENTRIES[29])
    put("CEIL", TRINO_DORIS_HAZARD_ENTRIES[38])
    put("CEILING", TRINO_DORIS_HAZARD_ENTRIES[39])
    put("COALESCE", TRINO_DORIS_HAZARD_ENTRIES[18])
    put("CONCAT", TRINO_DORIS_HAZARD_ENTRIES[2])
    put("CONCAT_WS", TRINO_DORIS_HAZARD_ENTRIES[64])
    put("CONTAINS", TRINO_DORIS_HAZARD_ENTRIES[137])
    put("CORR", TRINO_DORIS_HAZARD_ENTRIES[76])
    put("COS", TRINO_DORIS_HAZARD_ENTRIES[32])
    put("COSH", TRINO_DORIS_HAZARD_ENTRIES[33])
    put("COSINE_DISTANCE", TRINO_DORIS_HAZARD_ENTRIES[145])
    put("COSINE_SIMILARITY", TRINO_DORIS_HAZARD_ENTRIES[144])
    put("COUNT", TRINO_DORIS_HAZARD_ENTRIES[68])
    put("COVAR_POP", TRINO_DORIS_HAZARD_ENTRIES[77])
    put("COVAR_SAMP", TRINO_DORIS_HAZARD_ENTRIES[78])
    put("CRC32", TRINO_DORIS_HAZARD_ENTRIES[151])
    put("CUME_DIST", TRINO_DORIS_HAZARD_ENTRIES[102])
    put("CURRENT_DATE", TRINO_DORIS_HAZARD_ENTRIES[123])
    put("DATE", TRINO_DORIS_HAZARD_ENTRIES[106])
    put("DATE_ADD", TRINO_DORIS_HAZARD_ENTRIES[103])
    put("DATE_FORMAT", TRINO_DORIS_HAZARD_ENTRIES[104])
    put("DATE_TRUNC", TRINO_DORIS_HAZARD_ENTRIES[105])
    put("DAY", TRINO_DORIS_HAZARD_ENTRIES[107])
    put("DEGREES", TRINO_DORIS_HAZARD_ENTRIES[41])
    put("DENSE_RANK", TRINO_DORIS_HAZARD_ENTRIES[94])
    put("DOW", TRINO_DORIS_HAZARD_ENTRIES[115])
    put("DOY", TRINO_DORIS_HAZARD_ENTRIES[116])
    put("E", TRINO_DORIS_HAZARD_ENTRIES[150])
    put("ELEMENT_AT", TRINO_DORIS_HAZARD_ENTRIES[136])
    put("EXP", TRINO_DORIS_HAZARD_ENTRIES[28])
    put("FIRST_VALUE", TRINO_DORIS_HAZARD_ENTRIES[98])
    put("FLOOR", TRINO_DORIS_HAZARD_ENTRIES[40])
    put("FMOD", TRINO_DORIS_HAZARD_ENTRIES[13])
    put("FORMAT_NUMBER", TRINO_DORIS_HAZARD_ENTRIES[49])
    put("FROM_BASE64", TRINO_DORIS_HAZARD_ENTRIES[57])
    put("FROM_HEX", TRINO_DORIS_HAZARD_ENTRIES[48])
    put("FROM_ISO8601_DATE", TRINO_DORIS_HAZARD_ENTRIES[120])
    put("FROM_UNIXTIME", TRINO_DORIS_HAZARD_ENTRIES[119])
    put("GREATEST", TRINO_DORIS_HAZARD_ENTRIES[3])
    put("HAMMING_DISTANCE", TRINO_DORIS_HAZARD_ENTRIES[55])
    put("HISTOGRAM", TRINO_DORIS_HAZARD_ENTRIES[91])
    put("HOUR", TRINO_DORIS_HAZARD_ENTRIES[114])
    put("JSON_EXTRACT", TRINO_DORIS_HAZARD_ENTRIES[147])
    put("JSON_FORMAT", TRINO_DORIS_HAZARD_ENTRIES[149])
    put("JSON_PARSE", TRINO_DORIS_HAZARD_ENTRIES[148])
    put("KURTOSIS", TRINO_DORIS_HAZARD_ENTRIES[86])
    put("LAG", TRINO_DORIS_HAZARD_ENTRIES[96])
    put("LAST_DAY_OF_MONTH", TRINO_DORIS_HAZARD_ENTRIES[124])
    put("LAST_VALUE", TRINO_DORIS_HAZARD_ENTRIES[99])
    put("LEAD", TRINO_DORIS_HAZARD_ENTRIES[97])
    put("LEAST", TRINO_DORIS_HAZARD_ENTRIES[4])
    put("LENGTH", TRINO_DORIS_HAZARD_ENTRIES[15])
    put("LEVENSHTEIN_DISTANCE", TRINO_DORIS_HAZARD_ENTRIES[54])
    put("LN", TRINO_DORIS_HAZARD_ENTRIES[23])
    put("LOG", TRINO_DORIS_HAZARD_ENTRIES[27])
    put("LOG10", TRINO_DORIS_HAZARD_ENTRIES[26])
    put("LOG2", TRINO_DORIS_HAZARD_ENTRIES[25])
    put("LOWER", TRINO_DORIS_HAZARD_ENTRIES[0])
    put("LPAD", TRINO_DORIS_HAZARD_ENTRIES[59])
    put("LTRIM", TRINO_DORIS_HAZARD_ENTRIES[10])
    put("MAP", TRINO_DORIS_HAZARD_ENTRIES[161])
    put("MAP_AGG", TRINO_DORIS_HAZARD_ENTRIES[90])
    put("MAP_ENTRIES", TRINO_DORIS_HAZARD_ENTRIES[164])
    put("MAP_KEYS", TRINO_DORIS_HAZARD_ENTRIES[162])
    put("MAP_VALUES", TRINO_DORIS_HAZARD_ENTRIES[163])
    put("MAX", TRINO_DORIS_HAZARD_ENTRIES[69])
    put("MAX_BY", TRINO_DORIS_HAZARD_ENTRIES[74])
    put("MD5", TRINO_DORIS_HAZARD_ENTRIES[20])
    put("MIN", TRINO_DORIS_HAZARD_ENTRIES[70])
    put("MINUTE", TRINO_DORIS_HAZARD_ENTRIES[112])
    put("MIN_BY", TRINO_DORIS_HAZARD_ENTRIES[75])
    put("MOD", TRINO_DORIS_HAZARD_ENTRIES[17])
    put("MONTH", TRINO_DORIS_HAZARD_ENTRIES[108])
    put("NORMAL_CDF", TRINO_DORIS_HAZARD_ENTRIES[152])
    put("NOW", TRINO_DORIS_HAZARD_ENTRIES[122])
    put("NTH_VALUE", TRINO_DORIS_HAZARD_ENTRIES[100])
    put("NTILE", TRINO_DORIS_HAZARD_ENTRIES[95])
    put("NULLIF", TRINO_DORIS_HAZARD_ENTRIES[19])
    put("PARSE_DATA_SIZE", TRINO_DORIS_HAZARD_ENTRIES[157])
    put("PERCENT_RANK", TRINO_DORIS_HAZARD_ENTRIES[101])
    put("PI", TRINO_DORIS_HAZARD_ENTRIES[43])
    put("POW", TRINO_DORIS_HAZARD_ENTRIES[45])
    put("POWER", TRINO_DORIS_HAZARD_ENTRIES[46])
    put("QUARTER", TRINO_DORIS_HAZARD_ENTRIES[110])
    put("RADIANS", TRINO_DORIS_HAZARD_ENTRIES[42])
    put("RAND", TRINO_DORIS_HAZARD_ENTRIES[158])
    put("RANDOM", TRINO_DORIS_HAZARD_ENTRIES[159])
    put("RANK", TRINO_DORIS_HAZARD_ENTRIES[93])
    put("REGEXP_COUNT", TRINO_DORIS_HAZARD_ENTRIES[153])
    put("REGEXP_EXTRACT", TRINO_DORIS_HAZARD_ENTRIES[154])
    put("REGEXP_EXTRACT_ALL", TRINO_DORIS_HAZARD_ENTRIES[14])
    put("REGEXP_REPLACE", TRINO_DORIS_HAZARD_ENTRIES[7])
    put("REGR_INTERCEPT", TRINO_DORIS_HAZARD_ENTRIES[87])
    put("REGR_SLOPE", TRINO_DORIS_HAZARD_ENTRIES[88])
    put("REPEAT", TRINO_DORIS_HAZARD_ENTRIES[61])
    put("REPLACE", TRINO_DORIS_HAZARD_ENTRIES[53])
    put("REVERSE", TRINO_DORIS_HAZARD_ENTRIES[6])
    put("ROW_NUMBER", TRINO_DORIS_HAZARD_ENTRIES[92])
    put("RPAD", TRINO_DORIS_HAZARD_ENTRIES[60])
    put("RTRIM", TRINO_DORIS_HAZARD_ENTRIES[11])
    put("SECOND", TRINO_DORIS_HAZARD_ENTRIES[113])
    put("SEQUENCE", TRINO_DORIS_HAZARD_ENTRIES[143])
    put("SHA1", TRINO_DORIS_HAZARD_ENTRIES[52])
    put("SHUFFLE", TRINO_DORIS_HAZARD_ENTRIES[142])
    put("SIGN", TRINO_DORIS_HAZARD_ENTRIES[44])
    put("SIN", TRINO_DORIS_HAZARD_ENTRIES[34])
    put("SINH", TRINO_DORIS_HAZARD_ENTRIES[35])
    put("SKEWNESS", TRINO_DORIS_HAZARD_ENTRIES[85])
    put("SOUNDEX", TRINO_DORIS_HAZARD_ENTRIES[56])
    put("SPLIT", TRINO_DORIS_HAZARD_ENTRIES[141])
    put("SPLIT_PART", TRINO_DORIS_HAZARD_ENTRIES[5])
    put("SQRT", TRINO_DORIS_HAZARD_ENTRIES[24])
    put("STARTS_WITH", TRINO_DORIS_HAZARD_ENTRIES[51])
    put("STDDEV", TRINO_DORIS_HAZARD_ENTRIES[83])
    put("STDDEV_POP", TRINO_DORIS_HAZARD_ENTRIES[79])
    put("STDDEV_SAMP", TRINO_DORIS_HAZARD_ENTRIES[80])
    put("SUBSTR", TRINO_DORIS_HAZARD_ENTRIES[65])
    put("SUM", TRINO_DORIS_HAZARD_ENTRIES[67])
    put("TAN", TRINO_DORIS_HAZARD_ENTRIES[36])
    put("TANH", TRINO_DORIS_HAZARD_ENTRIES[37])
    put("TO_BASE64", TRINO_DORIS_HAZARD_ENTRIES[58])
    put("TO_HEX", TRINO_DORIS_HAZARD_ENTRIES[47])
    put("TO_ISO8601", TRINO_DORIS_HAZARD_ENTRIES[121])
    put("TRANSLATE", TRINO_DORIS_HAZARD_ENTRIES[62])
    put("TRIM", TRINO_DORIS_HAZARD_ENTRIES[9])
    put("TRUNCATE", TRINO_DORIS_HAZARD_ENTRIES[155])
    put("UNNEST", TRINO_DORIS_HAZARD_ENTRIES[165])
    put("UPPER", TRINO_DORIS_HAZARD_ENTRIES[1])
    put("URL_DECODE", TRINO_DORIS_HAZARD_ENTRIES[63])
    put("URL_ENCODE", TRINO_DORIS_HAZARD_ENTRIES[50])
    put("UUID", TRINO_DORIS_HAZARD_ENTRIES[160])
    put("VARIANCE", TRINO_DORIS_HAZARD_ENTRIES[84])
    put("VAR_POP", TRINO_DORIS_HAZARD_ENTRIES[81])
    put("VAR_SAMP", TRINO_DORIS_HAZARD_ENTRIES[82])
    put("WEEK", TRINO_DORIS_HAZARD_ENTRIES[111])
    put("WIDTH_BUCKET", TRINO_DORIS_HAZARD_ENTRIES[156])
    put("YEAR", TRINO_DORIS_HAZARD_ENTRIES[109])
    put("YEAR_OF_WEEK", TRINO_DORIS_HAZARD_ENTRIES[118])
    put("YOW", TRINO_DORIS_HAZARD_ENTRIES[117])
}

/** doris->trino lookup: 166 keys (Doris-side names) over 166 entries. */
internal val DORIS_TO_TRINO_HAZARDS: Map<String, FunctionHazard> = buildMap {
    put("ABS", TRINO_DORIS_HAZARD_ENTRIES[16])
    put("ACOS", TRINO_DORIS_HAZARD_ENTRIES[21])
    put("ANY_VALUE", TRINO_DORIS_HAZARD_ENTRIES[73])
    put("ARRAYS_OVERLAP", TRINO_DORIS_HAZARD_ENTRIES[134])
    put("ARRAY_AGG", TRINO_DORIS_HAZARD_ENTRIES[89])
    put("ARRAY_CONTAINS", TRINO_DORIS_HAZARD_ENTRIES[137])
    put("ARRAY_DISTINCT", TRINO_DORIS_HAZARD_ENTRIES[125])
    put("ARRAY_EXCEPT", TRINO_DORIS_HAZARD_ENTRIES[131])
    put("ARRAY_FIRST", TRINO_DORIS_HAZARD_ENTRIES[126])
    put("ARRAY_INTERSECT", TRINO_DORIS_HAZARD_ENTRIES[128])
    put("ARRAY_JOIN", TRINO_DORIS_HAZARD_ENTRIES[138])
    put("ARRAY_LAST", TRINO_DORIS_HAZARD_ENTRIES[127])
    put("ARRAY_MAX", TRINO_DORIS_HAZARD_ENTRIES[139])
    put("ARRAY_MIN", TRINO_DORIS_HAZARD_ENTRIES[140])
    put("ARRAY_POSITION", TRINO_DORIS_HAZARD_ENTRIES[129])
    put("ARRAY_REMOVE", TRINO_DORIS_HAZARD_ENTRIES[132])
    put("ARRAY_SIZE", TRINO_DORIS_HAZARD_ENTRIES[135])
    put("ARRAY_SORT", TRINO_DORIS_HAZARD_ENTRIES[130])
    put("ARRAY_UNION", TRINO_DORIS_HAZARD_ENTRIES[133])
    put("ASCII", TRINO_DORIS_HAZARD_ENTRIES[8])
    put("ASIN", TRINO_DORIS_HAZARD_ENTRIES[22])
    put("ATAN", TRINO_DORIS_HAZARD_ENTRIES[30])
    put("ATAN2", TRINO_DORIS_HAZARD_ENTRIES[31])
    put("AVG", TRINO_DORIS_HAZARD_ENTRIES[66])
    put("BIT_COUNT", TRINO_DORIS_HAZARD_ENTRIES[12])
    put("BOOL_AND", TRINO_DORIS_HAZARD_ENTRIES[71])
    put("BOOL_OR", TRINO_DORIS_HAZARD_ENTRIES[72])
    put("CARDINALITY", TRINO_DORIS_HAZARD_ENTRIES[146])
    put("CBRT", TRINO_DORIS_HAZARD_ENTRIES[29])
    put("CEIL", TRINO_DORIS_HAZARD_ENTRIES[38])
    put("CEILING", TRINO_DORIS_HAZARD_ENTRIES[39])
    put("COALESCE", TRINO_DORIS_HAZARD_ENTRIES[18])
    put("CONCAT", TRINO_DORIS_HAZARD_ENTRIES[2])
    put("CONCAT_WS", TRINO_DORIS_HAZARD_ENTRIES[64])
    put("CORR", TRINO_DORIS_HAZARD_ENTRIES[76])
    put("COS", TRINO_DORIS_HAZARD_ENTRIES[32])
    put("COSH", TRINO_DORIS_HAZARD_ENTRIES[33])
    put("COSINE_DISTANCE", TRINO_DORIS_HAZARD_ENTRIES[145])
    put("COSINE_SIMILARITY", TRINO_DORIS_HAZARD_ENTRIES[144])
    put("COUNT", TRINO_DORIS_HAZARD_ENTRIES[68])
    put("COVAR_POP", TRINO_DORIS_HAZARD_ENTRIES[77])
    put("COVAR_SAMP", TRINO_DORIS_HAZARD_ENTRIES[78])
    put("CRC32", TRINO_DORIS_HAZARD_ENTRIES[151])
    put("CUME_DIST", TRINO_DORIS_HAZARD_ENTRIES[102])
    put("CURRENT_DATE", TRINO_DORIS_HAZARD_ENTRIES[123])
    put("DATE", TRINO_DORIS_HAZARD_ENTRIES[106])
    put("DATE_ADD", TRINO_DORIS_HAZARD_ENTRIES[103])
    put("DATE_FORMAT", TRINO_DORIS_HAZARD_ENTRIES[104])
    put("DATE_TRUNC", TRINO_DORIS_HAZARD_ENTRIES[105])
    put("DAY", TRINO_DORIS_HAZARD_ENTRIES[107])
    put("DAYOFWEEK", TRINO_DORIS_HAZARD_ENTRIES[115])
    put("DAYOFYEAR", TRINO_DORIS_HAZARD_ENTRIES[116])
    put("DEGREES", TRINO_DORIS_HAZARD_ENTRIES[41])
    put("DENSE_RANK", TRINO_DORIS_HAZARD_ENTRIES[94])
    put("E", TRINO_DORIS_HAZARD_ENTRIES[150])
    put("ELEMENT_AT", TRINO_DORIS_HAZARD_ENTRIES[136])
    put("EXP", TRINO_DORIS_HAZARD_ENTRIES[28])
    put("FIRST_VALUE", TRINO_DORIS_HAZARD_ENTRIES[98])
    put("FLOOR", TRINO_DORIS_HAZARD_ENTRIES[40])
    put("FMOD", TRINO_DORIS_HAZARD_ENTRIES[13])
    put("FORMAT_NUMBER", TRINO_DORIS_HAZARD_ENTRIES[49])
    put("FROM_BASE64", TRINO_DORIS_HAZARD_ENTRIES[57])
    put("FROM_ISO8601_DATE", TRINO_DORIS_HAZARD_ENTRIES[120])
    put("FROM_UNIXTIME", TRINO_DORIS_HAZARD_ENTRIES[119])
    put("GREATEST", TRINO_DORIS_HAZARD_ENTRIES[3])
    put("HAMMING_DISTANCE", TRINO_DORIS_HAZARD_ENTRIES[55])
    put("HEX", TRINO_DORIS_HAZARD_ENTRIES[47])
    put("HISTOGRAM", TRINO_DORIS_HAZARD_ENTRIES[91])
    put("HOUR", TRINO_DORIS_HAZARD_ENTRIES[114])
    put("JSON_EXTRACT", TRINO_DORIS_HAZARD_ENTRIES[147])
    put("JSON_FORMAT", TRINO_DORIS_HAZARD_ENTRIES[149])
    put("JSON_PARSE", TRINO_DORIS_HAZARD_ENTRIES[148])
    put("KURTOSIS", TRINO_DORIS_HAZARD_ENTRIES[86])
    put("LAG", TRINO_DORIS_HAZARD_ENTRIES[96])
    put("LAST_DAY", TRINO_DORIS_HAZARD_ENTRIES[124])
    put("LAST_VALUE", TRINO_DORIS_HAZARD_ENTRIES[99])
    put("LEAD", TRINO_DORIS_HAZARD_ENTRIES[97])
    put("LEAST", TRINO_DORIS_HAZARD_ENTRIES[4])
    put("LENGTH", TRINO_DORIS_HAZARD_ENTRIES[15])
    put("LEVENSHTEIN", TRINO_DORIS_HAZARD_ENTRIES[54])
    put("LN", TRINO_DORIS_HAZARD_ENTRIES[23])
    put("LOG", TRINO_DORIS_HAZARD_ENTRIES[27])
    put("LOG10", TRINO_DORIS_HAZARD_ENTRIES[26])
    put("LOG2", TRINO_DORIS_HAZARD_ENTRIES[25])
    put("LOWER", TRINO_DORIS_HAZARD_ENTRIES[0])
    put("LPAD", TRINO_DORIS_HAZARD_ENTRIES[59])
    put("LTRIM", TRINO_DORIS_HAZARD_ENTRIES[10])
    put("MAP", TRINO_DORIS_HAZARD_ENTRIES[161])
    put("MAP_AGG", TRINO_DORIS_HAZARD_ENTRIES[90])
    put("MAP_ENTRIES", TRINO_DORIS_HAZARD_ENTRIES[164])
    put("MAP_KEYS", TRINO_DORIS_HAZARD_ENTRIES[162])
    put("MAP_VALUES", TRINO_DORIS_HAZARD_ENTRIES[163])
    put("MAX", TRINO_DORIS_HAZARD_ENTRIES[69])
    put("MAX_BY", TRINO_DORIS_HAZARD_ENTRIES[74])
    put("MD5", TRINO_DORIS_HAZARD_ENTRIES[20])
    put("MIN", TRINO_DORIS_HAZARD_ENTRIES[70])
    put("MINUTE", TRINO_DORIS_HAZARD_ENTRIES[112])
    put("MIN_BY", TRINO_DORIS_HAZARD_ENTRIES[75])
    put("MOD", TRINO_DORIS_HAZARD_ENTRIES[17])
    put("MONTH", TRINO_DORIS_HAZARD_ENTRIES[108])
    put("NORMAL_CDF", TRINO_DORIS_HAZARD_ENTRIES[152])
    put("NOW", TRINO_DORIS_HAZARD_ENTRIES[122])
    put("NTH_VALUE", TRINO_DORIS_HAZARD_ENTRIES[100])
    put("NTILE", TRINO_DORIS_HAZARD_ENTRIES[95])
    put("NULLIF", TRINO_DORIS_HAZARD_ENTRIES[19])
    put("PARSE_DATA_SIZE", TRINO_DORIS_HAZARD_ENTRIES[157])
    put("PERCENT_RANK", TRINO_DORIS_HAZARD_ENTRIES[101])
    put("PI", TRINO_DORIS_HAZARD_ENTRIES[43])
    put("POW", TRINO_DORIS_HAZARD_ENTRIES[45])
    put("POWER", TRINO_DORIS_HAZARD_ENTRIES[46])
    put("QUARTER", TRINO_DORIS_HAZARD_ENTRIES[110])
    put("RADIANS", TRINO_DORIS_HAZARD_ENTRIES[42])
    put("RAND", TRINO_DORIS_HAZARD_ENTRIES[158])
    put("RANDOM", TRINO_DORIS_HAZARD_ENTRIES[159])
    put("RANK", TRINO_DORIS_HAZARD_ENTRIES[93])
    put("REGEXP_COUNT", TRINO_DORIS_HAZARD_ENTRIES[153])
    put("REGEXP_EXTRACT", TRINO_DORIS_HAZARD_ENTRIES[154])
    put("REGEXP_EXTRACT_ALL", TRINO_DORIS_HAZARD_ENTRIES[14])
    put("REGEXP_REPLACE", TRINO_DORIS_HAZARD_ENTRIES[7])
    put("REGR_INTERCEPT", TRINO_DORIS_HAZARD_ENTRIES[87])
    put("REGR_SLOPE", TRINO_DORIS_HAZARD_ENTRIES[88])
    put("REPEAT", TRINO_DORIS_HAZARD_ENTRIES[61])
    put("REPLACE", TRINO_DORIS_HAZARD_ENTRIES[53])
    put("REVERSE", TRINO_DORIS_HAZARD_ENTRIES[6])
    put("ROW_NUMBER", TRINO_DORIS_HAZARD_ENTRIES[92])
    put("RPAD", TRINO_DORIS_HAZARD_ENTRIES[60])
    put("RTRIM", TRINO_DORIS_HAZARD_ENTRIES[11])
    put("SECOND", TRINO_DORIS_HAZARD_ENTRIES[113])
    put("SEQUENCE", TRINO_DORIS_HAZARD_ENTRIES[143])
    put("SHA1", TRINO_DORIS_HAZARD_ENTRIES[52])
    put("SHUFFLE", TRINO_DORIS_HAZARD_ENTRIES[142])
    put("SIGN", TRINO_DORIS_HAZARD_ENTRIES[44])
    put("SIN", TRINO_DORIS_HAZARD_ENTRIES[34])
    put("SINH", TRINO_DORIS_HAZARD_ENTRIES[35])
    put("SKEWNESS", TRINO_DORIS_HAZARD_ENTRIES[85])
    put("SOUNDEX", TRINO_DORIS_HAZARD_ENTRIES[56])
    put("SPLIT_BY_STRING", TRINO_DORIS_HAZARD_ENTRIES[141])
    put("SPLIT_PART", TRINO_DORIS_HAZARD_ENTRIES[5])
    put("SQRT", TRINO_DORIS_HAZARD_ENTRIES[24])
    put("STARTS_WITH", TRINO_DORIS_HAZARD_ENTRIES[51])
    put("STDDEV", TRINO_DORIS_HAZARD_ENTRIES[83])
    put("STDDEV_POP", TRINO_DORIS_HAZARD_ENTRIES[79])
    put("STDDEV_SAMP", TRINO_DORIS_HAZARD_ENTRIES[80])
    put("SUBSTR", TRINO_DORIS_HAZARD_ENTRIES[65])
    put("SUM", TRINO_DORIS_HAZARD_ENTRIES[67])
    put("TAN", TRINO_DORIS_HAZARD_ENTRIES[36])
    put("TANH", TRINO_DORIS_HAZARD_ENTRIES[37])
    put("TO_BASE64", TRINO_DORIS_HAZARD_ENTRIES[58])
    put("TO_ISO8601", TRINO_DORIS_HAZARD_ENTRIES[121])
    put("TRANSLATE", TRINO_DORIS_HAZARD_ENTRIES[62])
    put("TRIM", TRINO_DORIS_HAZARD_ENTRIES[9])
    put("TRUNCATE", TRINO_DORIS_HAZARD_ENTRIES[155])
    put("UNHEX", TRINO_DORIS_HAZARD_ENTRIES[48])
    put("UNNEST", TRINO_DORIS_HAZARD_ENTRIES[165])
    put("UPPER", TRINO_DORIS_HAZARD_ENTRIES[1])
    put("URL_DECODE", TRINO_DORIS_HAZARD_ENTRIES[63])
    put("URL_ENCODE", TRINO_DORIS_HAZARD_ENTRIES[50])
    put("UUID", TRINO_DORIS_HAZARD_ENTRIES[160])
    put("VARIANCE", TRINO_DORIS_HAZARD_ENTRIES[84])
    put("VAR_POP", TRINO_DORIS_HAZARD_ENTRIES[81])
    put("VAR_SAMP", TRINO_DORIS_HAZARD_ENTRIES[82])
    put("WEEK", TRINO_DORIS_HAZARD_ENTRIES[111])
    put("WIDTH_BUCKET", TRINO_DORIS_HAZARD_ENTRIES[156])
    put("YEAR", TRINO_DORIS_HAZARD_ENTRIES[109])
    put("YEARWEEK", TRINO_DORIS_HAZARD_ENTRIES[117])
    put("YEAR_OF_WEEK", TRINO_DORIS_HAZARD_ENTRIES[118])
}
