package dev.brikk.house.sql.dialects

import dev.brikk.house.sql.ast.Expression
import dev.brikk.house.sql.ast.GenerateSeries
import dev.brikk.house.sql.generator.Generator
import dev.brikk.house.sql.metadata.FunctionCatalog
import dev.brikk.house.sql.metadata.STARROCKS_FUNCTION_CATALOG
import dev.brikk.house.sql.parser.ErrorLevel
import dev.brikk.house.sql.parser.Parser
import dev.brikk.house.sql.parser.StarrocksTokenizerTables
import dev.brikk.house.sql.parser.TokenizerConfig

/**
 * Port of sqlglot's StarRocks dialect umbrella (reference/sqlglot/sqlglot/dialects/starrocks.py
 * class StarRocks(MySQL)). StarRocks extends MySQL (NOT Doris) — see the upstream class
 * hierarchy. Tokenizer tables were generated by tools/gen_tokenizer_tables.py
 * (StarrocksTokenizerTables); the parser and generator subclasses live in
 * StarrocksParser.kt / StarrocksGenerator.kt.
 *
 * Pinned to the current StarRocks 4.1.x release line (see vendor/README.md and
 * brikk-sql-metadata GeneratedStarrocksFunctionCatalog provenance).
 */
// sqlglot: dialects.starrocks.StarRocks
class StarrocksDialect : Dialect() {

    override val name: String get() = "starrocks"

    // sqlglot: StarRocks(MySQL) inherits MySQL.EXPRESSION_METADATA
    override val expressionMetadata get() = dev.brikk.house.sql.ast.GeneratedTypingMetadata.MYSQL

    // sqlglot: StarRocks inherits MySQL.NORMALIZATION_STRATEGY (CASE_SENSITIVE)
    override val normalizationStrategy get() = NormalizationStrategy.CASE_SENSITIVE

    // Version-pinned StarRocks builtin function registry (see brikk-sql-metadata).
    override val functionCatalog: FunctionCatalog get() = STARROCKS_FUNCTION_CATALOG

    override val tokenizerConfig: TokenizerConfig get() = StarrocksTokenizerTables.CONFIG

    // sqlglot: StarRocks.TIME_MAPPING (inherited from MySQL)
    override val timeMapping: Map<String, String> get() = MysqlDialect.TIME_MAPPING

    // sqlglot: StarRocks.DEFAULT_FUNCTIONS_COLUMN_NAMES = {exp.GenerateSeries: "generate_series"}
    override val defaultFunctionsColumnNames:
        Map<kotlin.reflect.KClass<out Expression>, List<String>>
        get() = mapOf(GenerateSeries::class to listOf("generate_series"))

    override fun parser(errorLevel: ErrorLevel?): Parser =
        StarrocksParser(errorLevel = errorLevel, tokenizerConfig = tokenizerConfig)

    override fun generator(pretty: Boolean, sourceDialect: String?): Generator =
        StarrocksGenerator(pretty = pretty, tokenizerConfig = tokenizerConfig, sourceDialect = sourceDialect)
}
