package dev.brikk.house.sql.ast

import kotlin.String
import kotlin.collections.Map

/**
 * sqlglot: datatypes.DataType.Type (member order preserved; value strings can
 * differ from member names, e.g. USERDEFINED = "USER-DEFINED").
 *
 * GENERATED by tools/gen_ast_nodes.py from sqlglot v30.12.0-44-g93d16591 — do not edit by hand.
 */
enum class DType(val value: kotlin.String) {
    ARRAY("ARRAY"),
    AGGREGATEFUNCTION("AGGREGATEFUNCTION"),
    SIMPLEAGGREGATEFUNCTION("SIMPLEAGGREGATEFUNCTION"),
    BIGDECIMAL("BIGDECIMAL"),
    BIGINT("BIGINT"),
    BIGNUM("BIGNUM"),
    BIGSERIAL("BIGSERIAL"),
    BINARY("BINARY"),
    BIT("BIT"),
    BLOB("BLOB"),
    BOOLEAN("BOOLEAN"),
    BPCHAR("BPCHAR"),
    CHAR("CHAR"),
    CHARACTER_SET("CHARACTER_SET"),
    DATE("DATE"),
    DATE32("DATE32"),
    DATEMULTIRANGE("DATEMULTIRANGE"),
    DATERANGE("DATERANGE"),
    DATETIME("DATETIME"),
    DATETIME2("DATETIME2"),
    DATETIME64("DATETIME64"),
    DECIMAL("DECIMAL"),
    DECIMAL32("DECIMAL32"),
    DECIMAL64("DECIMAL64"),
    DECIMAL128("DECIMAL128"),
    DECIMAL256("DECIMAL256"),
    DECFLOAT("DECFLOAT"),
    DOUBLE("DOUBLE"),
    DYNAMIC("DYNAMIC"),
    ENUM("ENUM"),
    ENUM8("ENUM8"),
    ENUM16("ENUM16"),
    FILE("FILE"),
    FIXEDSTRING("FIXEDSTRING"),
    FLOAT("FLOAT"),
    GEOGRAPHY("GEOGRAPHY"),
    GEOGRAPHYPOINT("GEOGRAPHYPOINT"),
    GEOMETRY("GEOMETRY"),
    POINT("POINT"),
    RING("RING"),
    LINESTRING("LINESTRING"),
    MULTILINESTRING("MULTILINESTRING"),
    POLYGON("POLYGON"),
    MULTIPOLYGON("MULTIPOLYGON"),
    HLLSKETCH("HLLSKETCH"),
    HSTORE("HSTORE"),
    IMAGE("IMAGE"),
    INET("INET"),
    INT("INT"),
    INT128("INT128"),
    INT256("INT256"),
    INT4MULTIRANGE("INT4MULTIRANGE"),
    INT4RANGE("INT4RANGE"),
    INT8MULTIRANGE("INT8MULTIRANGE"),
    INT8RANGE("INT8RANGE"),
    INTERVAL("INTERVAL"),
    IPADDRESS("IPADDRESS"),
    IPPREFIX("IPPREFIX"),
    IPV4("IPV4"),
    IPV6("IPV6"),
    JSON("JSON"),
    JSONB("JSONB"),
    LIST("LIST"),
    LONGBLOB("LONGBLOB"),
    LONGTEXT("LONGTEXT"),
    LOWCARDINALITY("LOWCARDINALITY"),
    MAP("MAP"),
    MEDIUMBLOB("MEDIUMBLOB"),
    MEDIUMINT("MEDIUMINT"),
    MEDIUMTEXT("MEDIUMTEXT"),
    MONEY("MONEY"),
    NAME("NAME"),
    NCHAR("NCHAR"),
    NESTED("NESTED"),
    NOTHING("NOTHING"),
    NULL("NULL"),
    NUMMULTIRANGE("NUMMULTIRANGE"),
    NUMRANGE("NUMRANGE"),
    NVARCHAR("NVARCHAR"),
    OBJECT("OBJECT"),
    RANGE("RANGE"),
    ROWVERSION("ROWVERSION"),
    SERIAL("SERIAL"),
    SET("SET"),
    SMALLDATETIME("SMALLDATETIME"),
    SMALLINT("SMALLINT"),
    SMALLMONEY("SMALLMONEY"),
    SMALLSERIAL("SMALLSERIAL"),
    STRUCT("STRUCT"),
    SUPER("SUPER"),
    TEXT("TEXT"),
    TINYBLOB("TINYBLOB"),
    TINYTEXT("TINYTEXT"),
    TIME("TIME"),
    TIMETZ("TIMETZ"),
    TIME_NS("TIME_NS"),
    TIMESTAMP("TIMESTAMP"),
    TIMESTAMPNTZ("TIMESTAMPNTZ"),
    TIMESTAMPLTZ("TIMESTAMPLTZ"),
    TIMESTAMPTZ("TIMESTAMPTZ"),
    TIMESTAMP_S("TIMESTAMP_S"),
    TIMESTAMP_MS("TIMESTAMP_MS"),
    TIMESTAMP_NS("TIMESTAMP_NS"),
    TINYINT("TINYINT"),
    TSMULTIRANGE("TSMULTIRANGE"),
    TSRANGE("TSRANGE"),
    TSTZMULTIRANGE("TSTZMULTIRANGE"),
    TSTZRANGE("TSTZRANGE"),
    UBIGINT("UBIGINT"),
    UINT("UINT"),
    UINT128("UINT128"),
    UINT256("UINT256"),
    UMEDIUMINT("UMEDIUMINT"),
    UDECIMAL("UDECIMAL"),
    UDOUBLE("UDOUBLE"),
    UNION("UNION"),
    UNKNOWN("UNKNOWN"),
    USERDEFINED("USER-DEFINED"),
    USMALLINT("USMALLINT"),
    UTINYINT("UTINYINT"),
    UUID("UUID"),
    VARBINARY("VARBINARY"),
    VARCHAR("VARCHAR"),
    VARIANT("VARIANT"),
    VECTOR("VECTOR"),
    XML("XML"),
    YEAR("YEAR"),
    TDIGEST("TDIGEST"),
    ;

    companion object {
        private val BY_VALUE = entries.associateBy { it.value }

        fun fromValue(value: kotlin.String): DType =
            BY_VALUE[value]
                ?: throw IllegalArgumentException("Unknown DataType.Type value: $value")
    }
}

// sqlglot: datatypes.DataType(Expression) — is_data_type. The "this" arg holds a DType.
open class DataType(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES
    override val isDataType get() = true

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to false, "nested" to false, "values" to false,
            "kind" to false, "nullable" to false, "collate" to false,
        )
    }
}

// sqlglot: datatypes.DataTypeParam(Expression) — precision/scale/size args of a DataType
class DataTypeParam(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    // sqlglot: DataTypeParam.name (delegates to `this`)
    override val name: String get() = (thisArg as Expression).name

    companion object {
        private val ARG_TYPES = argTypesOf("this" to true, "expression" to false)
    }
}
