// GENERATED FILE — DO NOT EDIT.
// Generated by tools/gen_ast_nodes.py from sqlglot v30.12.0-44-g93d16591.
// sqlglot is MIT-licensed, copyright Toby Mao. See reference/sqlglot/LICENSE.
package dev.brikk.house.sql.ast

// sqlglot.expressions.dml: 15 generated classes.

// sqlglot: dml.Copy(Expression, DML)
class Copy(initArgs: Args = emptyMap()) : Expression(initArgs), DML {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "kind" to true, "files" to false, "credentials" to false,
            "format" to false, "params" to false,
        )
    }
}

// sqlglot: dml.CopyParameter(Expression)
class CopyParameter(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to false, "expressions" to false,
        )
    }
}

// sqlglot: dml.Credentials(Expression)
class Credentials(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "credentials" to false, "encryption" to false, "storage" to false, "iam_role" to false,
            "region" to false,
        )
    }
}

// sqlglot: dml.Delete(Expression, DML)
class Delete(initArgs: Args = emptyMap()) : Expression(initArgs), DML {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "with_" to false, "this" to false, "using" to false, "where" to false,
            "returning" to false, "order" to false, "limit" to false, "tables" to false,
            "cluster" to false, "hint" to false,
        )
    }
}

// sqlglot: dml.Directory(Expression)
class Directory(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "local" to false, "row_format" to false,
        )
    }
}

// sqlglot: dml.DirectoryStage(Expression)
class DirectoryStage(initArgs: Args = emptyMap()) : Expression(initArgs)

// sqlglot: dml.Export(Expression)
class Export(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "connection" to false, "options" to true,
        )
    }
}

// sqlglot: dml.Insert(Expression, DDL, DML)
class Insert(initArgs: Args = emptyMap()) : Expression(initArgs), DDL, DML {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "hint" to false, "with_" to false, "is_function" to false, "this" to false,
            "expression" to false, "conflict" to false, "returning" to false, "overwrite" to false,
            "exists" to false, "alternative" to false, "where" to false, "ignore" to false,
            "by_name" to false, "stored" to false, "partition" to false, "settings" to false,
            "source" to false, "default" to false,
        )
    }
}

// sqlglot: dml.LoadData(Expression)
class LoadData(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "local" to false, "overwrite" to false, "temp" to false,
            "inpath" to false, "files" to false, "partition" to false, "input_format" to false,
            "serde" to false,
        )
    }
}

// sqlglot: dml.Merge(Expression, DML)
class Merge(initArgs: Args = emptyMap()) : Expression(initArgs), DML {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "using" to true, "on" to false, "using_cond" to false, "whens" to true,
            "with_" to false, "returning" to false,
        )
    }
}

// sqlglot: dml.OnConflict(Expression)
class OnConflict(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "duplicate" to false, "expressions" to false, "action" to false,
            "conflict_keys" to false, "index_predicate" to false, "constraint" to false,
            "where" to false,
        )
    }
}

// sqlglot: dml.Returning(Expression)
class Returning(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true, "into" to false,
        )
    }
}

// sqlglot: dml.Update(Expression, DML)
class Update(initArgs: Args = emptyMap()) : Expression(initArgs), DML {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "with_" to false, "this" to false, "expressions" to false, "from_" to false,
            "where" to false, "returning" to false, "order" to false, "limit" to false,
            "options" to false, "hint" to false,
        )
    }
}

// sqlglot: dml.When(Expression)
class When(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "matched" to true, "source" to false, "condition" to false, "then" to true,
        )
    }
}

// sqlglot: dml.Whens(Expression)
class Whens(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}
