// GENERATED FILE — DO NOT EDIT.
// Generated by tools/gen_ast_nodes.py from sqlglot v30.12.0-44-g93d16591.
// sqlglot is MIT-licensed, copyright Toby Mao. See reference/sqlglot/LICENSE.
package dev.brikk.house.sql.ast

// sqlglot.expressions.properties: 126 generated classes.

// sqlglot: properties.AllowedValuesProperty(Expression)
class AllowedValuesProperty(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.GrantPrincipal(Expression)
class GrantPrincipal(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "kind" to false,
        )
    }
}

// sqlglot: properties.GrantPrivilege(Expression)
class GrantPrivilege(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to false,
        )
    }
}

// sqlglot: properties.PartitionBoundSpec(Expression)
class PartitionBoundSpec(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "expression" to false, "from_expressions" to false,
            "to_expressions" to false,
        )
    }
}

// sqlglot: properties.PartitionByRangePropertyDynamic(Expression)
class PartitionByRangePropertyDynamic(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "start" to true, "end" to true, "every" to true,
        )
    }
}

// sqlglot: properties.PartitionList(Expression)
class PartitionList(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to true,
        )
    }
}

// sqlglot: properties.Properties(Expression)
class Properties(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.Property(Expression)
open class Property(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "value" to true,
        )
    }
}

// sqlglot: properties.QueryTransform(Expression)
class QueryTransform(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true, "command_script" to true, "schema" to false,
            "row_format_before" to false, "record_writer" to false, "row_format_after" to false,
            "record_reader" to false,
        )
    }
}

// sqlglot: properties.RollupIndex(Expression)
class RollupIndex(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to true, "from_index" to false, "properties" to false,
        )
    }
}

// sqlglot: properties.SemanticView(Expression)
class SemanticView(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "metrics" to false, "dimensions" to false, "facts" to false,
            "where" to false,
        )
    }
}

// sqlglot: properties.AlgorithmProperty(Property)
class AlgorithmProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.ApiProperty(Property)
class ApiProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.ApplicationProperty(Property)
class ApplicationProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.AutoIncrementProperty(Property)
class AutoIncrementProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.AutoRefreshProperty(Property)
class AutoRefreshProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.BackupProperty(Property)
class BackupProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.BlockCompressionProperty(Property)
class BlockCompressionProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "autotemp" to false, "always" to false, "default" to false, "manual" to false,
            "never" to false,
        )
    }
}

// sqlglot: properties.BuildProperty(Property)
class BuildProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.CalledOnNullInputProperty(Property)
class CalledOnNullInputProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.CatalogProperty(Property)
class CatalogProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.CharacterSetProperty(Property)
class CharacterSetProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "default" to true,
        )
    }
}

// sqlglot: properties.ChecksumProperty(Property)
class ChecksumProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "on" to false, "default" to false,
        )
    }
}

// sqlglot: properties.ClusterProperty(Property)
class ClusterProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "expressions" to false,
        )
    }
}

// sqlglot: properties.ClusteredByProperty(Property)
class ClusteredByProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true, "sorted_by" to false, "buckets" to true,
        )
    }
}

// sqlglot: properties.CollateProperty(Property)
class CollateProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "default" to false,
        )
    }
}

// sqlglot: properties.ComputeProperty(Property)
class ComputeProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.CopyGrantsProperty(Property)
class CopyGrantsProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.CredentialsProperty(Property)
class CredentialsProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.DataBlocksizeProperty(Property)
class DataBlocksizeProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "size" to false, "units" to false, "minimum" to false, "maximum" to false,
            "default" to false,
        )
    }
}

// sqlglot: properties.DataDeletionProperty(Property)
class DataDeletionProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "on" to true, "filter_column" to false, "retention_period" to false,
        )
    }
}

// sqlglot: properties.DatabaseProperty(Property)
class DatabaseProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.DefinerProperty(Property)
class DefinerProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.DictProperty(Property)
class DictProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "kind" to true, "settings" to false,
        )
    }
}

// sqlglot: properties.DictRange(Property)
class DictRange(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "min" to true, "max" to true,
        )
    }
}

// sqlglot: properties.DictSubProperty(Property)
class DictSubProperty(initArgs: Args = emptyMap()) : Property(initArgs)

// sqlglot: properties.DistKeyProperty(Property)
class DistKeyProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.DistStyleProperty(Property)
class DistStyleProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.DistributedByProperty(Property)
class DistributedByProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to false, "kind" to true, "buckets" to false, "order" to false,
        )
    }
}

// sqlglot: properties.DuplicateKeyProperty(Property)
class DuplicateKeyProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.DynamicProperty(Property)
class DynamicProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.EmptyProperty(Property)
class EmptyProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.EncodeProperty(Property)
class EncodeProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "properties" to false, "key" to false,
        )
    }
}

// sqlglot: properties.EngineProperty(Property)
class EngineProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.EnviromentProperty(Property)
class EnviromentProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.ExecuteAsProperty(Property)
class ExecuteAsProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.ExternalProperty(Property)
class ExternalProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false,
        )
    }
}

// sqlglot: properties.FallbackProperty(Property)
class FallbackProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "no" to true, "protection" to false,
        )
    }
}

// sqlglot: properties.FileFormatProperty(Property)
class FileFormatProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "expressions" to false, "hive_format" to false,
        )
    }
}

// sqlglot: properties.ForceProperty(Property)
class ForceProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.FreespaceProperty(Property)
class FreespaceProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "percent" to false,
        )
    }
}

// sqlglot: properties.GlobalProperty(Property)
class GlobalProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.HandlerProperty(Property)
class HandlerProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.HeapProperty(Property)
class HeapProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.HybridProperty(Property)
class HybridProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.IcebergProperty(Property)
class IcebergProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.IncludeProperty(Property)
class IncludeProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "alias" to false, "column_def" to false,
        )
    }
}

// sqlglot: properties.InheritsProperty(Property)
class InheritsProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.InputModelProperty(Property)
class InputModelProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.IsolatedLoadingProperty(Property)
class IsolatedLoadingProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "no" to false, "concurrent" to false, "target" to false,
        )
    }
}

// sqlglot: properties.JournalProperty(Property)
class JournalProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "no" to false, "dual" to false, "before" to false, "local" to false, "after" to false,
        )
    }
}

// sqlglot: properties.LanguageProperty(Property)
class LanguageProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.LikeProperty(Property)
class LikeProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to false,
        )
    }
}

// sqlglot: properties.LocationProperty(Property)
class LocationProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.LockProperty(Property)
class LockProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.LockingProperty(Property)
class LockingProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "kind" to true, "for_or_in" to false, "lock_type" to true,
            "override" to false,
        )
    }
}

// sqlglot: properties.LogProperty(Property)
class LogProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "no" to true,
        )
    }
}

// sqlglot: properties.MaskingProperty(Property)
class MaskingProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.MaterializedProperty(Property)
class MaterializedProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false,
        )
    }
}

// sqlglot: properties.MergeBlockRatioProperty(Property)
class MergeBlockRatioProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "no" to false, "default" to false, "percent" to false,
        )
    }
}

// sqlglot: properties.ModuleProperty(Property)
class ModuleProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to false,
        )
    }
}

// sqlglot: properties.NetworkProperty(Property)
class NetworkProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.NoPrimaryIndexProperty(Property)
class NoPrimaryIndexProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.OnCluster(Property)
class OnCluster(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.OnCommitProperty(Property)
class OnCommitProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "delete" to false,
        )
    }
}

// sqlglot: properties.OnProperty(Property)
class OnProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.OutputModelProperty(Property)
class OutputModelProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.ParameterStyleProperty(Property)
class ParameterStyleProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.PartitionByListProperty(Property)
class PartitionByListProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "partition_expressions" to true, "create_expressions" to true,
        )
    }
}

// sqlglot: properties.PartitionByRangeProperty(Property)
class PartitionByRangeProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "partition_expressions" to true, "create_expressions" to true,
        )
    }
}

// sqlglot: properties.PartitionByTruncate(Property)
class PartitionByTruncate(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: properties.PartitionedByBucket(Property)
class PartitionedByBucket(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: properties.PartitionedByProperty(Property)
class PartitionedByProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.PartitionedOfProperty(Property)
class PartitionedOfProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: properties.RefreshTriggerProperty(Property)
class RefreshTriggerProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "method" to false, "kind" to false, "every" to false, "unit" to false,
            "starts" to false,
        )
    }
}

// sqlglot: properties.RemoteWithConnectionModelProperty(Property)
class RemoteWithConnectionModelProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.ReturnsProperty(Property)
class ReturnsProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "is_table" to false, "table" to false, "null" to false,
        )
    }
}

// sqlglot: properties.RollupProperty(Property)
class RollupProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.RowAccessProperty(Property)
class RowAccessProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "expressions" to false,
        )
    }
}

// sqlglot: properties.RowFormatDelimitedProperty(Property)
class RowFormatDelimitedProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "fields" to false, "escaped" to false, "collection_items" to false,
            "map_keys" to false, "lines" to false, "null" to false, "serde" to false,
        )
    }
}

// sqlglot: properties.RowFormatProperty(Property)
class RowFormatProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.RowFormatSerdeProperty(Property)
class RowFormatSerdeProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "serde_properties" to false,
        )
    }
}

// sqlglot: properties.SampleProperty(Property)
class SampleProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.SchemaCommentProperty(Property)
class SchemaCommentProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.SecureProperty(Property)
class SecureProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.SecurityIntegrationProperty(Property)
class SecurityIntegrationProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.SerdeProperties(Property)
class SerdeProperties(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true, "with_" to false,
        )
    }
}

// sqlglot: properties.SetConfigProperty(Property)
class SetConfigProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.SetProperty(Property)
class SetProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "multi" to true,
        )
    }
}

// sqlglot: properties.SettingsProperty(Property)
class SettingsProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.SharingProperty(Property)
class SharingProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false,
        )
    }
}

// sqlglot: properties.SortKeyProperty(Property)
class SortKeyProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "compound" to false,
        )
    }
}

// sqlglot: properties.SqlReadWriteProperty(Property)
class SqlReadWriteProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.SqlSecurityProperty(Property)
class SqlSecurityProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.StabilityProperty(Property)
class StabilityProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.StorageHandlerProperty(Property)
class StorageHandlerProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.StreamingTableProperty(Property)
class StreamingTableProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.StrictProperty(Property)
class StrictProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.Tags(Property, ColumnConstraintKind)
class Tags(initArgs: Args = emptyMap()) : Property(initArgs), ColumnConstraintKind {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.TemporaryProperty(Property)
class TemporaryProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false,
        )
    }
}

// sqlglot: properties.ToTableProperty(Property)
class ToTableProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.TransformModelProperty(Property)
class TransformModelProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.TransientProperty(Property)
class TransientProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false,
        )
    }
}

// sqlglot: properties.UniqueKeyProperty(Property)
class UniqueKeyProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.UnloggedProperty(Property)
class UnloggedProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.UsingProperty(Property)
class UsingProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "kind" to true,
        )
    }
}

// sqlglot: properties.UsingTemplateProperty(Property)
class UsingTemplateProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.UuidProperty(Property)
class UuidProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.ViewAttributeProperty(Property)
class ViewAttributeProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.VirtualProperty(Property)
class VirtualProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf()
    }
}

// sqlglot: properties.VolatileProperty(Property)
class VolatileProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false,
        )
    }
}

// sqlglot: properties.WithDataProperty(Property)
class WithDataProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "no" to true, "statistics" to false,
        )
    }
}

// sqlglot: properties.WithJournalTableProperty(Property)
class WithJournalTableProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.WithProcedureOptions(Property)
class WithProcedureOptions(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: properties.WithSchemaBindingProperty(Property)
class WithSchemaBindingProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: properties.WithSystemVersioningProperty(Property)
class WithSystemVersioningProperty(initArgs: Args = emptyMap()) : Property(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "on" to false, "this" to false, "data_consistency" to false,
            "retention_period" to false, "with_" to true,
        )
    }
}
