// GENERATED FILE — DO NOT EDIT.
// Generated by tools/gen_ast_nodes.py from sqlglot v30.12.0-44-g93d16591.
// sqlglot is MIT-licensed, copyright Toby Mao. See reference/sqlglot/LICENSE.
package dev.brikk.house.sql.ast

// sqlglot.expressions.datatypes: 4 generated classes.

// sqlglot: datatypes.Interval(_TimeUnit)
class Interval(initArgs: Args = emptyMap()) : Expression(initArgs), TimeUnit {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "unit" to false,
        )
    }
}

// sqlglot: datatypes.IntervalSpan(DataType)
class IntervalSpan(initArgs: Args = emptyMap()) : DataType(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: datatypes.ObjectIdentifier(DataType)
class ObjectIdentifier(initArgs: Args = emptyMap()) : DataType(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}

// sqlglot: datatypes.PseudoType(DataType)
class PseudoType(initArgs: Args = emptyMap()) : DataType(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true,
        )
    }
}
