// GENERATED FILE — DO NOT EDIT.
// Generated by tools/gen_ast_nodes.py from sqlglot v30.12.0-44-g93d16591.
// sqlglot is MIT-licensed, copyright Toby Mao. See reference/sqlglot/LICENSE.
package dev.brikk.house.sql.ast

// sqlglot.expressions.core: 49 generated classes.

// sqlglot: core.AnonymousAggFunc(Expression, AggFunc) — is_var_len_args
open class AnonymousAggFunc(initArgs: Args = emptyMap()) : Expression(initArgs), AggFunc {
    override val argTypes get() = ARG_TYPES
    override val isVarLenArgs get() = true

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to false,
        )
    }
}

// sqlglot: core.ApproxDistinct(Expression, AggFunc) — _sql_names = ['APPROX_DISTINCT', 'APPROX_COUNT_DISTINCT']
class ApproxDistinct(initArgs: Args = emptyMap()) : Expression(initArgs), AggFunc {
    override val argTypes get() = ARG_TYPES
    override val sqlNamesOverride get() = SQL_NAMES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "accuracy" to false,
        )
        private val SQL_NAMES = listOf("APPROX_DISTINCT", "APPROX_COUNT_DISTINCT")
    }
}

// sqlglot: core.AtIndex(Expression)
class AtIndex(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: core.AtTimeZone(Expression)
class AtTimeZone(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "zone" to true,
        )
    }
}

// sqlglot: core.Bracket(Expression, Condition)
class Bracket(initArgs: Args = emptyMap()) : Expression(initArgs), Condition {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to true, "offset" to false, "safe" to false,
            "returns_list_for_maps" to false, "json_access" to false,
        )
    }
}

// sqlglot: core.Cache(Expression)
class Cache(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "lazy" to false, "options" to false, "expression" to false,
        )
    }
}

// sqlglot: core.Check(Expression)
class Check(initArgs: Args = emptyMap()) : Expression(initArgs)

// sqlglot: core.DynamicIdentifier(Expression, Func)
class DynamicIdentifier(initArgs: Args = emptyMap()) : Expression(initArgs), Func {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to false,
        )
    }
}

// sqlglot: core.Filter(Expression)
class Filter(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: core.ForIn(Expression)
class ForIn(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: core.FormatPhrase(Expression)
class FormatPhrase(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "format" to true,
        )
    }
}

// sqlglot: core.FromTimeZone(Expression)
class FromTimeZone(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "zone" to true,
        )
    }
}

// sqlglot: core.HashAgg(Expression, AggFunc) — is_var_len_args
class HashAgg(initArgs: Args = emptyMap()) : Expression(initArgs), AggFunc {
    override val argTypes get() = ARG_TYPES
    override val isVarLenArgs get() = true

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to false,
        )
    }
}

// sqlglot: core.HavingMax(Expression)
class HavingMax(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true, "max" to true,
        )
    }
}

// sqlglot: core.Hint(Expression)
class Hint(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "expressions" to true,
        )
    }
}

// sqlglot: core.Hll(Expression, AggFunc) — is_var_len_args
class Hll(initArgs: Args = emptyMap()) : Expression(initArgs), AggFunc {
    override val argTypes get() = ARG_TYPES
    override val isVarLenArgs get() = true

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to false,
        )
    }
}

// sqlglot: core.IgnoreNulls(Expression)
class IgnoreNulls(initArgs: Args = emptyMap()) : Expression(initArgs)

// sqlglot: core.JoinHint(Expression)
class JoinHint(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to true,
        )
    }
}

// sqlglot: core.LockingStatement(Expression)
class LockingStatement(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: core.Opclass(Expression)
class Opclass(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true,
        )
    }
}

// sqlglot: core.ParameterizedAgg(Expression, AggFunc)
open class ParameterizedAgg(initArgs: Args = emptyMap()) : Expression(initArgs), AggFunc {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expressions" to true, "params" to true,
        )
    }
}

// sqlglot: core.PivotAny(Expression)
class PivotAny(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false,
        )
    }
}

// sqlglot: core.Refresh(Expression)
class Refresh(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "kind" to true,
        )
    }
}

// sqlglot: core.RespectNulls(Expression)
class RespectNulls(initArgs: Args = emptyMap()) : Expression(initArgs)

// sqlglot: core.SafeFunc(Expression, Func)
class SafeFunc(initArgs: Args = emptyMap()) : Expression(initArgs), Func

// sqlglot: core.SessionParameter(Expression, Condition)
class SessionParameter(initArgs: Args = emptyMap()) : Expression(initArgs), Condition {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "kind" to false,
        )
    }
}

// sqlglot: core.Slice(Expression)
class Slice(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to false, "expression" to false, "step" to false,
        )
    }
}

// sqlglot: core.Typeof(Expression, Func)
class Typeof(initArgs: Args = emptyMap()) : Expression(initArgs), Func

// sqlglot: core.Uncache(Expression)
class Uncache(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "exists" to false,
        )
    }
}

// sqlglot: core.WithinGroup(Expression)
class WithinGroup(initArgs: Args = emptyMap()) : Expression(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to false,
        )
    }
}

// sqlglot: core.Adjacent(Expression, Binary)
class Adjacent(initArgs: Args = emptyMap()) : Binary(initArgs)

// sqlglot: core.BitwiseLeftShift(Expression, Binary)
class BitwiseLeftShift(initArgs: Args = emptyMap()) : Binary(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true, "requires_int128" to false,
        )
    }
}

// sqlglot: core.BitwiseRightShift(Expression, Binary)
class BitwiseRightShift(initArgs: Args = emptyMap()) : Binary(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true, "requires_int128" to false,
        )
    }
}

// sqlglot: core.CombinedAggFunc(AnonymousAggFunc)
class CombinedAggFunc(initArgs: Args = emptyMap()) : AnonymousAggFunc(initArgs)

// sqlglot: core.CombinedParameterizedAgg(ParameterizedAgg)
class CombinedParameterizedAgg(initArgs: Args = emptyMap()) : ParameterizedAgg(initArgs)

// sqlglot: core.Distance(Expression, Binary)
class Distance(initArgs: Args = emptyMap()) : Binary(initArgs)

// sqlglot: core.DistanceNd(Expression, Binary)
class DistanceNd(initArgs: Args = emptyMap()) : Binary(initArgs)

// sqlglot: core.ExtendsLeft(Expression, Binary)
class ExtendsLeft(initArgs: Args = emptyMap()) : Binary(initArgs)

// sqlglot: core.ExtendsRight(Expression, Binary)
class ExtendsRight(initArgs: Args = emptyMap()) : Binary(initArgs)

// sqlglot: core.Glob(Expression, Binary, Predicate)
class Glob(initArgs: Args = emptyMap()) : Binary(initArgs), Predicate

// sqlglot: core.Kwarg(Expression, Binary)
class Kwarg(initArgs: Args = emptyMap()) : Binary(initArgs)

// sqlglot: core.Match(Expression, Binary, Predicate)
class Match(initArgs: Args = emptyMap()) : Binary(initArgs), Predicate

// sqlglot: core.NestedJSONSelect(Expression, Binary)
class NestedJSONSelect(initArgs: Args = emptyMap()) : Binary(initArgs)

// sqlglot: core.Operator(Expression, Binary)
class Operator(initArgs: Args = emptyMap()) : Binary(initArgs) {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "operator" to true, "expression" to true,
        )
    }
}

// sqlglot: core.Overlaps(Expression, Binary)
class Overlaps(initArgs: Args = emptyMap()) : Binary(initArgs)

// sqlglot: core.PivotAlias(Alias)
class PivotAlias(initArgs: Args = emptyMap()) : Alias(initArgs)

// sqlglot: core.Pseudocolumn(Column)
class Pseudocolumn(initArgs: Args = emptyMap()) : Column(initArgs)

// sqlglot: core.RegexpLike(Expression, Binary, Func)
class RegexpLike(initArgs: Args = emptyMap()) : Binary(initArgs), Func {
    override val argTypes get() = ARG_TYPES

    companion object {
        private val ARG_TYPES = argTypesOf(
            "this" to true, "expression" to true, "flag" to false, "full_match" to false,
        )
    }
}

// sqlglot: core.SimilarTo(Expression, Binary, Predicate)
class SimilarTo(initArgs: Args = emptyMap()) : Binary(initArgs), Predicate
