package dev.brikk.house.sql

import dev.brikk.house.sql.ast.Add
import dev.brikk.house.sql.ast.Alias
import dev.brikk.house.sql.ast.And
import dev.brikk.house.sql.ast.Anonymous
import dev.brikk.house.sql.ast.Avg
import dev.brikk.house.sql.ast.Between
import dev.brikk.house.sql.ast.CTE
import dev.brikk.house.sql.ast.Cast
import dev.brikk.house.sql.ast.Column
import dev.brikk.house.sql.ast.Command
import dev.brikk.house.sql.ast.Count
import dev.brikk.house.sql.ast.DType
import dev.brikk.house.sql.ast.DataType
import dev.brikk.house.sql.ast.Distinct
import dev.brikk.house.sql.ast.Div
import dev.brikk.house.sql.ast.Dot
import dev.brikk.house.sql.ast.EQ
import dev.brikk.house.sql.ast.Except
import dev.brikk.house.sql.ast.Expression
import dev.brikk.house.sql.ast.From
import dev.brikk.house.sql.ast.GT
import dev.brikk.house.sql.ast.GTE
import dev.brikk.house.sql.ast.Group
import dev.brikk.house.sql.ast.Having
import dev.brikk.house.sql.ast.ILike
import dev.brikk.house.sql.ast.Identifier
import dev.brikk.house.sql.ast.In
import dev.brikk.house.sql.ast.Intersect
import dev.brikk.house.sql.ast.Is
import dev.brikk.house.sql.ast.Join
import dev.brikk.house.sql.ast.LT
import dev.brikk.house.sql.ast.LTE
import dev.brikk.house.sql.ast.Limit
import dev.brikk.house.sql.ast.Literal
import dev.brikk.house.sql.ast.Max
import dev.brikk.house.sql.ast.Min
import dev.brikk.house.sql.ast.Mod
import dev.brikk.house.sql.ast.Mul
import dev.brikk.house.sql.ast.NEQ
import dev.brikk.house.sql.ast.Neg
import dev.brikk.house.sql.ast.Not
import dev.brikk.house.sql.ast.Null
import dev.brikk.house.sql.ast.NullSafeEQ
import dev.brikk.house.sql.ast.Offset
import dev.brikk.house.sql.ast.Or
import dev.brikk.house.sql.ast.Order
import dev.brikk.house.sql.ast.Ordered
import dev.brikk.house.sql.ast.Paren
import dev.brikk.house.sql.ast.Parameter
import dev.brikk.house.sql.ast.Placeholder
import dev.brikk.house.sql.ast.Pow
import dev.brikk.house.sql.ast.Select
import dev.brikk.house.sql.ast.Serde
import dev.brikk.house.sql.ast.Star
import dev.brikk.house.sql.ast.Sub
import dev.brikk.house.sql.ast.Subquery
import dev.brikk.house.sql.ast.Sum
import dev.brikk.house.sql.ast.Table
import dev.brikk.house.sql.ast.TableAlias
import dev.brikk.house.sql.ast.Union
import dev.brikk.house.sql.ast.Where
import dev.brikk.house.sql.ast.With
import dev.brikk.house.sql.ast.Xor
import dev.brikk.house.sql.ast.args
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Differential test: replays the Python-oracle AST serde corpus (generated by
 * tools/gen_ast_corpus.py, which hand-builds trees with direct sqlglot constructors
 * and dumps them with sqlglot.serde.dump). For each case this test hand-builds the
 * SAME tree with our node classes and asserts:
 *  1. Serde.dump(tree) matches the oracle dump structurally (after stripping
 *     meta/comments on both sides — position parity comes with the parser work),
 *  2. load(dump(tree)) round-trips to an equal tree.
 *
 * The Kotlin builders below MUST stay mechanically in sync with the recipes in
 * tools/gen_ast_corpus.py (same constructors, same arg order).
 */
class AstCorpusDifferentialTest {

    private fun ident(name: String, quoted: Boolean = false): Identifier =
        Identifier(args("this" to name, "quoted" to quoted))

    private fun col(name: String): Column = Column(args("this" to ident(name)))

    private fun num(value: String): Literal =
        Literal(args("this" to value, "is_string" to false))

    private fun num(value: Int): Literal = num(value.toString())

    private fun lit(value: String): Literal =
        Literal(args("this" to value, "is_string" to true))

    /** Kotlin twins of the Python recipes in tools/gen_ast_corpus.py, keyed by recipe id. */
    private val twins: Map<String, () -> Expression> = mapOf(
        "literal_int" to { num(5) },
        "literal_string" to { lit("Hello World") },
        "boolean_eq_is_null" to {
            EQ(
                args(
                    "this" to dev.brikk.house.sql.ast.Boolean(args("this" to true)),
                    "expression" to Is(args("this" to col("a"), "expression" to Null())),
                )
            )
        },
        "column_qualified" to {
            Column(args("this" to ident("a", quoted = true), "table" to ident("t"), "db" to ident("d")))
        },
        "dot_neg" to {
            Neg(
                args(
                    "this" to Dot(
                        args(
                            "this" to Dot(args("this" to ident("d"), "expression" to ident("t"))),
                            "expression" to ident("a"),
                        )
                    )
                )
            )
        },
        "alias_add" to {
            Alias(
                args(
                    "this" to Add(args("this" to col("a"), "expression" to num(1))),
                    "alias" to ident("x"),
                )
            )
        },
        "arithmetic" to {
            Sub(
                args(
                    "this" to Add(
                        args(
                            "this" to Mul(args("this" to col("a"), "expression" to num(2))),
                            "expression" to Div(
                                args(
                                    "this" to col("b"),
                                    "expression" to num(3),
                                    "typed" to false,
                                    "safe" to false,
                                )
                            ),
                        )
                    ),
                    "expression" to Mod(
                        args(
                            "this" to Pow(args("this" to col("c"), "expression" to num(4))),
                            "expression" to num(5),
                        )
                    ),
                )
            )
        },
        "logic_not_paren" to {
            And(
                args(
                    "this" to Or(
                        args(
                            "this" to EQ(args("this" to col("a"), "expression" to num(1))),
                            "expression" to GT(args("this" to col("b"), "expression" to num(2))),
                        )
                    ),
                    "expression" to Not(
                        args("this" to Paren(args("this" to LT(args("this" to col("c"), "expression" to num(3))))))
                    ),
                )
            )
        },
        "comparison_zoo" to {
            Xor(
                args(
                    "this" to And(
                        args(
                            "this" to NEQ(args("this" to col("a"), "expression" to num(1))),
                            "expression" to GTE(args("this" to col("b"), "expression" to num(2))),
                        )
                    ),
                    "expression" to Or(
                        args(
                            "this" to LTE(args("this" to col("c"), "expression" to num(3))),
                            "expression" to NullSafeEQ(args("this" to col("d"), "expression" to Null())),
                        )
                    ),
                )
            )
        },
        "in_list" to {
            In(args("this" to col("a"), "expressions" to listOf(num(1), num(2), num(3))))
        },
        "between_like" to {
            And(
                args(
                    "this" to Between(args("this" to col("a"), "low" to num(1), "high" to num(10))),
                    "expression" to ILike(args("this" to col("b"), "expression" to lit("%x%"))),
                )
            )
        },
        "cast_nested_array" to {
            Cast(
                args(
                    "this" to col("a"),
                    "to" to DataType(
                        args(
                            "this" to DType.ARRAY,
                            "expressions" to listOf(DataType(args("this" to DType.INT))),
                            "nested" to true,
                        )
                    ),
                )
            )
        },
        "cast_decimal" to {
            Cast(
                args(
                    "this" to num("3.14"),
                    "to" to DataType(args("this" to DType.DECIMAL)),
                )
            )
        },
        "select_star" to {
            Select(
                args(
                    "expressions" to listOf(Star()),
                    "from_" to From(args("this" to Table(args("this" to ident("t"))))),
                )
            )
        },
        "select_full" to {
            Select(
                args(
                    "expressions" to listOf(
                        col("a"),
                        Alias(args("this" to Sum(args("this" to col("b"))), "alias" to ident("total"))),
                    ),
                    "distinct" to Distinct(),
                    "from_" to From(args("this" to Table(args("this" to ident("t"), "db" to ident("d"))))),
                    "where" to Where(args("this" to GT(args("this" to col("b"), "expression" to num(0))))),
                    "group" to Group(args("expressions" to listOf(col("a")))),
                    "having" to Having(
                        args("this" to GT(args("this" to Count(args("this" to Star())), "expression" to num(1))))
                    ),
                    "order" to Order(
                        args(
                            "expressions" to listOf(
                                Ordered(args("this" to col("a"), "desc" to true, "nulls_first" to false))
                            )
                        )
                    ),
                    "limit" to Limit(args("expression" to num(10))),
                    "offset" to Offset(args("expression" to num(5))),
                )
            )
        },
        "join_subquery" to {
            Select(
                args(
                    "expressions" to listOf(Star()),
                    "from_" to From(
                        args(
                            "this" to Subquery(
                                args(
                                    "this" to Select(
                                        args(
                                            "expressions" to listOf(col("a")),
                                            "from_" to From(args("this" to Table(args("this" to ident("u"))))),
                                        )
                                    ),
                                    "alias" to TableAlias(args("this" to ident("sq"))),
                                )
                            )
                        )
                    ),
                    "joins" to listOf(
                        Join(
                            args(
                                "this" to Table(args("this" to ident("v"))),
                                "side" to "LEFT",
                                "on" to EQ(
                                    args(
                                        "this" to Column(args("this" to ident("a"), "table" to ident("sq"))),
                                        "expression" to Column(args("this" to ident("a"), "table" to ident("v"))),
                                    )
                                ),
                            )
                        )
                    ),
                )
            )
        },
        "cte_union" to {
            Select(
                args(
                    "with_" to With(
                        args(
                            "expressions" to listOf(
                                CTE(
                                    args(
                                        "this" to Union(
                                            args(
                                                "this" to Select(args("expressions" to listOf(num(1)))),
                                                "expression" to Select(args("expressions" to listOf(num(2)))),
                                                "distinct" to true,
                                            )
                                        ),
                                        "alias" to TableAlias(args("this" to ident("c"))),
                                    )
                                )
                            )
                        )
                    ),
                    "expressions" to listOf(Star()),
                    "from_" to From(args("this" to Table(args("this" to ident("c"))))),
                )
            )
        },
        "except_intersect" to {
            Except(
                args(
                    "this" to Select(
                        args(
                            "expressions" to listOf(col("a")),
                            "from_" to From(args("this" to Table(args("this" to ident("t"))))),
                        )
                    ),
                    "expression" to Intersect(
                        args(
                            "this" to Select(
                                args(
                                    "expressions" to listOf(col("a")),
                                    "from_" to From(args("this" to Table(args("this" to ident("u"))))),
                                )
                            ),
                            "expression" to Select(
                                args(
                                    "expressions" to listOf(col("a")),
                                    "from_" to From(args("this" to Table(args("this" to ident("v"))))),
                                )
                            ),
                            "distinct" to true,
                        )
                    ),
                    "distinct" to false,
                )
            )
        },
        "functions" to {
            Anonymous(
                args(
                    "this" to "MY_FUNC",
                    "expressions" to listOf(
                        col("a"),
                        num(1),
                        Max(args("this" to col("b"))),
                        Min(args("this" to col("c"))),
                        Avg(args("this" to col("d"))),
                        Count(args("this" to Star(), "big_int" to true)),
                    ),
                )
            )
        },
        "placeholder_parameter" to {
            Select(
                args(
                    "expressions" to listOf(
                        Placeholder(),
                        Parameter(args("this" to num(1))),
                        Placeholder(args("this" to "name", "kind" to true)),
                    )
                )
            )
        },
        "command" to {
            Command(args("this" to "SHOW", "expression" to "TABLES LIKE 'x'"))
        },
        "comments_meta" to {
            val column = col("x")
            column.comments = mutableListOf("leading comment", "trailing comment")
            column.meta["line"] = 1
            column.meta["col"] = 3
            (column.thisArg as Identifier).comments = mutableListOf("inner")
            column
        },
    )

    private val json = Json { ignoreUnknownKeys = true }

    private fun loadCorpus(): Map<String, JsonArray> {
        val stream = javaClass.classLoader.getResourceAsStream("ast-corpus/handbuilt.json")
            ?: java.io.File("brikk-sql/testResources/ast-corpus/handbuilt.json")
                .takeIf { it.exists() }
                ?.inputStream()
            ?: fail("corpus ast-corpus/handbuilt.json not found on classpath or filesystem")
        val root = stream.use { json.parseToJsonElement(it.readBytes().decodeToString()) }.jsonObject
        return root.getValue("cases").jsonArray.associate { case ->
            val obj = case.jsonObject
            obj.getValue("id").jsonPrimitive.content to obj.getValue("dump").jsonArray
        }
    }

    @Test
    fun dumpsMatchPythonOracle() {
        val corpus = loadCorpus()
        check(corpus.isNotEmpty()) { "empty ast corpus" }

        val missing = corpus.keys - twins.keys
        assertTrue(missing.isEmpty(), "corpus cases without a Kotlin twin: $missing")

        val mismatches = mutableListOf<String>()
        for ((id, oracle) in corpus) {
            val ours = Serde.dump(twins.getValue(id)())
            val oursStripped = Serde.stripMetaAndComments(ours)
            val oracleStripped = Serde.stripMetaAndComments(oracle)
            if (oursStripped != oracleStripped) {
                mismatches.add("case $id\n  oracle: $oracleStripped\n  ours:   $oursStripped")
            }
        }

        if (mismatches.isNotEmpty()) {
            fail("${mismatches.size}/${corpus.size} mismatching cases:\n\n" + mismatches.joinToString("\n\n"))
        }
    }

    @Test
    fun commentsAndMetaMatchPythonOracleUnstripped() {
        // comments/meta encoding parity is checked without stripping on the case that has them
        val oracle = loadCorpus().getValue("comments_meta")
        assertEquals(oracle, Serde.dump(twins.getValue("comments_meta")()))
    }

    @Test
    fun loadDumpRoundTripsEveryTree() {
        for ((id, build) in twins) {
            val tree = build()
            val dumped = Serde.dump(tree)
            val loaded = Serde.loadExpression(dumped)
            assertEquals(tree, loaded, "round-trip equality failed for case $id")
            assertEquals(dumped, Serde.dump(loaded), "round-trip dump stability failed for case $id")
        }
    }

    @Test
    fun oracleDumpsLoadIntoEqualTrees() {
        // loading the PYTHON dump must also produce a tree equal to the hand-built twin
        for ((id, oracle) in loadCorpus()) {
            val loaded = Serde.loadExpression(oracle)
            assertEquals(twins.getValue(id)(), loaded, "oracle load mismatch for case $id")
        }
    }
}
