package dev.brikk.house.sql

import dev.brikk.house.sql.ast.Serde
import dev.brikk.house.sql.parser.ParseError
import dev.brikk.house.sql.parser.parseOne
import kotlin.test.Test
import kotlin.test.fail
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put

/**
 * Gate: parseOne(sql, "hive") over the hive dialect-corpus identity SQLs must
 * structurally match Python sqlglot's ASTs (ast-corpus/hive-serde.json, generated by
 * tools/gen_serde_corpus.py --dialect hive), UNSTRIPPED (meta positions + comments included).
 * Failures must exactly match parser-corpus/hive-parser-known-failures.json — no
 * unledgered failure, no stale ledger entry.
 */
class HiveParserCorpusTest {

    private val json = Json { ignoreUnknownKeys = true }

    private fun resource(path: String): String {
        val stream = javaClass.classLoader.getResourceAsStream(path)
            ?: java.io.File("brikk-sql/testResources/$path").takeIf { it.exists() }?.inputStream()
            ?: java.io.File("testResources/$path").takeIf { it.exists() }?.inputStream()
            ?: fail("resource $path not found on classpath or filesystem")
        return stream.use { it.readBytes().decodeToString() }
    }

    private fun loadCorpus(): Pair<String, List<Pair<String, JsonArray>>> {
        val root = json.parseToJsonElement(resource("ast-corpus/hive-serde.json")).jsonObject
        val version = root.getValue("sqlglot_version").jsonPrimitive.content
        val cases = root.getValue("cases").jsonArray.map { case ->
            val obj = case.jsonObject
            obj.getValue("sql").jsonPrimitive.content to obj.getValue("dump").jsonArray
        }
        return version to cases
    }

    private fun loadLedger(): Map<String, String> {
        val text = try {
            resource("parser-corpus/hive-parser-known-failures.json")
        } catch (e: AssertionError) {
            return emptyMap()
        }
        val root = json.parseToJsonElement(text).jsonObject
        return root.getValue("cases").jsonArray.associate { entry ->
            val obj = entry.jsonObject
            obj.getValue("sql").jsonPrimitive.content to
                obj.getValue("reason").jsonPrimitive.content
        }
    }

    /** Derives a cluster-friendly reason from a structural mismatch. */
    private fun mismatchReason(expected: JsonArray, actual: JsonArray): String {
        for (i in 0 until minOf(expected.size, actual.size)) {
            if (expected[i] != actual[i]) {
                val exp = expected[i].jsonObject
                val cls = (exp["c"] as? JsonPrimitive)?.content?.substringAfterLast(".")
                val key = (exp["k"] as? JsonPrimitive)?.content
                return "ast-mismatch at #$i: expected " +
                    (cls?.let { "$it${key?.let { k -> " (k=$k)" } ?: ""}" }
                        ?: exp.toString().take(120))
            }
        }
        return "ast-mismatch: payload count expected=${expected.size} actual=${actual.size}"
    }

    @Test
    fun hiveCorpusMatchesPythonAstsModuloLedger() {
        val (version, cases) = loadCorpus()
        check(cases.isNotEmpty()) { "empty corpus" }
        val ledger = loadLedger()

        val failures = LinkedHashMap<String, String>() // sql -> reason
        val details = mutableListOf<String>()

        for ((sql, expectedDump) in cases) {
            // Unstripped: positions (meta) and comments must match Python's dumps.
            val expected = expectedDump
            val actual = try {
                Serde.dump(parseOne(sql, "hive"))
            } catch (e: ParseError) {
                failures[sql] = e.message?.lineSequence()?.first()?.take(160) ?: "ParseError"
                continue
            } catch (e: Exception) {
                failures[sql] = "${e::class.simpleName}: ${e.message?.take(140)}"
                continue
            }
            if (expected != actual) {
                failures[sql] = mismatchReason(expected, actual)
                val firstDiff = (0 until minOf(expected.size, actual.size))
                    .firstOrNull { expected[it] != actual[it] }
                    ?: minOf(expected.size, actual.size)
                details.add(
                    "SQL: $sql\n  first diff #$firstDiff\n" +
                        "  expected: ${expected.getOrNull(firstDiff)}\n" +
                        "  actual:   ${actual.getOrNull(firstDiff)}"
                )
            }
        }

        // Always write the actual failure set in ledger format for easy regeneration.
        val actualLedger = buildJsonObject {
            put("sqlglot_version", version)
            put("cases", buildJsonArray {
                for ((sql, reason) in failures) {
                    add(buildJsonObject {
                        put("sql", sql)
                        put("reason", reason)
                    })
                }
            })
        }
        val outDir = java.io.File("build").takeIf { it.isDirectory } ?: java.io.File(".")
        java.io.File(outDir, "hive-parser-ledger-actual.json")
            .writeText(Json { prettyPrint = true }.encodeToString(JsonObject.serializer(), actualLedger))

        val unledgered = failures.keys - ledger.keys
        val stale = ledger.keys - failures.keys

        println("HiveParserCorpusTest: ${cases.size - failures.size} pass / ${failures.size} ledgered (of ${cases.size})")

        val problems = mutableListOf<String>()
        if (unledgered.isNotEmpty()) {
            problems.add(
                "${unledgered.size} UNLEDGERED failures (showing up to 20):\n" +
                    unledgered.take(20).joinToString("\n") { "  $it\n    reason: ${failures[it]}" }
            )
            val shown = details.filter { d -> unledgered.any { d.startsWith("SQL: $it\n") } }
            if (shown.isNotEmpty()) {
                problems.add("mismatch details (up to 10):\n" + shown.take(10).joinToString("\n\n"))
            }
        }
        if (stale.isNotEmpty()) {
            problems.add(
                "${stale.size} STALE ledger entries now pass (showing up to 20):\n" +
                    stale.take(20).joinToString("\n") { "  $it" }
            )
        }
        if (problems.isNotEmpty()) {
            fail(
                problems.joinToString("\n\n") +
                    "\n\nActual ledger written to ${java.io.File(outDir, "hive-parser-ledger-actual.json").absolutePath}"
            )
        }
    }
}
