package dev.brikk.house.sql

import dev.brikk.house.sql.ast.Serde
import dev.brikk.house.sql.parser.ParseError
import dev.brikk.house.sql.parser.parseOne
import kotlin.test.Test
import kotlin.test.fail
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Differential test: replays the Python-oracle parser corpus (generated by
 * tools/gen_parser_corpus.py with sqlglot's serde.dump) against our Parser and requires
 * a structural match of every payload, after stripping meta/comments on both sides
 * (position tracking lands in a later phase).
 */
class ParserCorpusDifferentialTest {

    private val json = Json { ignoreUnknownKeys = true }

    private fun loadCorpus(name: String): Pair<List<Pair<String, JsonArray>>, Int> {
        val stream = javaClass.classLoader.getResourceAsStream("parser-corpus/$name")
            ?: java.io.File("brikk-sql/testResources/parser-corpus/$name")
                .takeIf { it.exists() }
                ?.inputStream()
            ?: fail("corpus parser-corpus/$name not found on classpath or filesystem")

        val root = stream.use { json.parseToJsonElement(it.readBytes().decodeToString()) }.jsonObject
        val cases = root.getValue("cases").jsonArray.map { element ->
            val case = element.jsonObject
            case.getValue("sql").jsonPrimitive.content to case.getValue("dump").jsonArray
        }
        return cases to cases.size
    }

    @Test
    fun baseCorpusMatchesPythonOracle() {
        val (cases, total) = loadCorpus("base.json")
        check(cases.isNotEmpty()) { "empty corpus base.json" }

        val mismatches = mutableListOf<String>()

        for ((sql, expectedDump) in cases) {
            val expected = Serde.stripMetaAndComments(expectedDump)

            val actual = try {
                Serde.stripMetaAndComments(Serde.dump(parseOne(sql)))
            } catch (e: ParseError) {
                mismatches.add("SQL: $sql\n  unexpected ParseError: ${e.message}")
                continue
            } catch (e: Exception) {
                mismatches.add("SQL: $sql\n  unexpected ${e::class.simpleName}: ${e.message}")
                continue
            }

            if (expected != actual) {
                var firstDiff = -1
                for (i in 0 until minOf(expected.size, actual.size)) {
                    if (expected[i] != actual[i]) {
                        firstDiff = i
                        break
                    }
                }
                if (firstDiff == -1) firstDiff = minOf(expected.size, actual.size)

                mismatches.add(
                    "SQL: $sql\n" +
                        "  first differing payload index: $firstDiff " +
                        "(expected ${expected.size} payloads, actual ${actual.size})\n" +
                        "  expected: ${expected.getOrNull(firstDiff)}\n" +
                        "  actual:   ${actual.getOrNull(firstDiff)}"
                )
            }
        }

        if (mismatches.isNotEmpty()) {
            fail(
                "${mismatches.size}/$total mismatching cases in base.json (showing up to 15):\n\n" +
                    mismatches.take(15).joinToString("\n\n")
            )
        }
    }
}
