package dev.brikk.house.sql

import dev.brikk.house.sql.ast.Expression
import dev.brikk.house.sql.dialects.Dialects
import dev.brikk.house.sql.dialects.sql
import dev.brikk.house.sql.optimizer.MappingSchema
import dev.brikk.house.sql.optimizer.OptimizeError
import dev.brikk.house.sql.optimizer.SchemaError
import dev.brikk.house.sql.optimizer.normalizeIdentifiers
import dev.brikk.house.sql.optimizer.qualify
import dev.brikk.house.sql.optimizer.qualifyColumns
import dev.brikk.house.sql.optimizer.qualifyTables
import dev.brikk.house.sql.optimizer.validateQualifyColumns
import dev.brikk.house.sql.parser.parseOne
import kotlin.test.Test
import kotlin.test.fail
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.add
import kotlinx.serialization.json.put

/**
 * Gate: our qualify pipeline over sqlglot's own optimizer fixtures
 * (testResources/qualify-corpus, generated by tools/gen_qualify_corpus.py from the
 * fixtures in tests/fixtures/optimizer with the exact kwargs tests/test_optimizer.py
 * passes).
 *
 * Per corpus we compare output SQL strings exactly (or expect OptimizeError/SchemaError
 * for the __invalid corpus). Cases whose fixture dialect is not one of our 8 supported
 * dialects are skipped ("dialect_supported": false), as are cases where the Python
 * oracle itself deviated from the fixture ("skipped", ~none).
 *
 * Failures must exactly match the ledger in qualify-corpus/known-failures.json — no
 * unledgered failure, no stale entry. The actual failure set is always written to
 * build/qualify-ledger-actual.json.
 */
class QualifyCorpusTest {

    private val json = Json { ignoreUnknownKeys = true }

    private fun resource(path: String): String {
        val stream = javaClass.classLoader.getResourceAsStream(path)
            ?: java.io.File("brikk-sql/testResources/$path").takeIf { it.exists() }?.inputStream()
            ?: java.io.File("testResources/$path").takeIf { it.exists() }?.inputStream()
            ?: fail("resource $path not found on classpath or filesystem")
        return stream.use { it.readBytes().decodeToString() }
    }

    private fun loadLedger(): Map<String, String> {
        val text = try {
            resource("qualify-corpus/known-failures.json")
        } catch (e: AssertionError) {
            return emptyMap()
        }
        val root = json.parseToJsonElement(text).jsonObject
        return root.getValue("cases").jsonArray.associate { entry ->
            val obj = entry.jsonObject
            obj.getValue("key").jsonPrimitive.content to
                obj.getValue("reason").jsonPrimitive.content
        }
    }

    /** Nested JsonObject -> plain Map (schema dicts hold string leaf values). */
    private fun toPlainMap(obj: JsonObject): MutableMap<String, Any?> {
        val out = LinkedHashMap<String, Any?>()
        for ((k, v) in obj) {
            out[k] = when (v) {
                is JsonObject -> toPlainMap(v)
                is JsonArray -> v.map { (it as JsonPrimitive).content }
                is JsonPrimitive -> v.content
                else -> null
            }
        }
        return out
    }

    private data class CorpusResult(
        val compared: Int,
        val skipped: Int,
        val failures: LinkedHashMap<String, String>,
    )

    private fun runCorpus(name: String): CorpusResult {
        val root = json.parseToJsonElement(resource("qualify-corpus/$name.json")).jsonObject
        val cases = root.getValue("cases").jsonArray.map { it.jsonObject }
        check(cases.isNotEmpty()) { "empty corpus: $name" }

        val schemaMap = (root["schema"] as? JsonObject)?.let { toPlainMap(it) }
        val visibleMap = (root["visible"] as? JsonObject)?.let { toPlainMap(it) }

        val failures = LinkedHashMap<String, String>()
        var compared = 0
        var skipped = 0

        for (case in cases) {
            val sql = case.getValue("sql").jsonPrimitive.content
            val key = "$name::$sql"

            if (case["dialect_supported"]?.jsonPrimitive?.content == "false" ||
                case["skipped"] != null
            ) {
                skipped++
                continue
            }

            val dialectName = case["dialect"]?.jsonPrimitive?.content ?: ""
            val flags = case["flags"] as? JsonObject
            val validate = flags?.get("validate_qualify_columns")
                ?.jsonPrimitive?.content != "false"
            val canonicalize = flags?.get("canonicalize_table_aliases")
                ?.jsonPrimitive?.content == "true"

            compared++

            if (case["raises"]?.jsonPrimitive?.content == "true") {
                // qualify_columns__invalid: qualify_columns + validate must raise
                // (OptimizeError, SchemaError)
                try {
                    val expr = parseOne(sql)
                    validateQualifyColumns(qualifyColumns(expr, schemaMap))
                    failures[key] = "expected OptimizeError/SchemaError, none raised"
                } catch (e: OptimizeError) {
                    // expected
                } catch (e: SchemaError) {
                    // expected
                } catch (e: Exception) {
                    failures[key] = "expected OptimizeError/SchemaError, got " +
                        "${e::class.simpleName}: ${e.message}"
                }
                continue
            }

            val expected = case.getValue("expected").jsonPrimitive.content

            val actual = try {
                val dialect = Dialects.forName(dialectName)
                val expr: Expression = parseOne(sql, dialectName)
                val result: Expression = when (name) {
                    "qualify_tables" -> qualifyTables(
                        expr,
                        db = "db",
                        catalog = "c",
                        dialect = dialect,
                        canonicalizeTableAliases = canonicalize,
                    )
                    "normalize_identifiers" -> normalizeIdentifiers(expr, dialect = dialect)
                    else -> qualify(
                        expr,
                        dialect = dialect,
                        schema = if (visibleMap != null) {
                            MappingSchema(schemaMap, visible = visibleMap, dialect = dialect)
                        } else {
                            schemaMap
                        },
                        inferSchema = true,
                        validateQualifyColumns = validate,
                        identify = false,
                    )
                }
                result.sql(dialectName)
            } catch (e: Exception) {
                failures[key] = "${e::class.simpleName}: ${e.message}"
                continue
            }

            if (actual != expected) {
                failures[key] = "output mismatch:\n      expected: $expected\n      actual:   $actual"
            }
        }

        return CorpusResult(compared, skipped, failures)
    }

    @Test
    fun qualifyCorpusMatchesPythonModuloLedger() {
        val corpora = listOf(
            "qualify_columns",
            "qualify_columns__with_invisible",
            "qualify_tables",
            "normalize_identifiers",
            "qualify_columns__invalid",
        )
        val ledger = loadLedger()

        val allFailures = LinkedHashMap<String, String>()
        val problems = mutableListOf<String>()

        for (name in corpora) {
            val result = runCorpus(name)
            allFailures.putAll(result.failures)

            val passed = result.compared - result.failures.size
            val rate = if (result.compared > 0) 100.0 * passed / result.compared else 100.0
            println(
                "QualifyCorpusTest[$name]: $passed/${result.compared} pass " +
                    "(${"%.1f".format(rate)}%), ${result.failures.size} failing, " +
                    "${result.skipped} skipped (unsupported dialect / oracle skip)"
            )
            if (rate < 90.0) {
                problems.add("$name below 90% gate: $passed/${result.compared}")
            }
        }

        // Always write the actual failure set in ledger format for easy regeneration.
        val actualLedger = buildJsonObject {
            put("cases", buildJsonArray {
                for ((key, reason) in allFailures) {
                    add(buildJsonObject { put("key", key); put("reason", reason) })
                }
            })
        }
        val outDir = java.io.File("build").takeIf { it.isDirectory } ?: java.io.File(".")
        java.io.File(outDir, "qualify-ledger-actual.json")
            .writeText(Json { prettyPrint = true }.encodeToString(JsonObject.serializer(), actualLedger))

        val unledgered = allFailures.keys - ledger.keys
        val stale = ledger.keys - allFailures.keys

        if (unledgered.isNotEmpty()) {
            problems.add(
                "${unledgered.size} UNLEDGERED failures (showing up to 20):\n" +
                    unledgered.take(20).joinToString("\n") { "  $it\n    reason: ${allFailures[it]}" }
            )
        }
        if (stale.isNotEmpty()) {
            problems.add(
                "${stale.size} STALE ledger entries now pass (showing up to 20):\n" +
                    stale.take(20).joinToString("\n") { "  $it" }
            )
        }
        if (problems.isNotEmpty()) {
            fail(
                problems.joinToString("\n\n") +
                    "\n\nActual ledger written to ${java.io.File(outDir, "qualify-ledger-actual.json").absolutePath}"
            )
        }
    }
}
