package dev.brikk.house.sql

import dev.brikk.house.sql.parser.DorisTokenizerTables
import dev.brikk.house.sql.parser.DuckdbTokenizerTables
import dev.brikk.house.sql.parser.MysqlTokenizerTables
import dev.brikk.house.sql.parser.PostgresTokenizerTables
import dev.brikk.house.sql.parser.PrestoTokenizerTables
import dev.brikk.house.sql.parser.TokenError
import dev.brikk.house.sql.parser.TrinoTokenizerTables
import dev.brikk.house.sql.parser.Tokenizer
import dev.brikk.house.sql.parser.TokenizerConfig
import kotlin.test.Test
import kotlin.test.fail
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Differential test: replays the Python-oracle token corpus (generated by
 * tools/gen_token_corpus.py from sqlglot's identity.sql fixture) against our
 * Tokenizer and requires an exact match of every token.
 */
class TokenCorpusDifferentialTest {

    @Serializable
    private data class OracleToken(
        val type: String,
        val text: String,
        val line: Int,
        val col: Int,
        val start: Int,
        val end: Int,
        val comments: List<String> = emptyList(),
    )

    @Serializable
    private data class OracleCase(val sql: String, val tokens: List<OracleToken>)

    @Serializable
    private data class Corpus(
        val dialect: String,
        val cases: List<OracleCase>,
    )

    private val json = Json { ignoreUnknownKeys = true }

    private fun loadCorpus(name: String): Corpus {
        val stream = javaClass.classLoader.getResourceAsStream("token-corpus/$name")
            ?: java.io.File("brikk-sql/testResources/token-corpus/$name")
                .takeIf { it.exists() }
                ?.inputStream()
            ?: fail("corpus token-corpus/$name not found on classpath or filesystem")
        return stream.use { json.decodeFromString(Corpus.serializer(), it.readBytes().decodeToString()) }
    }

    private fun runCorpus(name: String, config: TokenizerConfig) {
        val corpus = loadCorpus(name)
        check(corpus.cases.isNotEmpty()) { "empty corpus $name" }

        val mismatches = mutableListOf<String>()

        for (case in corpus.cases) {
            val actual = try {
                Tokenizer(config).tokenize(case.sql)
            } catch (e: TokenError) {
                mismatches.add("SQL: ${case.sql}\n  unexpected TokenError: ${e.message}")
                continue
            }

            var caseMismatch: String? = null
            if (actual.size != case.tokens.size) {
                caseMismatch = "token count expected=${case.tokens.size} actual=${actual.size}\n" +
                    "  expected: ${case.tokens.map { it.type to it.text }}\n" +
                    "  actual:   ${actual.map { it.tokenType.name to it.text }}"
            } else {
                for (i in case.tokens.indices) {
                    val exp = case.tokens[i]
                    val act = actual[i]
                    val same = exp.type == act.tokenType.name &&
                        exp.text == act.text &&
                        exp.line == act.line &&
                        exp.col == act.col &&
                        exp.start == act.start &&
                        exp.end == act.end &&
                        exp.comments == act.comments
                    if (!same) {
                        caseMismatch = "token #$i\n" +
                            "  expected: type=${exp.type} text=${exp.text} line=${exp.line} " +
                            "col=${exp.col} start=${exp.start} end=${exp.end} comments=${exp.comments}\n" +
                            "  actual:   type=${act.tokenType.name} text=${act.text} line=${act.line} " +
                            "col=${act.col} start=${act.start} end=${act.end} comments=${act.comments}"
                        break
                    }
                }
            }

            if (caseMismatch != null) {
                mismatches.add("SQL: ${case.sql}\n  $caseMismatch")
            }
        }

        if (mismatches.isNotEmpty()) {
            fail(
                "${mismatches.size}/${corpus.cases.size} mismatching cases in $name " +
                    "(showing up to 20):\n\n" +
                    mismatches.take(20).joinToString("\n\n")
            )
        }
    }

    @Test
    fun baseCorpusMatchesPythonOracle() = runCorpus("base.json", TokenizerConfig.BASE)

    @Test
    fun mysqlCorpusMatchesPythonOracle() = runCorpus("mysql.json", MysqlTokenizerTables.CONFIG)

    @Test
    fun dorisCorpusMatchesPythonOracle() = runCorpus("doris.json", DorisTokenizerTables.CONFIG)

    @Test
    fun prestoCorpusMatchesPythonOracle() = runCorpus("presto.json", PrestoTokenizerTables.CONFIG)

    @Test
    fun trinoCorpusMatchesPythonOracle() = runCorpus("trino.json", TrinoTokenizerTables.CONFIG)

    @Test
    fun duckdbCorpusMatchesPythonOracle() = runCorpus("duckdb.json", DuckdbTokenizerTables.CONFIG)

    @Test
    fun postgresCorpusMatchesPythonOracle() =
        runCorpus("postgres.json", PostgresTokenizerTables.CONFIG)
}
