package dev.brikk.house.sql

import dev.brikk.house.sql.dialects.sql
import dev.brikk.house.sql.optimizer.Node
import dev.brikk.house.sql.optimizer.SqlglotError
import dev.brikk.house.sql.optimizer.lineage
import dev.brikk.house.sql.optimizer.lineageAll
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.fail
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.add
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put

/**
 * Gate: our lineage() vs the Python oracle over testResources/lineage-corpus/base.json
 * (generated by tools/gen_lineage_corpus.py from reference/sqlglot tests/test_lineage.py
 * plus curated extras; unsupported-dialect cases were skipped at generation time).
 *
 * Node graphs are compared structurally: {name, expression sql, source sql, source_name,
 * reference_node_name, downstream}. Downstream children are sorted (on both sides) by a
 * Python-json.dumps-compatible canonical dump, because Python's to_node iterates a
 * set() of Column expressions whose order is hash-dependent and not portable.
 *
 * Failures must exactly match lineage-corpus/known-failures.json — no unledgered
 * failure, no stale entry. Actual failures are written to build/lineage-ledger-actual.json.
 */
class LineageCorpusTest : LedgerGate() {

    /** Nested JsonObject -> plain Map (schema dicts hold string leaf values). */
    private fun toPlainMap(obj: JsonObject): MutableMap<String, Any?> {
        val out = LinkedHashMap<String, Any?>()
        for ((k, v) in obj) {
            out[k] = when (v) {
                is JsonObject -> toPlainMap(v)
                is JsonArray -> v.map { (it as JsonPrimitive).content }
                is JsonPrimitive -> v.content
                else -> null
            }
        }
        return out
    }

    /** json.dumps(x, sort_keys=True) — Python-compatible canonical dump. */
    private fun pyDumps(element: JsonElement, sb: StringBuilder) {
        when (element) {
            is JsonObject -> {
                sb.append('{')
                var first = true
                for (key in element.keys.sorted()) {
                    if (!first) sb.append(", ")
                    first = false
                    pyString(key, sb)
                    sb.append(": ")
                    pyDumps(element.getValue(key), sb)
                }
                sb.append('}')
            }
            is JsonArray -> {
                sb.append('[')
                for ((i, item) in element.withIndex()) {
                    if (i > 0) sb.append(", ")
                    pyDumps(item, sb)
                }
                sb.append(']')
            }
            is JsonPrimitive -> {
                if (element.isString) pyString(element.content, sb) else sb.append(element.content)
            }
        }
    }

    private fun pyString(s: String, sb: StringBuilder) {
        sb.append('"')
        for (ch in s) {
            when {
                ch == '"' -> sb.append("\\\"")
                ch == '\\' -> sb.append("\\\\")
                ch == '\n' -> sb.append("\\n")
                ch == '\r' -> sb.append("\\r")
                ch == '\t' -> sb.append("\\t")
                ch.code < 0x20 || ch.code > 0x7e ->
                    sb.append("\\u").append(ch.code.toString(16).padStart(4, '0'))
                else -> sb.append(ch)
            }
        }
        sb.append('"')
    }

    private fun pyDumps(element: JsonElement): String =
        StringBuilder().also { pyDumps(element, it) }.toString()

    /** Serialize a lineage Node the same way tools/gen_lineage_corpus.py does. */
    private fun serialize(node: Node, dialect: String): JsonObject {
        val children = node.downstream
            .map { serialize(it, dialect) }
            .sortedBy { pyDumps(it) }
        return buildJsonObject {
            put("name", node.name)
            put("expression", node.expression.sql(dialect))
            put("source", node.source.sql(dialect))
            put("source_name", node.sourceName)
            put("reference_node_name", node.referenceNodeName)
            put("downstream", buildJsonArray { for (c in children) add(c) })
        }
    }

    /** Re-sort the oracle's downstream arrays with the same canonical key. */
    private fun canonicalize(expected: JsonObject): JsonObject {
        val children = expected.getValue("downstream").jsonArray
            .map { canonicalize(it.jsonObject) }
            .sortedBy { pyDumps(it) }
        return buildJsonObject {
            for ((k, v) in expected) {
                if (k == "downstream") {
                    put(k, buildJsonArray { for (c in children) add(c) })
                } else {
                    put(k, v)
                }
            }
        }
    }

    private fun expectedErrorFailure(case: String, expected: String, error: Exception?): CorpusFailure? =
        when {
            error == null -> CorpusFailure.missingError(case, expected)
            error is SqlglotError && error::class.simpleName == expected -> null
            else -> CorpusFailure.exception(case, "lineage (expected $expected)", error)
        }

    @Test
    fun expectedErrorRequiresExactSqlglotError() {
        val case = "expected-error-regression"
        assertNull(expectedErrorFailure(case, "SqlglotError", SqlglotError("missing column")))
        assertNotNull(expectedErrorFailure(case, "SqlglotError", IllegalArgumentException("missing column")))
        assertNotNull(expectedErrorFailure(case, "SqlglotError", NullPointerException("missing column")))
        assertNotNull(expectedErrorFailure(case, "OptimizeError", SqlglotError("missing column")))
        assertNotNull(expectedErrorFailure(case, "SqlglotError", null))
    }

    @Test
    fun lineageCorpusMatchesPythonModuloLedger() {
        val root = json.parseToJsonElement(testResource("lineage-corpus/base.json")).jsonObject
        val cases = root.getValue("cases").jsonArray.map { it.jsonObject }
        check(cases.isNotEmpty()) { "empty lineage corpus" }
        val ledger = loadLedger("lineage-corpus/known-failures.json", "key")
        val assertionIds = CorpusAssertionIds("lineage-corpus")

        var excluded = 0
        var unextractable = 0
        var duplicates = 0
        for (skip in root.getValue("skipped").jsonArray) {
            val entry = skip.jsonObject
            val reason = entry.getValue("reason").jsonPrimitive.content
            when {
                reason.startsWith("unsupported dialect: ") -> {
                    val dialect = reason.removePrefix("unsupported dialect: ")
                    check(CorpusDialects.resolveOrSkip(dialect) == null) {
                        "Lineage case ${entry["id"]} skips supported dialect '$dialect'; regenerate the corpus"
                    }
                    excluded++
                }
                reason == "duplicate of earlier case" -> duplicates++
                reason.startsWith("unresolvable") || reason.startsWith("unsupported kwargs:") ||
                    reason.startsWith("non-literal arg:") || reason == "**kwargs call" ||
                    reason == "sql arg is not a string literal" || reason == "fewer than 2 positional args" -> unextractable++
                else -> fail("Unclassified lineage extraction skip: $entry")
            }
        }

        val failures = LinkedHashMap<String, CorpusFailure>()
        var compared = 0

        for (case in cases) {
            val id = case.getValue("id").jsonPrimitive.content
            val sql = case.getValue("sql").jsonPrimitive.content
            val dialectName = case["dialect"]?.jsonPrimitive?.content ?: ""
            val trimSelects = case["trim_selects"]?.jsonPrimitive?.content != "false"
            val columnElem = case["column"] ?: JsonNull
            val schema = (case["schema"] as? JsonObject)?.let { toPlainMap(it) }
            val sources = (case["sources"] as? JsonObject)
                ?.mapValues { (_, v) -> v.jsonPrimitive.content as Any }
            val dialect = checkNotNull(CorpusDialects.resolveOrSkip(dialectName)) { "Runnable lineage case uses excluded dialect '$dialectName'" }
            val assertionId = assertionIds.next(buildJsonObject {
                put("case", JsonObject(case.filterKeys { it != "id" }))
                put("options", buildJsonObject {
                    put("operation", if (columnElem is JsonNull) "lineageAll" else "lineage")
                    put("dialect", dialectName)
                    put("trim_selects", trimSelects)
                })
            })

            compared++

            if (case["error"] != null) {
                val expectedError = case.getValue("error").jsonPrimitive.content
                var error: Exception? = null
                try {
                    if (columnElem is JsonNull) {
                        lineageAll(sql, schema = schema, sources = sources, dialect = dialect,
                            trimSelects = trimSelects)
                    } else {
                        lineage(columnElem.jsonPrimitive.content, sql, schema = schema,
                            sources = sources, dialect = dialect, trimSelects = trimSelects)
                    }
                } catch (e: Exception) {
                    error = e
                }
                expectedErrorFailure(id, expectedError, error)?.let { failures[assertionId] = it }
                continue
            }

            var phase = if (columnElem is JsonNull) "lineageAll" else "lineage"
            try {
                if (columnElem is JsonNull) {
                    val result = lineageAll(
                        sql, schema = schema, sources = sources, dialect = dialect,
                        trimSelects = trimSelects,
                    )
                    phase = "serialize"
                    val expected = case.getValue("expected_columns").jsonObject
                    val exp = JsonObject(expected.mapValues { (_, node) -> canonicalize(node.jsonObject) })
                    val act = JsonObject(result.mapValues { (_, node) -> serialize(node, dialectName) })
                    if (pyDumps(exp) != pyDumps(act)) {
                        failures[assertionId] = CorpusFailure.mismatch(
                            id, exp, act,
                            reason = if (result.keys != expected.keys) {
                                "column set mismatch: expected ${expected.keys}, actual ${result.keys}"
                            } else {
                                "graph mismatch:\n      expected: ${pyDumps(exp)}\n      actual:   ${pyDumps(act)}"
                            },
                        )
                    }
                } else {
                    val node = lineage(
                        columnElem.jsonPrimitive.content, sql, schema = schema,
                        sources = sources, dialect = dialect, trimSelects = trimSelects,
                    )
                    phase = "serialize"
                    val exp = canonicalize(case.getValue("expected").jsonObject)
                    val act = serialize(node, dialectName)
                    if (pyDumps(exp) != pyDumps(act)) {
                        failures[assertionId] = CorpusFailure.mismatch(
                            id, exp, act,
                            reason = "graph mismatch:\n      expected: ${pyDumps(exp)}\n      actual:   ${pyDumps(act)}",
                        )
                    }
                }
            } catch (e: Exception) {
                failures[assertionId] = CorpusFailure.exception(id, phase, e)
            }
        }

        check(compared + excluded + unextractable + duplicates == cases.size + root.getValue("skipped").jsonArray.size) {
            "Unaccounted lineage extraction records"
        }
        val passed = compared - failures.size
        val rate = if (compared > 0) 100.0 * passed / compared else 100.0
        enforceLedger(
            ledger = ledger,
            failures = failures,
            summary = "LineageCorpusTest: $passed/$compared pass (${"%.1f".format(rate)}%), " +
                "${failures.size} failing, excluded=$excluded, unextractable=$unextractable, duplicate=$duplicates, " +
                "oracle-raised=${cases.count { it["error"] != null }} (executed as error assertions)",
            actualLedgerName = "lineage-ledger-actual.json",
            caseKey = "key",
        )
        if (rate < 90.0) fail("below 90% gate: $passed/$compared")
    }
}
