package dev.brikk.house.sql

import dev.brikk.house.sql.ast.Serde
import dev.brikk.house.sql.parser.parseOne
import kotlin.test.Test
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put

/**
 * Shared harness for the per-dialect parser gates.
 *
 * Gate: parseOne(sql, <dialect>) over the <dialect> dialect-corpus identity SQLs must
 * structurally match Python sqlglot's ASTs (ast-corpus/<dialect>-serde.json, generated by
 * tools/gen_serde_corpus.py --dialect <dialect>), UNSTRIPPED (meta positions + comments
 * included). Failures must exactly match parser-corpus/<dialect>-parser-known-failures.json
 * — no unledgered failure, no stale ledger entry (see [LedgerGate]).
 *
 * Each dialect gets a concrete subclass (one line) so gates stay individually addressable
 * via `--include-classes` and report per-dialect in test output.
 */
abstract class ParserCorpusGate(private val dialect: String) : LedgerGate() {

    private fun loadCorpus(): Pair<String, List<Pair<String, JsonArray>>> {
        val root = json.parseToJsonElement(testResource("ast-corpus/$dialect-serde.json")).jsonObject
        val version = root.getValue("sqlglot_version").jsonPrimitive.content
        val cases = root.getValue("cases").jsonArray.map { case ->
            val obj = case.jsonObject
            obj.getValue("sql").jsonPrimitive.content to obj.getValue("dump").jsonArray
        }
        return version to cases
    }

    /** Finds the first differing payload index and a cluster-friendly reason for it. */
    private fun firstMismatch(expected: JsonArray, actual: JsonArray): Pair<Int, String> {
        for (i in 0 until minOf(expected.size, actual.size)) {
            if (expected[i] != actual[i]) {
                val exp = expected[i].jsonObject
                val cls = (exp["c"] as? JsonPrimitive)?.content?.substringAfterLast(".")
                val key = (exp["k"] as? JsonPrimitive)?.content
                val reason = "ast-mismatch at #$i: expected " +
                    (cls?.let { "$it${key?.let { k -> " (k=$k)" } ?: ""}" }
                        ?: exp.toString().take(120))
                return i to reason
            }
        }
        val i = minOf(expected.size, actual.size)
        return i to "ast-mismatch: payload count expected=${expected.size} actual=${actual.size}"
    }

    @Test
    fun corpusMatchesPythonAstsModuloLedger() {
        val (version, cases) = loadCorpus()
        check(cases.isNotEmpty()) { "empty corpus" }
        val ledger = loadLedger("parser-corpus/$dialect-parser-known-failures.json", caseKey = "sql")

        val failures = LinkedHashMap<String, CorpusFailure>()
        val ids = CorpusAssertionIds("parser:$dialect")
        val details = mutableListOf<String>()
        var passed = 0

        for ((sql, expected) in cases) {
            val id = ids.next(buildJsonObject {
                put("dialect", dialect)
                put("sql", sql)
                put("expected", expected)
            })
            // Unstripped: positions (meta) and comments must match Python's dumps.
            var phase = "parse"
            val actual = try {
                val expression = parseOne(sql, dialect)
                phase = "dump"
                Serde.dump(expression)
            } catch (e: Exception) {
                failures[id] = CorpusFailure.exception(sql, phase, e)
                continue
            }
            if (expected != actual) {
                val (firstDiff, reason) = firstMismatch(expected, actual)
                failures[id] = CorpusFailure.mismatch(sql, expected, actual, reason = reason)
                details.add(
                    "SQL: $sql\n  first diff #$firstDiff\n" +
                        "  expected: ${expected.getOrNull(firstDiff)}\n" +
                        "  actual:   ${actual.getOrNull(firstDiff)}"
                )
            } else {
                passed += 1
            }
        }
        check(cases.size == passed + failures.size) { "Unaccounted parser assertions" }

        enforceLedger(
            ledger = ledger,
            failures = failures,
            summary = "${javaClass.simpleName}: $passed pass / " +
                "${failures.size} ledgered (of ${cases.size})",
            actualLedgerName = "$dialect-parser-ledger-actual.json",
            caseKey = "sql",
            sqlglotVersion = version,
            mismatchDetails = details,
        )
    }
}
