package dev.brikk.house.sql

import dev.brikk.house.sql.ast.Expression
import dev.brikk.house.sql.optimizer.MappingSchema
import dev.brikk.house.sql.optimizer.OptimizeError
import dev.brikk.house.sql.optimizer.SchemaError
import dev.brikk.house.sql.optimizer.normalizeIdentifiers
import dev.brikk.house.sql.optimizer.qualify
import dev.brikk.house.sql.optimizer.qualifyColumns
import dev.brikk.house.sql.optimizer.qualifyTables
import dev.brikk.house.sql.optimizer.validateQualifyColumns
import dev.brikk.house.sql.parser.parseOne
import kotlin.test.Test
import kotlin.test.fail
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put

/**
 * Gate: our qualify pipeline over sqlglot's own optimizer fixtures
 * (testResources/qualify-corpus, generated by tools/gen_qualify_corpus.py from the
 * fixtures in tests/fixtures/optimizer with the exact kwargs tests/test_optimizer.py
 * passes).
 *
 * Per corpus we compare output SQL strings exactly (or expect OptimizeError/SchemaError
 * for the __invalid corpus). Availability follows the shared corpus policy, not stale
 * fixture flags. Dialect exclusions and oracle failures are reported separately.
 *
 * Failures must exactly match the ledger in qualify-corpus/known-failures.json — no
 * unledgered failure, no stale entry. The actual failure set is always written to
 * build/qualify-ledger-actual.json.
 */
class QualifyCorpusTest : LedgerGate() {

    /** Nested JsonObject -> plain Map (schema dicts hold string leaf values). */
    private fun toPlainMap(obj: JsonObject): MutableMap<String, Any?> {
        val out = LinkedHashMap<String, Any?>()
        for ((k, v) in obj) {
            out[k] = when (v) {
                is JsonObject -> toPlainMap(v)
                is JsonArray -> v.map { (it as JsonPrimitive).content }
                is JsonPrimitive -> v.content
                else -> null
            }
        }
        return out
    }

    private data class CorpusResult(
        val compared: Int,
        val excluded: Int,
        val oracleFailed: Int,
        val failures: LinkedHashMap<String, CorpusFailure>,
    )

    private fun runCorpus(name: String, assertionIds: CorpusAssertionIds): CorpusResult {
        val root = json.parseToJsonElement(testResource("qualify-corpus/$name.json")).jsonObject
        val cases = root.getValue("cases").jsonArray.map { it.jsonObject }
        check(cases.isNotEmpty()) { "empty corpus: $name" }

        val schemaMap = (root["schema"] as? JsonObject)?.let { toPlainMap(it) }
        val visibleMap = (root["visible"] as? JsonObject)?.let { toPlainMap(it) }

        val failures = LinkedHashMap<String, CorpusFailure>()
        var compared = 0
        var excluded = 0
        var oracleFailed = 0

        for (case in cases) {
            val sql = case.getValue("sql").jsonPrimitive.content
            val key = "$name::$sql"

            val dialectName = case["dialect"]?.jsonPrimitive?.content ?: ""
            val dialect = CorpusDialects.resolveOrSkip(dialectName)
            if (dialect == null) {
                excluded++
                continue
            }
            check(case["dialect_supported"]?.jsonPrimitive?.content != "false") {
                "$name marks supported dialect '$dialectName' unavailable; regenerate the corpus"
            }
            if (case["skipped"] != null) {
                oracleFailed++
                continue
            }
            val flags = case["flags"] as? JsonObject
            val validate = flags?.get("validate_qualify_columns")
                ?.jsonPrimitive?.content != "false"
            val canonicalize = flags?.get("canonicalize_table_aliases")
                ?.jsonPrimitive?.content == "true"
            val raises = case["raises"]?.jsonPrimitive?.content == "true"
            val assertionId = assertionIds.next(buildJsonObject {
                put("corpus", name)
                put("schema", root["schema"] ?: JsonNull)
                put("visible", root["visible"] ?: JsonNull)
                put("case", JsonObject(case.filterKeys { it != "title" }))
                put("options", buildJsonObject {
                    put("dialect", if (raises) "" else dialectName)
                    when {
                        raises -> {
                            put("operation", "qualifyColumns+validateQualifyColumns")
                            put("expected_error", "OptimizeError/SchemaError")
                        }
                        name == "qualify_tables" -> {
                            put("operation", "qualifyTables")
                            put("db", "db")
                            put("catalog", "c")
                            put("canonicalize_table_aliases", canonicalize)
                        }
                        name == "normalize_identifiers" -> put("operation", "normalizeIdentifiers")
                        else -> {
                            put("operation", "qualify")
                            put("infer_schema", true)
                            put("validate_qualify_columns", validate)
                            put("identify", false)
                        }
                    }
                })
            })

            compared++

            if (raises) {
                // qualify_columns__invalid: qualify_columns + validate must raise
                // (OptimizeError, SchemaError)
                var phase = "parse"
                try {
                    val expr = parseOne(sql)
                    phase = "qualifyColumns"
                    val qualified = qualifyColumns(expr, schemaMap)
                    phase = "validateQualifyColumns"
                    validateQualifyColumns(qualified)
                    failures[assertionId] = CorpusFailure.missingError(key, "OptimizeError/SchemaError")
                } catch (e: OptimizeError) {
                    // expected
                } catch (e: SchemaError) {
                    // expected
                } catch (e: Exception) {
                    failures[assertionId] = CorpusFailure.exception(
                        key, "$phase (expected OptimizeError/SchemaError)", e,
                    )
                }
                continue
            }

            val expected = case.getValue("expected").jsonPrimitive.content

            var phase = "parse"
            val actual = try {
                val expr: Expression = dialect.parseOne(sql)
                phase = name
                val result: Expression = when (name) {
                    "qualify_tables" -> qualifyTables(
                        expr,
                        db = "db",
                        catalog = "c",
                        dialect = dialect,
                        canonicalizeTableAliases = canonicalize,
                    )
                    "normalize_identifiers" -> normalizeIdentifiers(expr, dialect = dialect)
                    else -> qualify(
                        expr,
                        dialect = dialect,
                        schema = if (visibleMap != null) {
                            MappingSchema(schemaMap, visible = visibleMap, dialect = dialect)
                        } else {
                            schemaMap
                        },
                        inferSchema = true,
                        validateQualifyColumns = validate,
                        identify = false,
                    )
                }
                phase = "generate"
                dialect.generate(result)
            } catch (e: Exception) {
                failures[assertionId] = CorpusFailure.exception(key, phase, e)
                continue
            }

            if (actual != expected) {
                failures[assertionId] = CorpusFailure.sqlMismatch(key, expected, actual)
            }
        }

        check(compared + excluded + oracleFailed == cases.size) { "Unaccounted qualification cases in $name" }
        return CorpusResult(compared, excluded, oracleFailed, failures)
    }

    @Test
    fun qualifyCorpusMatchesPythonModuloLedger() {
        val corpora = listOf(
            "qualify_columns",
            "qualify_columns__with_invisible",
            "qualify_tables",
            "normalize_identifiers",
            "qualify_columns__invalid",
        )
        val ledger = loadLedger("qualify-corpus/known-failures.json", "key")
        val assertionIds = CorpusAssertionIds("qualify-corpus")

        val allFailures = LinkedHashMap<String, CorpusFailure>()
        val problems = mutableListOf<String>()

        for (name in corpora) {
            val result = runCorpus(name, assertionIds)
            allFailures.putAll(result.failures)

            val passed = result.compared - result.failures.size
            val rate = if (result.compared > 0) 100.0 * passed / result.compared else 100.0
            println(
                "QualifyCorpusTest[$name]: $passed/${result.compared} pass " +
                    "(${"%.1f".format(rate)}%), ${result.failures.size} failing, " +
                    "excluded=${result.excluded}, oracle-failed=${result.oracleFailed}, unextractable=0 (fixture records)"
            )
            if (rate < 90.0) {
                problems.add("$name below 90% gate: $passed/${result.compared}")
            }
        }

        enforceLedger(
            ledger = ledger,
            failures = allFailures,
            summary = "QualifyCorpusTest: ${allFailures.size} failing across ${corpora.size} corpora",
            actualLedgerName = "qualify-ledger-actual.json",
            caseKey = "key",
        )
        if (problems.isNotEmpty()) {
            fail(problems.joinToString("\n\n"))
        }
    }
}
