package dev.brikk.house.sql

import dev.brikk.house.sql.ast.Table
import dev.brikk.house.sql.optimizer.Scope
import dev.brikk.house.sql.optimizer.traverseScope
import dev.brikk.house.sql.parser.ParseError
import dev.brikk.house.sql.parser.parseOne
import kotlin.test.Test
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put

/**
 * Gate: our traverseScope over the scope corpus (all identity.sql queries + handpicked
 * scope-heavy queries) must produce the same per-scope summaries as Python sqlglot's
 * traverse_scope (scope-corpus/base.json, generated by tools/gen_scope_corpus.py).
 *
 * Cases where Python skipped (parse error / no scopes) must also be skipped by us;
 * cases where Python raised (e.g. OptimizeError from selected_sources) must raise the
 * same error class. Failures must exactly match the ledger in
 * scope-corpus/known-failures.json — no unledgered failure, no stale entry.
 *
 * The actual failure set is always written to build/scope-ledger-actual.json.
 */
class ScopeCorpusTest : LedgerGate() {

    private fun qualifiedName(column: dev.brikk.house.sql.ast.Column): String {
        val table = column.text("table")
        return if (table.isNotEmpty()) "$table.${column.name}" else column.name
    }

    private fun summarize(scope: Scope): JsonObject = buildJsonObject {
        put("expression_class", scope.expression::class.simpleName)
        put("scope_type", scope.scopeType.name)
        put("sources", buildJsonArray {
            for ((name, source) in scope.sources) {
                add(buildJsonArray {
                    add(JsonPrimitive(name))
                    add(JsonPrimitive(if (source is Table) "table" else "scope"))
                })
            }
        })
        put("selected_source_names", buildJsonArray {
            for (name in scope.selectedSources.keys) add(JsonPrimitive(name))
        })
        put("column_names", buildJsonArray {
            for (c in scope.columns) add(JsonPrimitive(qualifiedName(c)))
        })
        put("external_column_names", buildJsonArray {
            for (c in scope.externalColumns) add(JsonPrimitive(qualifiedName(c)))
        })
        put("unqualified_column_count", scope.unqualifiedColumns.size)
        put("subquery_count", scope.subqueryScopes.size)
        put("cte_count", scope.cteScopes.size)
        put("derived_count", scope.derivedTableScopes.size)
        put("udtf_count", scope.udtfScopes.size)
        put("is_correlated_subquery", scope.isCorrelatedSubquery)
    }

    private fun mismatchReason(expected: JsonObject, actual: JsonObject): String {
        val expectedKind = listOf("scopes", "skipped", "error").first { it in expected }
        val actualKind = listOf("scopes", "skipped", "error").first { it in actual }
        if (expectedKind != actualKind) return "kind mismatch: expected $expectedKind, got $actualKind"
        if (expectedKind == "error") {
            return "error mismatch: expected ${expected["error"]}, got ${actual["error"]}"
        }
        if (expectedKind == "skipped") return "skipped-reason (informational)"

        val exp = expected.getValue("scopes").jsonArray
        val act = actual.getValue("scopes").jsonArray
        if (exp.size != act.size) {
            return "scope count mismatch: expected ${exp.size}, got ${act.size}"
        }
        for (i in exp.indices) {
            val e = exp[i].jsonObject
            val a = act[i].jsonObject
            for (key in e.keys) {
                if (e[key] != a[key]) {
                    return "scope #$i $key: expected ${e[key]} got ${a[key]}"
                }
            }
        }
        return "unknown mismatch"
    }

    @Test
    fun scopeCorpusMatchesPythonModuloLedger() {
        val root = json.parseToJsonElement(testResource("scope-corpus/base.json")).jsonObject
        val version = root.getValue("sqlglot_version").jsonPrimitive.content
        val cases = root.getValue("cases").jsonArray.map { it.jsonObject }
        check(cases.isNotEmpty()) { "empty corpus" }
        val ledger = loadLedger("scope-corpus/known-failures.json", "sql")
        val ids = CorpusAssertionIds("ScopeCorpusTest:base")

        val failures = LinkedHashMap<String, CorpusFailure>()
        var compared = 0

        for (expected in cases) {
            val sql = expected.getValue("sql").jsonPrimitive.content
            val id = ids.next(buildJsonObject {
                put("sql", sql)
                put("expected", expected)
                put("dialect", "")
                put("skipComparison", "any-legitimate-skip")
                put("errorComparison", "class-name")
            })
            compared++

            val ast = try {
                parseOne(sql)
            } catch (e: ParseError) {
                if ("skipped" !in expected) {
                    failures[id] = CorpusFailure.exception(sql, "parse", e)
                    continue
                }
                null
            } catch (e: Exception) {
                failures[id] = CorpusFailure.exception(sql, "parse", e)
                continue
            }
            val actual = if (ast == null) {
                buildJsonObject { put("sql", sql); put("skipped", "parse error") }
            } else {
                var phase = "traverse"
                try {
                    val scopes = traverseScope(ast)
                    phase = "summarize"
                    if (scopes.isEmpty()) {
                        buildJsonObject { put("sql", sql); put("skipped", "no scopes") }
                    } else {
                        buildJsonObject {
                            put("sql", sql)
                            put("scopes", buildJsonArray { for (s in scopes) add(summarize(s)) })
                        }
                    }
                } catch (e: Exception) {
                    // Oracle error cases compare the class, not the exception message.
                    if (expected["error"]?.jsonPrimitive?.content != (e::class.simpleName ?: "Exception")) {
                        failures[id] = CorpusFailure.exception(sql, phase, e)
                    }
                    continue
                }
            }

            val equal = when {
                "scopes" in expected ->
                    "scopes" in actual && expected["scopes"] == actual["scopes"]
                "error" in expected -> expected["error"] == actual["error"]
                // Python skipped (parse error or no scopes): we must skip too, any reason.
                else -> "skipped" in actual
            }
            if (!equal) {
                failures[id] = if ("error" in expected) {
                    CorpusFailure.missingError(sql, expected.getValue("error").jsonPrimitive.content, actual.toString())
                } else {
                    CorpusFailure.mismatch(
                        sql, expected, actual, kind = "scope-mismatch", reason = mismatchReason(expected, actual),
                    )
                }
            }
        }

        enforceLedger(
            ledger = ledger,
            failures = failures,
            summary = "ScopeCorpusTest: ${compared - failures.size} pass / ${failures.size} ledgered (of $compared)",
            actualLedgerName = "scope-ledger-actual.json",
            caseKey = "sql",
            sqlglotVersion = version,
        )
    }
}
