package dev.brikk.house.sql

import dev.brikk.house.sql.dialects.sql
import dev.brikk.house.sql.dialects.transpile
import dev.brikk.house.sql.parser.parseOne
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Hand assertions for the Postgres dialect wiring, each verified against the Python
 * oracle (reference/sqlglot v30.12.0-44-g93d16591): :: casts, JSON arrow operators,
 * regex operators, TO_CHAR time mapping, SERIAL-to-GENERATED, array slices with the
 * bracket-paren rule, GENERATE_SERIES transpilation and ON CONFLICT ... RETURNING.
 */
class PostgresDialectTest {

    private fun roundTrip(sqlText: String): String = parseOne(sqlText, "postgres").sql("postgres")

    @Test
    fun doubleColonCastRoundTrips() {
        assertEquals("SELECT CAST(c AS INT) FROM t", roundTrip("SELECT c::int FROM t"))
    }

    @Test
    fun jsonArrowOperators() {
        // COLUMN_OPERATORS[ARROW] via build_json_extract_path (arrow_req_json_type=True)
        assertEquals("SELECT x -> 'a' -> 0 FROM t", roundTrip("SELECT x -> 'a' -> 0 FROM t"))
        // `?` -> JSONBContains; base renders the function name
        assertEquals(
            "SELECT JSONB_CONTAINS(x, 'k')",
            transpile("SELECT x ? 'k'", read = "postgres", write = ""),
        )
    }

    @Test
    fun regexOperators() {
        // `~` -> RegexpLike (binary "~"), `!~*` -> NOT RegexpILike
        assertEquals("SELECT a ~ 'x', NOT a ~* 'y'", roundTrip("SELECT a ~ 'x', a !~* 'y'"))
    }

    @Test
    fun toCharTimeMappingToMysql() {
        // Postgres TIME_MAPPING 'YYYY-MM-DD' -> strftime -> MySQL DATE_FORMAT '%Y-%m-%d'
        assertEquals(
            "SELECT DATE_FORMAT(d, '%Y-%m-%d')",
            transpile("SELECT TO_CHAR(d, 'YYYY-MM-DD')", read = "postgres", write = "mysql"),
        )
    }

    @Test
    fun serialBecomesGeneratedIdentity() {
        // generators.postgres._serial_to_generated (ColumnDef preprocess)
        assertEquals(
            "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY)",
            roundTrip("CREATE TABLE t (id SERIAL PRIMARY KEY)"),
        )
    }

    @Test
    fun arrayLiteralSliceWrapsInParens() {
        // PostgresGenerator.bracket_sql: ARRAY[..][..] must wrap the ARRAY in parens
        assertEquals("SELECT (ARRAY[1, 2, 3])[2:3]", roundTrip("SELECT ARRAY[1, 2, 3][2:3]"))
    }

    @Test
    fun generateSeriesToPresto() {
        // ExplodingGenerateSeries -> base Unnest wrap -> Presto SEQUENCE
        assertEquals(
            "SELECT UNNEST(SEQUENCE(1, 5))",
            transpile("SELECT GENERATE_SERIES(1, 5)", read = "postgres", write = "presto"),
        )
    }

    @Test
    fun onConflictReturningRoundTrips() {
        assertEquals(
            "INSERT INTO t (a) VALUES (1) ON CONFLICT(a) DO UPDATE SET a = 2 RETURNING a",
            roundTrip("INSERT INTO t (a) VALUES (1) ON CONFLICT (a) DO UPDATE SET a = 2 RETURNING a"),
        )
    }
}
