platform=macos-arm64
version=26.5.0
url=https://github.com/chdb-io/chdb-core/releases/download/v26.5.0/macos-arm64-libchdb.tar.gz
archiveSha256=86a77d5aa775902740d312153eddfbdc641b8fd5a2e028ddfd18d002ade9ec38
