#!/usr/bin/env python3
"""Generates the full sqlglot expression-node catalog for brikk-sql.

Reads reference/sqlglot (see git describe for the pin) and emits:
  - brikk-sql/src/dev.brikk.house.sql/ast/GeneratedNodes<Module>.kt   (one per
    sqlglot.expressions submodule; every Expression subclass in EXPR_CLASSES that
    is not already handwritten in Nodes.kt / DataType.kt / Expression.kt)
  - brikk-sql/src/dev.brikk.house.sql/ast/GeneratedTraits.kt          (marker
    interfaces for the python mixin "traits" not yet represented in Kotlin)
  - brikk-sql/src/dev.brikk.house.sql/ast/GeneratedRegistry.kt        (serde
    registry entries for every class not registered by hand in Serde.kt)
  - a full DType enum spliced into ast/DataType.kt (surgical replacement of the
    `enum class DType { ... }` block only)
  - brikk-sql/testResources/ast-corpus/arg-types-manifest.json        (arg_types
    oracle for ALL Expression subclasses, including the handwritten ones)

The handwritten skip-list is scraped from the Kotlin sources at generation time,
so it never goes stale.

Run from anywhere:  python3 tools/gen_ast_nodes.py
Re-run whenever reference/sqlglot is updated, then review the diff.
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SQLGLOT = ROOT / "reference" / "sqlglot"
AST_DIR = ROOT / "brikk-sql" / "src" / "dev.brikk.house.sql" / "ast"
CORPUS_DIR = ROOT / "brikk-sql" / "testResources" / "ast-corpus"

sys.path.insert(0, str(SQLGLOT))

import sqlglot.expressions as exp  # noqa: E402
from sqlglot.expressions.core import (  # noqa: E402
    Binary,
    Connector,
    Expr,
    Expression,
    Func,
)
from sqlglot.helper import camel_to_snake_case  # noqa: E402


def sqlglot_version() -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(SQLGLOT), "describe", "--tags"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def kstr(s: str) -> str:
    """Escape a Python string into a Kotlin double-quoted string literal."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "$":
            out.append("\\$")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


HEADER = """\
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/gen_ast_nodes.py from sqlglot {version}.
// sqlglot is MIT-licensed, copyright Toby Mao. See reference/sqlglot/LICENSE.
package dev.brikk.house.sql.ast
"""

# ---------------------------------------------------------------------------
# Catalog + skip-list
# ---------------------------------------------------------------------------

VERSION = sqlglot_version()

# name -> class for every Expression subclass reachable via EXPR_CLASSES
NODES: dict[str, type] = {}
# name -> class for the mixin "traits" (Expr subclasses that are not Expression)
MIXINS: dict[str, type] = {}
for c in exp.EXPR_CLASSES.values():
    if c is Expression:
        continue  # the abstract Kotlin base class; never instantiated/dumped
    (NODES if issubclass(c, Expression) else MIXINS)[c.__name__] = c

CLASS_DECL_RE = re.compile(
    r"^(?:internal |private )?(?:abstract |open )?(?:class|interface|object|enum class) (\w+)",
    re.M,
)


def scrape_names(path: pathlib.Path) -> set[str]:
    return set(CLASS_DECL_RE.findall(path.read_text()))


HANDWRITTEN = (
    scrape_names(AST_DIR / "Nodes.kt")
    | scrape_names(AST_DIR / "DataType.kt")
    | scrape_names(AST_DIR / "Expression.kt")
)

# Classes already registered by hand in Serde.kt (`"X" to Entry(...)`)
SERDE_REGISTERED = set(re.findall(r'"(\w+)" to Entry\(', (AST_DIR / "Serde.kt").read_text()))

# Kotlin interfaces that already exist by hand
EXISTING_IFACES = {"Condition", "Predicate", "Func", "AggFunc", "SubqueryPredicate"}

assert Expression.arg_types == {"this": True}, "Expression.arg_types drifted"

# ---------------------------------------------------------------------------
# Base resolution: python bases -> (single Kotlin superclass, Kotlin interfaces)
# ---------------------------------------------------------------------------


def is_kotlin_class(b: type) -> bool:
    """True if b maps to a Kotlin *class* (Expression chain incl. Binary/Connector)."""
    if b in (Binary, Connector):
        return True
    return isinstance(b, type) and issubclass(b, Expression)


def is_emitted_class(b: type) -> bool:
    """True if b exists as a Kotlin class (handwritten or generated)."""
    if b in (Binary, Connector) or b is Expression:
        return True
    return b.__name__ in NODES or b.__name__ in HANDWRITTEN


def resolve_bases(c: type) -> tuple[list[type], list[str]]:
    """Direct python bases -> Kotlin class-base candidates + interface names.

    Private Expression subclasses that are not part of the catalog (e.g. core._TimeUnit)
    are flattened into their own bases.
    """
    kclasses: list[type] = []
    ifaces: list[str] = []
    for b in c.__bases__:
        if b is object or b is Expr:
            continue
        if is_kotlin_class(b):
            if is_emitted_class(b):
                kclasses.append(b)
            else:
                sub_k, sub_i = resolve_bases(b)
                kclasses.extend(sub_k)
                ifaces.extend(sub_i)
        else:
            # mixin trait
            assert issubclass(b, Expr), f"{c.__name__}: unexpected base {b}"
            ifaces.append(b.__name__)
    return kclasses, ifaces


_CHOSEN: dict[type, type | None] = {Expression: None, Binary: Expression, Connector: Binary}


def chosen_super(c: type) -> type | None:
    """The single Kotlin superclass for c (None for Expression itself)."""
    if c in _CHOSEN:
        return _CHOSEN[c]
    kclasses, _ = resolve_bases(c)
    reduced = reduce_class_bases(c, kclasses)
    _CHOSEN[c] = reduced
    return reduced


def kotlin_chain(c: type) -> list[type]:
    chain = []
    cur: type | None = c
    while cur is not None:
        chain.append(cur)
        cur = chosen_super(cur)
    return chain


def reduce_class_bases(c: type, kclasses: list[type]) -> type:
    assert kclasses, f"{c.__name__}: no Kotlin class base found"
    survivors = []
    for b in kclasses:
        # drop b if it is a Kotlin ancestor of another candidate
        if any(o is not b and b in kotlin_chain(o) for o in kclasses):
            continue
        survivors.append(b)
    uniq = list(dict.fromkeys(survivors))
    assert len(uniq) == 1, (
        f"{c.__name__}: ambiguous Kotlin superclass {[x.__name__ for x in uniq]} "
        f"from bases {[x.__name__ for x in kclasses]} — needs manual review"
    )
    return uniq[0]


# ---------------------------------------------------------------------------
# Trait interfaces
# ---------------------------------------------------------------------------


def gen_traits(warnings: list[str]) -> str:
    lines = [HEADER.format(version=VERSION)]
    lines.append("// Marker interfaces for python mixin traits (see Expression.kt for the")
    lines.append("// handwritten trait setup). Python-side behavior on these mixins (builder or")
    lines.append("// convenience methods, never arg_types) is deferred to later phases.")
    lines.append("")
    for name in sorted(set(MIXINS) - EXISTING_IFACES - {"Binary", "Connector"}):
        c = MIXINS[name]
        extra = [k for k in c.__dict__ if not k.startswith("__") and k not in ("key", "required_args")]
        parents = [b.__name__ for b in c.__bases__ if b is not Expr and b is not object]
        for p in parents:
            assert p in MIXINS or p in EXISTING_IFACES, f"trait {name}: unknown parent {p}"
        decl = f"interface {name}"
        if parents:
            decl += " : " + ", ".join(parents)
        comment = f"// sqlglot: {c.__module__.split('.')[-1]}.{name}"
        if extra:
            comment += f" — python members deferred: {', '.join(sorted(extra))}"
            warnings.append(f"trait {name} carries python members: {sorted(extra)} (marker interface emitted; behavior deferred)")
        lines.append(comment)
        lines.append(decl)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Node emission
# ---------------------------------------------------------------------------

FLAG_ATTRS = [
    # (python attr, kotlin member)
    ("_hash_raw_args", "hashRawArgs"),
    ("is_primitive", "isPrimitive"),
    ("is_cast", "isCast"),
    ("is_data_type", "isDataType"),
    ("is_subquery", "isSubquery"),
]


def topo_nodes() -> list[type]:
    """All catalog node classes, parents before children (by Kotlin chain depth)."""
    return sorted(NODES.values(), key=lambda c: (len(kotlin_chain(c)), c.__name__))


# Effective Kotlin-inherited sql_names (None == dynamic camel-case default).
EFFECTIVE_SQL_NAMES: dict[type, list[str] | None] = {}
# seed the handwritten Func overrides
for _name, _val in (("Pow", ["POWER", "POW"]), ("If", ["IF", "IIF"])):
    if _name in NODES:
        EFFECTIVE_SQL_NAMES[NODES[_name]] = _val


def arg_types_kotlin(arg_types: dict[str, bool], indent: str) -> list[str]:
    if not arg_types:
        return [f"{indent}private val ARG_TYPES = argTypesOf()"]
    entries = [f"{kstr(k)} to {str(v).lower()}" for k, v in arg_types.items()]
    lines = [f"{indent}private val ARG_TYPES = argTypesOf("]
    cur = f"{indent}    "
    for e in entries:
        candidate = cur + e + ", "
        if len(candidate) > 100 and cur.strip():
            lines.append(cur.rstrip())
            cur = f"{indent}    " + e + ", "
        else:
            cur = candidate
    if cur.strip():
        lines.append(cur.rstrip())
    lines.append(f"{indent})")
    return lines


def gen_node(c: type, open_classes: set[str]) -> list[str]:
    sup = chosen_super(c)
    assert sup is not None
    _, ifaces = resolve_bases(c)
    # drop interface redundant with the chosen superclass name (shouldn't happen)
    ifaces = list(dict.fromkeys(i for i in ifaces if i != sup.__name__))

    sup_name = sup.__name__

    # arg_types: emit override iff ordered items differ from Kotlin superclass effective
    own_at = list(c.arg_types.items())
    sup_at = list(sup.arg_types.items())
    emit_arg_types = own_at != sup_at

    # flags
    flag_overrides: list[str] = []
    for attr, member in FLAG_ATTRS:
        own = bool(getattr(c, attr, False))
        inherited = bool(getattr(sup, attr, False))
        if own != inherited:
            flag_overrides.append(f"    override val {member} get() = {str(own).lower()}")

    # Func metadata
    sql_names_override: list[str] | None = None
    varlen_override: bool | None = None
    if issubclass(c, Func):
        inherited_names = EFFECTIVE_SQL_NAMES.get(sup) if issubclass(sup, Func) else None
        desired = list(c.sql_names())
        default = [camel_to_snake_case(c.__name__)]
        if inherited_names is None:
            emit_names = desired != default
        else:
            emit_names = desired != inherited_names
        if emit_names:
            sql_names_override = desired
            EFFECTIVE_SQL_NAMES[c] = desired
        else:
            EFFECTIVE_SQL_NAMES[c] = inherited_names

        own_varlen = bool(getattr(c, "is_var_len_args", False))
        inherited_varlen = bool(getattr(sup, "is_var_len_args", False)) if issubclass(sup, Func) else False
        if own_varlen != inherited_varlen:
            varlen_override = own_varlen
    else:
        assert "_sql_names" not in c.__dict__, f"{c.__name__}: _sql_names on non-Func"

    # provenance comment
    base_desc = ", ".join(b.__name__ for b in c.__bases__)
    mod_short = c.__module__.split(".")[-1]
    extras = []
    if sql_names_override:
        extras.append(f'_sql_names = {sql_names_override}')
    if varlen_override:
        extras.append("is_var_len_args")
    for attr, _ in FLAG_ATTRS:
        if attr in c.__dict__:
            extras.append(attr.lstrip("_"))
    comment = f"// sqlglot: {mod_short}.{c.__name__}({base_desc})"
    if extras:
        comment += " — " + ", ".join(extras)

    open_kw = "open " if c.__name__ in open_classes else ""
    decl = f"{open_kw}class {c.__name__}(initArgs: Args = emptyMap()) : {sup_name}(initArgs)"
    if ifaces:
        decl += ", " + ", ".join(ifaces)

    body: list[str] = []
    companion: list[str] = []
    if emit_arg_types:
        body.append("    override val argTypes get() = ARG_TYPES")
        companion.extend(arg_types_kotlin(c.arg_types, "        "))
    if varlen_override is not None:
        body.append(f"    override val isVarLenArgs get() = {str(varlen_override).lower()}")
    if sql_names_override is not None:
        names = ", ".join(kstr(n) for n in sql_names_override)
        body.append(f"    override val sqlNamesOverride get() = SQL_NAMES")
        companion.append(f"        private val SQL_NAMES = listOf({names})")
    body.extend(flag_overrides)

    lines = [comment]
    if not body:
        lines.append(decl)
    else:
        lines.append(decl + " {")
        lines.extend(body)
        if companion:
            lines.append("")
            lines.append("    companion object {")
            lines.extend(companion)
            lines.append("    }")
        lines.append("}")
    lines.append("")
    return lines


def gen_node_files() -> dict[str, list[str]]:
    """module short name -> generated class names, and writes the files."""
    # classes that need `open` (extended by another catalog class)
    open_classes: set[str] = set()
    for c in NODES.values():
        sup = chosen_super(c)
        if sup is not None:
            open_classes.add(sup.__name__)

    to_emit = [c for c in topo_nodes() if c.__name__ not in HANDWRITTEN]

    by_module: dict[str, list[type]] = {}
    for c in to_emit:
        by_module.setdefault(c.__module__.split(".")[-1], []).append(c)

    emitted: dict[str, list[str]] = {}
    for mod, classes in sorted(by_module.items()):
        # emit in topological order (parents first) then name for readability;
        # topo_nodes already gives that ordering.
        lines = [HEADER.format(version=VERSION)]
        lines.append(f"// sqlglot.expressions.{mod}: {len(classes)} generated classes.")
        lines.append("")
        for c in classes:
            lines.extend(gen_node(c, open_classes))
        text = "\n".join(lines).rstrip() + "\n"
        fname = f"GeneratedNodes{mod.capitalize()}.kt"
        n_lines = text.count("\n")
        if n_lines > 3000:
            print(f"WARNING: {fname} has {n_lines} lines (>3000); consider splitting")
        (AST_DIR / fname).write_text(text)
        emitted[mod] = [c.__name__ for c in classes]
        print(f"Generated {fname}: {len(classes)} classes, {n_lines} lines")
    return emitted


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------


def gen_registry() -> int:
    to_register = [c for c in topo_nodes() if c.__name__ not in SERDE_REGISTERED]
    by_module: dict[str, list[type]] = {}
    for c in to_register:
        by_module.setdefault(c.__module__.split(".")[-1], []).append(c)

    map_t = "kotlin.collections.MutableMap<kotlin.String, ExpressionRegistry.Entry>"
    lines = [HEADER.format(version=VERSION)]
    lines.append("// Serde registry entries for every generated class (plus handwritten classes")
    lines.append("// not registered by hand in Serde.kt). Wired in by ExpressionRegistry.entries.")
    lines.append("")
    lines.append(f"internal fun registerAllGenerated(m: {map_t}) {{")
    for mod in sorted(by_module):
        lines.append(f"    registerGenerated{mod.capitalize()}(m)")
    lines.append("}")
    lines.append("")
    for mod, classes in sorted(by_module.items()):
        lines.append(f"private fun registerGenerated{mod.capitalize()}(m: {map_t}) {{")
        lines.append(f"    val module = \"sqlglot.expressions.{mod}\"")
        for c in sorted(classes, key=lambda x: x.__name__):
            lines.append(
                f"    m[{kstr(c.__name__)}] = ExpressionRegistry.Entry(module) {{ {c.__name__}() }}"
            )
        lines.append("}")
        lines.append("")
    (AST_DIR / "GeneratedRegistry.kt").write_text("\n".join(lines).rstrip() + "\n")
    print(f"Generated GeneratedRegistry.kt: {len(to_register)} entries")
    return len(to_register)


# ---------------------------------------------------------------------------
# DType enum surgery
# ---------------------------------------------------------------------------


def gen_dtype() -> None:
    from sqlglot.expressions.datatypes import DataType as PyDataType

    members = list(PyDataType.Type)
    body = [
        "/**",
        " * sqlglot: datatypes.DataType.Type (member order preserved; value strings can",
        " * differ from member names, e.g. USERDEFINED = \"USER-DEFINED\").",
        " *",
        f" * GENERATED by tools/gen_ast_nodes.py from sqlglot {VERSION} — do not edit by hand.",
        " */",
        "enum class DType(val value: kotlin.String) {",
    ]
    for m in members:
        body.append(f"    {m.name}({kstr(m.value)}),")
    body.append("    ;")
    body.append("")
    body.append("    companion object {")
    body.append("        private val BY_VALUE = entries.associateBy { it.value }")
    body.append("")
    body.append("        fun fromValue(value: kotlin.String): DType =")
    body.append("            BY_VALUE[value]")
    body.append("                ?: throw IllegalArgumentException(\"Unknown DataType.Type value: $value\")")
    body.append("    }")
    body.append("}")
    new_block = "\n".join(body)

    path = AST_DIR / "DataType.kt"
    text = path.read_text()
    start = text.index("enum class DType")
    # include the doc comment immediately preceding the enum, if any
    prefix = text[:start]
    m = re.search(r"/\*\*(?:[^*]|\*(?!/))*\*/\s*$", prefix, re.S)
    if m:
        start = m.start()
    # matching closing brace of the enum
    brace = text.index("{", text.index("enum class DType"))
    depth = 0
    end = None
    for i in range(brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    assert end is not None
    path.write_text(text[:start] + new_block + text[end:])
    print(f"Spliced DType enum into DataType.kt: {len(members)} members")


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------


def gen_manifest() -> None:
    classes = {}
    for name in sorted(NODES):
        c = NODES[name]
        classes[name] = {
            "module": c.__module__,
            "arg_types": {k: bool(v) for k, v in c.arg_types.items()},
        }
    manifest = {
        "sqlglot_version": VERSION,
        "class_count": len(classes),
        "traits": sorted(MIXINS),
        "classes": classes,
    }
    CORPUS_DIR.mkdir(parents=True, exist_ok=True)
    out = CORPUS_DIR / "arg-types-manifest.json"
    out.write_text(json.dumps(manifest, indent=1) + "\n")
    print(f"Generated arg-types-manifest.json: {len(classes)} classes, {len(MIXINS)} traits")


# ---------------------------------------------------------------------------


def main() -> None:
    print(f"sqlglot {VERSION}: {len(NODES)} node classes, {len(MIXINS)} traits")
    print(f"handwritten skip-list: {len(HANDWRITTEN & set(NODES))} node classes "
          f"(of {len(HANDWRITTEN)} scraped Kotlin decls)")

    warnings: list[str] = []
    (AST_DIR / "GeneratedTraits.kt").write_text(gen_traits(warnings))
    print(f"Generated GeneratedTraits.kt: {len(set(MIXINS) - EXISTING_IFACES - {'Binary', 'Connector'})} interfaces")

    emitted = gen_node_files()
    total = sum(len(v) for v in emitted.values())
    print(f"Total generated node classes: {total}")

    n_reg = gen_registry()
    expected = len(NODES) - len(SERDE_REGISTERED & set(NODES))
    assert n_reg == expected, f"registry mismatch: {n_reg} != {expected}"

    gen_dtype()
    gen_manifest()

    # handwritten classes that must be `open` (extended by generated classes)
    need_open = sorted(
        {chosen_super(c).__name__ for c in NODES.values()
         if c.__name__ not in HANDWRITTEN and chosen_super(c) is not None}
        & HANDWRITTEN - {"Expression", "Binary", "Connector", "Unary", "SetOperation"}
    )
    print(f"handwritten classes that must be open: {need_open}")

    if warnings:
        print("\n=== WARNINGS (traits carrying python behavior) ===")
        for w in warnings:
            print(" -", w)


if __name__ == "__main__":
    main()
