#!/usr/bin/env python3
"""Regenerates brikk-sql/src/dev.brikk.house.sql/parser/GeneratedFunctionRegistry.kt.

Emits the base layer of Parser.FUNCTIONS — {name: func.from_arg_list for name, func
in exp.FUNCTION_BY_NAME.items()} — as a Kotlin map. The hand-ported custom builders
(ParserFunctionBuilders.kt) are layered on top in BaseParserTables.FUNCTIONS,
mirroring the Python dict-merge order.

Run from the repo root: python3 tools/gen_function_registry.py
"""

import re
import sys

sys.path.insert(0, "reference/sqlglot")
from sqlglot import expressions as exp  # noqa: E402

OUT = "brikk-sql/src/dev.brikk.house.sql/parser/GeneratedFunctionRegistry.kt"


def kotlin_classes() -> set:
    classes = set()
    for path, pattern in [
        ("brikk-sql/src/dev.brikk.house.sql/ast/GeneratedRegistry.kt", r'm\["([A-Za-z0-9_]+)"\]'),
        ("brikk-sql/src/dev.brikk.house.sql/ast/Nodes.kt", r"class ([A-Za-z0-9_]+)"),
    ]:
        classes.update(re.findall(pattern, open(path).read()))
    return classes


def main() -> None:
    kotlin = kotlin_classes()

    missing = []
    lines = []
    for name, func in sorted(exp.FUNCTION_BY_NAME.items()):
        cls = func.__name__
        if cls not in kotlin:
            missing.append((name, cls))
            continue
        keys = ", ".join(f'"{k}"' for k in func.arg_types)
        varlen = "true" if func.is_var_len_args else "false"
        lines.append(
            f'        put("{name}", fromArgList(listOf({keys}), {varlen})'
            f" {{ dev.brikk.house.sql.ast.{cls}(it) }})"
        )

    out = [
        "// GENERATED FILE - DO NOT EDIT. Generated by tools/gen_function_registry.py",
        "// from reference/sqlglot exp.FUNCTION_BY_NAME (sqlglot v30.12.0-44-g93d16591).",
        "// sqlglot: Parser.FUNCTIONS base layer {name: func.from_arg_list}; custom",
        "// builders are layered on top in BaseParserTables.FUNCTIONS.",
        "package dev.brikk.house.sql.parser",
        "",
        "import dev.brikk.house.sql.ast.Expression",
        "",
        "internal val GENERATED_FUNCTION_BY_NAME:"
        " kotlin.collections.Map<kotlin.String, (kotlin.collections.List<Expression?>) -> Expression> =",
        "    buildMap {",
        *lines,
        "    }",
    ]
    open(OUT, "w").write("\n".join(out) + "\n")
    print(f"{len(lines)} entries; {len(missing)} missing: {missing[:20]}")


if __name__ == "__main__":
    main()
