#!/usr/bin/env python3
"""Generates Kotlin token tables for brikk-sql from the pinned sqlglot checkout.

Reads reference/sqlglot (see git describe for the pin) and emits:
  - brikk-sql/src/dev.brikk.house.sql/parser/TokenType.kt
  - brikk-sql/src/dev.brikk.house.sql/parser/BaseTokenizerTables.kt
  - brikk-sql/src/dev.brikk.house.sql/parser/<Dialect>TokenizerTables.kt for each
    non-base dialect in DIALECTS (with a fully-wired `CONFIG: TokenizerConfig`).

The emitted tables mirror EXACTLY what sqlglot/tokens.py Tokenizer._init_core passes
to TokenizerCore: the tokenizer-class tables/flags plus the dialect-level flags
(NUMBERS_CAN_BE_UNDERSCORE_SEPARATED, IDENTIFIERS_CAN_START_WITH_DIGIT,
UNESCAPED_SEQUENCES).

Run from anywhere:  python3 tools/gen_tokenizer_tables.py
Re-run whenever reference/sqlglot is updated, then review the diff.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SQLGLOT = ROOT / "reference" / "sqlglot"
OUT_DIR = ROOT / "brikk-sql" / "src" / "dev.brikk.house.sql" / "parser"

sys.path.insert(0, str(SQLGLOT))

from sqlglot.tokenizer_core import TokenType  # noqa: E402
from sqlglot.dialects.dialect import Dialect  # noqa: E402

# Dialects to generate tables for. "" is the base "sqlglot" dialect and always
# emits BaseTokenizerTables.kt; every other name emits <Name>TokenizerTables.kt.
DIALECTS = ["", "mysql", "doris", "trino", "duckdb", "postgres"]


def sqlglot_version() -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(SQLGLOT), "describe", "--tags"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def kstr(s: str) -> str:
    """Escape a Python string into a Kotlin double-quoted string literal."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "$":
            out.append("\\$")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            # Control chars (e.g. \x07 bell in MySQL UNESCAPED_SEQUENCES) — Kotlin
            # has no \a/\v/\f escapes, so emit \uXXXX.
            out.append(f"\\u{ord(ch):04X}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def kchar(c: str) -> str:
    """Escape a single-character Python string into a Kotlin Char literal."""
    assert len(c) == 1, f"expected single char, got {c!r}"
    if c == "\\":
        return "'\\\\'"
    if c == "'":
        return "'\\''"
    if c == "\n":
        return "'\\n'"
    if c == "\r":
        return "'\\r'"
    if c == "\t":
        return "'\\t'"
    if ord(c) < 0x20:
        return f"'\\u{ord(c):04X}'"
    return f"'{c}'"


HEADER = """\
// GENERATED FILE — DO NOT EDIT.
// Generated by tools/gen_tokenizer_tables.py from sqlglot {version}.
// sqlglot is MIT-licensed, copyright Toby Mao. See reference/sqlglot/LICENSE.
package dev.brikk.house.sql.parser
"""


def gen_token_type(version: str) -> str:
    lines = [HEADER.format(version=version)]
    lines.append("/** sqlglot: tokenizer_core.TokenType (member order preserved). */")
    lines.append("enum class TokenType {")
    for member in TokenType:
        lines.append(f"    {member.name},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _token_map_entries(d: dict, key_fn) -> list[str]:
    return [f"        {key_fn(k)} to TokenType.{v.name}," for k, v in d.items()]


def _assert_single_chars(dialect_label: str, what: str, values) -> None:
    """The Kotlin engine models these as Char — fail loudly if a dialect violates it."""
    for v in values:
        assert len(v) == 1, (
            f"dialect {dialect_label!r}: {what} contains non-single-char entry {v!r}; "
            "the Kotlin engine uses Char for these — extend the engine before generating"
        )


def gen_tables(dialect_name: str, version: str) -> tuple[str, str]:
    """Returns (kotlin_object_name, file_contents) for one dialect."""
    is_base = dialect_name == ""
    d = Dialect.get_or_raise(dialect_name or None)
    t = d.tokenizer_class

    if is_base:
        obj_name = "BaseTokenizerTables"
        py_name = "Tokenizer"
    else:
        obj_name = dialect_name.capitalize() + "TokenizerTables"
        py_name = f"dialects.{type(d).__name__}.Tokenizer"

    label = dialect_name or "sqlglot"

    # Single-char assumptions of the Kotlin engine (Map<Char,...> / Set<Char>).
    _assert_single_chars(label, "SINGLE_TOKENS keys", t.SINGLE_TOKENS)
    _assert_single_chars(label, "_IDENTIFIERS keys", t._IDENTIFIERS)
    _assert_single_chars(label, "_STRING_ESCAPES", t._STRING_ESCAPES)
    _assert_single_chars(label, "_BYTE_STRING_ESCAPES", t._BYTE_STRING_ESCAPES)
    _assert_single_chars(label, "_IDENTIFIER_ESCAPES", t._IDENTIFIER_ESCAPES)
    _assert_single_chars(label, "_ESCAPE_FOLLOW_CHARS", t._ESCAPE_FOLLOW_CHARS)
    _assert_single_chars(label, "VAR_SINGLE_TOKENS", t.VAR_SINGLE_TOKENS)

    lines = [HEADER.format(version=version)]
    lines.append("/**")
    if is_base:
        lines.append(" * Base ('sqlglot' dialect) tokenizer tables.")
        lines.append(" * sqlglot: tokens.Tokenizer class-level dicts, with the derived tables")
    else:
        lines.append(f" * '{dialect_name}' dialect tokenizer tables.")
        lines.append(f" * sqlglot: {py_name} class-level dicts, with the derived tables")
    lines.append(" * (_QUOTES, _FORMAT_STRINGS, _COMMENTS, ...) pre-computed exactly as")
    lines.append(" * _TokenizerBase.__init_subclass__ computes them.")
    lines.append(" */")
    lines.append(f"object {obj_name} {{")

    # SINGLE_TOKENS — keys are single chars by engine design
    lines.append(f"    // sqlglot: {py_name}.SINGLE_TOKENS")
    lines.append("    val SINGLE_TOKENS: Map<Char, TokenType> = mapOf(")
    lines.extend(_token_map_entries(t.SINGLE_TOKENS, kchar))
    lines.append("    )")
    lines.append("")

    # KEYWORDS
    lines.append(f"    // sqlglot: {py_name}.KEYWORDS")
    lines.append("    val KEYWORDS: Map<String, TokenType> = mapOf(")
    lines.extend(_token_map_entries(t.KEYWORDS, kstr))
    lines.append("    )")
    lines.append("")

    # _QUOTES (computed)
    lines.append(f"    // sqlglot: {py_name}._QUOTES (computed)")
    lines.append("    val QUOTES: Map<String, String> = mapOf(")
    for k, v in t._QUOTES.items():
        lines.append(f"        {kstr(k)} to {kstr(v)},")
    lines.append("    )")
    lines.append("")

    # _FORMAT_STRINGS (computed)
    lines.append(f"    // sqlglot: {py_name}._FORMAT_STRINGS (computed)")
    lines.append("    val FORMAT_STRINGS: Map<String, StringFormat> = mapOf(")
    for k, (end, tt) in t._FORMAT_STRINGS.items():
        lines.append(f"        {kstr(k)} to StringFormat({kstr(end)}, TokenType.{tt.name}),")
    lines.append("    )")
    lines.append("")

    # _IDENTIFIERS (computed) — keys are single chars by engine design
    lines.append(f"    // sqlglot: {py_name}._IDENTIFIERS (computed)")
    lines.append("    val IDENTIFIERS: Map<Char, String> = mapOf(")
    for k, v in t._IDENTIFIERS.items():
        lines.append(f"        {kchar(k)} to {kstr(v)},")
    lines.append("    )")
    lines.append("")

    # _COMMENTS (computed; includes Jinja {# #} and hint start)
    lines.append(f"    // sqlglot: {py_name}._COMMENTS (computed)")
    lines.append("    val COMMENTS: Map<String, String?> = mapOf(")
    for k, v in t._COMMENTS.items():
        val = kstr(v) if v is not None else "null"
        lines.append(f"        {kstr(k)} to {val},")
    lines.append("    )")
    lines.append("")

    def char_set(name: str, comment: str, values) -> None:
        lines.append(f"    // sqlglot: {comment}")
        if values:
            body = ", ".join(kchar(c) for c in sorted(values))
            lines.append(f"    val {name}: Set<Char> = setOf({body})")
        else:
            lines.append(f"    val {name}: Set<Char> = emptySet()")
        lines.append("")

    char_set("STRING_ESCAPES", f"{py_name}._STRING_ESCAPES (computed)", t._STRING_ESCAPES)
    char_set(
        "BYTE_STRING_ESCAPES",
        f"{py_name}._BYTE_STRING_ESCAPES (computed)",
        t._BYTE_STRING_ESCAPES,
    )
    char_set(
        "IDENTIFIER_ESCAPES", f"{py_name}._IDENTIFIER_ESCAPES (computed)", t._IDENTIFIER_ESCAPES
    )
    char_set(
        "ESCAPE_FOLLOW_CHARS",
        f"{py_name}._ESCAPE_FOLLOW_CHARS (computed)",
        t._ESCAPE_FOLLOW_CHARS,
    )
    char_set("VAR_SINGLE_TOKENS", f"{py_name}.VAR_SINGLE_TOKENS", t.VAR_SINGLE_TOKENS)

    def token_set(name: str, comment: str, values) -> None:
        lines.append(f"    // sqlglot: {comment}")
        body = ", ".join(f"TokenType.{tt.name}" for tt in sorted(values, key=lambda x: x.name))
        lines.append(f"    val {name}: Set<TokenType> = setOf({body})")
        lines.append("")

    token_set("COMMANDS", f"{py_name}.COMMANDS", t.COMMANDS)
    token_set("COMMAND_PREFIX_TOKENS", f"{py_name}.COMMAND_PREFIX_TOKENS", t.COMMAND_PREFIX_TOKENS)
    token_set("TOKENS_PRECEDING_HINT", f"{py_name}.TOKENS_PRECEDING_HINT", t.TOKENS_PRECEDING_HINT)

    # NUMERIC_LITERALS
    lines.append(f"    // sqlglot: {py_name}.NUMERIC_LITERALS")
    if t.NUMERIC_LITERALS:
        lines.append("    val NUMERIC_LITERALS: Map<String, String> = mapOf(")
        for k, v in t.NUMERIC_LITERALS.items():
            lines.append(f"        {kstr(k)} to {kstr(v)},")
        lines.append("    )")
    else:
        lines.append("    val NUMERIC_LITERALS: Map<String, String> = emptyMap()")
    lines.append("")

    lines.append(f"    // sqlglot: {py_name} flags")
    lines.append(f"    const val NESTED_COMMENTS: Boolean = {str(t.NESTED_COMMENTS).lower()}")
    lines.append(f"    const val HINT_START: String = {kstr(t.HINT_START)}")
    lines.append(
        "    const val HEREDOC_TAG_IS_IDENTIFIER: Boolean = "
        f"{str(t.HEREDOC_TAG_IS_IDENTIFIER).lower()}"
    )
    lines.append(
        "    val HEREDOC_STRING_ALTERNATIVE: TokenType = "
        f"TokenType.{t.HEREDOC_STRING_ALTERNATIVE.name}"
    )
    lines.append(
        "    const val STRING_ESCAPES_ALLOWED_IN_RAW_STRINGS: Boolean = "
        f"{str(t.STRING_ESCAPES_ALLOWED_IN_RAW_STRINGS).lower()}"
    )
    lines.append(
        "    const val NUMBERS_CAN_HAVE_DECIMALS: Boolean = "
        f"{str(t.NUMBERS_CAN_HAVE_DECIMALS).lower()}"
    )

    if not is_base:
        # sqlglot: tokens.Tokenizer._init_core has_bit_strings/has_hex_strings
        lines.append(f"    const val HAS_BIT_STRINGS: Boolean = {str(bool(t.BIT_STRINGS)).lower()}")
        lines.append(f"    const val HAS_HEX_STRINGS: Boolean = {str(bool(t.HEX_STRINGS)).lower()}")
        lines.append("")
        dialect_py = f"dialects.{type(d).__name__}"
        lines.append(f"    // sqlglot: {dialect_py} dialect-level flags (passed via Tokenizer._init_core)")
        lines.append(
            "    const val NUMBERS_CAN_BE_UNDERSCORE_SEPARATED: Boolean = "
            f"{str(d.NUMBERS_CAN_BE_UNDERSCORE_SEPARATED).lower()}"
        )
        lines.append(
            "    const val IDENTIFIERS_CAN_START_WITH_DIGIT: Boolean = "
            f"{str(d.IDENTIFIERS_CAN_START_WITH_DIGIT).lower()}"
        )
        lines.append(f"    // sqlglot: {dialect_py}.UNESCAPED_SEQUENCES")
        if d.UNESCAPED_SEQUENCES:
            lines.append("    val UNESCAPED_SEQUENCES: Map<String, String> = mapOf(")
            for k, v in d.UNESCAPED_SEQUENCES.items():
                lines.append(f"        {kstr(k)} to {kstr(v)},")
            lines.append("    )")
        else:
            lines.append("    val UNESCAPED_SEQUENCES: Map<String, String> = emptyMap()")
        lines.append("")
        lines.append("    /**")
        lines.append(f"     * Full tokenizer configuration for the '{dialect_name}' dialect —")
        lines.append("     * every TokenizerConfig parameter wired explicitly, mirroring")
        lines.append("     * sqlglot tokens.Tokenizer._init_core.")
        lines.append("     */")
        lines.append("    val CONFIG: TokenizerConfig = TokenizerConfig(")
        lines.append("        singleTokens = SINGLE_TOKENS,")
        lines.append("        keywords = KEYWORDS,")
        lines.append("        quotes = QUOTES,")
        lines.append("        formatStrings = FORMAT_STRINGS,")
        lines.append("        identifiers = IDENTIFIERS,")
        lines.append("        comments = COMMENTS,")
        lines.append("        stringEscapes = STRING_ESCAPES,")
        lines.append("        byteStringEscapes = BYTE_STRING_ESCAPES,")
        lines.append("        identifierEscapes = IDENTIFIER_ESCAPES,")
        lines.append("        escapeFollowChars = ESCAPE_FOLLOW_CHARS,")
        lines.append("        commands = COMMANDS,")
        lines.append("        commandPrefixTokens = COMMAND_PREFIX_TOKENS,")
        lines.append("        nestedComments = NESTED_COMMENTS,")
        lines.append("        hintStart = HINT_START,")
        lines.append("        tokensPrecedingHint = TOKENS_PRECEDING_HINT,")
        lines.append("        hasBitStrings = HAS_BIT_STRINGS,")
        lines.append("        hasHexStrings = HAS_HEX_STRINGS,")
        lines.append("        numericLiterals = NUMERIC_LITERALS,")
        lines.append("        varSingleTokens = VAR_SINGLE_TOKENS,")
        lines.append("        stringEscapesAllowedInRawStrings = STRING_ESCAPES_ALLOWED_IN_RAW_STRINGS,")
        lines.append("        heredocTagIsIdentifier = HEREDOC_TAG_IS_IDENTIFIER,")
        lines.append("        heredocStringAlternative = HEREDOC_STRING_ALTERNATIVE,")
        lines.append("        numbersCanBeUnderscoreSeparated = NUMBERS_CAN_BE_UNDERSCORE_SEPARATED,")
        lines.append("        numbersCanHaveDecimals = NUMBERS_CAN_HAVE_DECIMALS,")
        lines.append("        identifiersCanStartWithDigit = IDENTIFIERS_CAN_START_WITH_DIGIT,")
        lines.append("        unescapedSequences = UNESCAPED_SEQUENCES,")
        lines.append("    )")

    lines.append("}")
    return obj_name, "\n".join(lines) + "\n"


def main() -> None:
    version = sqlglot_version()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "TokenType.kt").write_text(gen_token_type(version))
    print(f"Generated TokenType.kt ({len(list(TokenType))} members) from sqlglot {version}")
    for name in DIALECTS:
        obj_name, contents = gen_tables(name, version)
        (OUT_DIR / f"{obj_name}.kt").write_text(contents)
        d = Dialect.get_or_raise(name or None)
        print(
            f"Generated {obj_name}.kt "
            f"(dialect={name or 'sqlglot'!r}, keywords={len(d.tokenizer_class.KEYWORDS)})"
        )


if __name__ == "__main__":
    main()
