#!/usr/bin/env python3
"""Generate ClickHouse's FunctionCatalog from the vendored system.functions dump.

Source: vendor/data/clickhouse-functions-26.5.1.1.tsv, captured from ClickHouse
26.5.1.1 system.functions. The dump provides name, aggregate kind, case sensitivity,
and alias_to. It does not expose signatures, so overloads stay empty (honest unknown).

Usage: python3 tools/generate_clickhouse_functions.py
"""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "vendor" / "data" / "clickhouse-functions-26.5.1.1.tsv"
OUT = (
    ROOT / "brikk-sql-metadata" / "src" / "dev.brikk.house.sql.metadata"
    / "GeneratedClickhouseFunctionCatalog.kt"
)


def kstr(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def main() -> None:
    rows = [line.split("\t") for line in SOURCE.read_text().splitlines()[1:]]
    entries: dict[str, dict] = {}
    aliases: list[tuple[str, str]] = []

    for cols in rows:
        if len(cols) < 4:
            continue
        name, is_aggregate, _case_insensitive, alias_to = cols[:4]
        low = name.lower()
        target = alias_to.lower() if alias_to else ""
        if target and target != low:
            aliases.append((name, target))
            continue
        entries.setdefault(low, {
            "name": name,
            "kind": "AGGREGATE" if is_aggregate == "1" else "SCALAR",
            "aliases": [],
        })

    for alias, target in aliases:
        entry = entries.setdefault(target, {"name": target, "kind": "SCALAR", "aliases": []})
        if alias.lower() != entry["name"].lower():
            entry["aliases"].append(alias)

    blocks: list[tuple[list[str], int]] = []
    for kind in ("SCALAR", "AGGREGATE"):
        selected = sorted((e for e in entries.values() if e["kind"] == kind), key=lambda e: e["name"].lower())
        blocks.append(([f"    // {kind.lower()} ({len(selected)})"], 0))
        for entry in selected:
            aliases_list = sorted(set(entry["aliases"]), key=lambda value: (value.lower(), value))
            alias_arg = ""
            if aliases_list:
                alias_arg = ", aliases = listOf(" + ", ".join(kstr(a) for a in aliases_list) + ")"
            blocks.append(([
                f"    FunctionDef({kstr(entry['name'])}, FunctionKind.{kind}{alias_arg}),"
            ], 1))

    chunks: list[list[str]] = [[]]
    budget = 0
    for block, cost in blocks:
        if budget + cost > 400 and chunks[-1]:
            chunks.append([])
            budget = 0
        chunks[-1].extend(block)
        budget += cost

    aggregate_count = sum(e["kind"] == "AGGREGATE" for e in entries.values())
    alias_count = sum(len(set(e["aliases"])) for e in entries.values())
    lines = [
        "// GENERATED FILE — DO NOT EDIT.",
        "// Generated by tools/generate_clickhouse_functions.py from ClickHouse 26.5.1.1",
        "// system.functions (vendor/data/clickhouse-functions-26.5.1.1.tsv).",
        "// The dump exposes names/kinds/aliases but not signatures; overloads are honestly empty.",
        "// ClickHouse is Apache-2.0 licensed. See ATTRIBUTIONS.md and vendor/README.md.",
        "package dev.brikk.house.sql.metadata",
        "",
        f"/** ClickHouse 26.5.1.1 builtins: {len(entries)} definitions, {alias_count} aliases, "
        f"{aggregate_count} aggregates. */",
        "val CLICKHOUSE_FUNCTION_CATALOG: FunctionCatalog = FunctionCatalog(",
        "    " + " + ".join(f"chunk{i}()" for i in range(len(chunks))),
        ")",
    ]
    for i, chunk in enumerate(chunks):
        lines.extend(["", f"private fun chunk{i}(): List<FunctionDef> = listOf(", *chunk, ")"])

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(entries)} defs / {alias_count} aliases -> {OUT}")


if __name__ == "__main__":
    main()
