#!/usr/bin/env python3
"""Generate closed-world semantic pair scopes from *-hazards.json sources.

A hazard file defaults to PARTIAL. It becomes COMPLETE only when its explicit
`coverage.status` is `complete`; file existence alone never proves completeness.
Each direction receives the source-side evidence keys (raw names plus slash aliases),
catalog/version provenance, scope text, and source-file pointer.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SEMANTICS = ROOT / "brikk-sql" / "testResources" / "semantics"
OUT = (
    ROOT / "brikk-sql-metadata" / "src" / "dev.brikk.house.sql.metadata"
    / "GeneratedSemanticCoverage.kt"
)
IDENT = re.compile(r"^[A-Za-z_][A-Za-z_0-9]*$")


def kstr(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
    value = value.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return f'"{value}"'


def keys_for(side_name: str) -> set[str]:
    keys = {side_name.strip().upper()}
    for piece in side_name.split("/"):
        piece = piece.strip()
        if piece.endswith("()"):
            piece = piece[:-2]
        if IDENT.match(piece):
            keys.add(piece.upper())
    return keys


def pascal(value: str) -> str:
    return value[:1].upper() + value[1:]


def main() -> None:
    records = []
    for path in sorted(SEMANTICS.glob("*-hazards.json")):
        parts = path.name.removesuffix("-hazards.json").split("-")
        if len(parts) != 2:
            sys.exit(f"error: invalid pair filename {path.name}")
        a, b = parts
        data = json.loads(path.read_text())
        coverage = data.get("coverage") or {}
        status = coverage.get("status", "partial").upper().replace("-", "_")
        if status not in {"PARTIAL", "COMPLETE"}:
            sys.exit(f"error: {path.name}: coverage.status must be partial or complete")
        catalogs = coverage.get("catalogs") or data.get("engines") or {}
        scope = coverage.get(
            "scope",
            f"{len(data.get('pairs') or [])} evidence entries; no closed-world completeness declaration",
        )
        pairs = data.get("pairs") or []
        for source, target in ((a, b), (b, a)):
            # Concept resolution may encounter the parsed canonical name, source surface
            # name, or emitted target name. Track both evidence-side key sets while the
            # directional hazard itself retains oriented sourceName/targetName fields.
            keys = sorted({
                key
                for pair in pairs
                for side in (source, target)
                for key in keys_for(pair[side])
            })
            records.append({
                "source": source,
                "target": target,
                "status": status,
                "source_catalog": str(catalogs.get(source, "unversioned hazard source")),
                "target_catalog": str(catalogs.get(target, "unversioned hazard source")),
                "scope": scope,
                "evidence": f"brikk-sql/testResources/semantics/{path.name}",
                "keys": keys,
            })

    lines = [
        "// GENERATED FILE — DO NOT EDIT.",
        "// Generated by tools/generate_semantic_coverage.py from *-hazards.json.",
        "// File existence defaults to PARTIAL; COMPLETE requires an explicit closed-world declaration.",
        "package dev.brikk.house.sql.metadata",
        "",
        "internal val GENERATED_SEMANTIC_PAIR_SCOPES: Map<Pair<String, String>, SemanticPairScope> = mapOf(",
    ]
    for i, record in enumerate(records):
        source = record["source"]
        target = record["target"]
        lines.extend([
            f"    ({kstr(source)} to {kstr(target)}) to SemanticPairScope(",
            f"        source = {kstr(source)}, target = {kstr(target)},",
            f"        coverage = PairCoverage.{record['status']},",
            f"        sourceCatalog = {kstr(record['source_catalog'])},",
            f"        targetCatalog = {kstr(record['target_catalog'])},",
            f"        scope = {kstr(record['scope'])},",
            f"        evidence = {kstr(record['evidence'])},",
            f"        coveredConcepts = scopeKeys{i}(),",
            "    ),",
        ])
    lines.append(")")
    for i, record in enumerate(records):
        keys = record["keys"]
        lines.extend(["", f"private fun scopeKeys{i}(): Set<String> = setOf("])
        for start in range(0, len(keys), 8):
            lines.append("    " + ", ".join(kstr(k) for k in keys[start:start + 8]) + ",")
        lines.append(")")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {len(records)} directional scopes -> {OUT}")


if __name__ == "__main__":
    main()
