#!/usr/bin/env python3
"""Generates the Trino built-in function catalog for brikk-sql-metadata from a
`SHOW FUNCTIONS` TSV dump.

Source of truth: Trino's own resolved function registry via `SHOW FUNCTIONS`, dumped by
an in-JVM DistributedQueryRunner harness pinned to the target Trino version (Method B of
trino-ducklake's GENERATE-TRINO-FUNCTION-CATALOG.md recipe; provenance in
vendor/README.md). The committed dump lives at vendor/data/trino-functions-<version>.tsv,
6 tab-separated columns: name, return type, argument types, function type, deterministic,
description.

Modeling decisions (from the recipe's caveats, documented in the generated header too):
  - kinds: scalar->SCALAR, aggregate->AGGREGATE, window->WINDOW, table->TABLE_VALUED.
  - variadic=false everywhere: SHOW FUNCTIONS does not flag variadics, so listed arities
    are a LOWER bound (concat/greatest/least/coalesce accept more args than shown).
  - parametric types (varchar(x), decimal(p,s)) and type variables (E, T, K, V, unknown)
    are kept as literal strings — treat as "any" when mapping.
  - operators (::, ||, CAST, ...) are grammar-level and not in SHOW FUNCTIONS; the
    catalog intentionally excludes them.
  - FunctionOverload.argNames stays null: SHOW FUNCTIONS lists argument TYPES only,
    never parameter names.
  - FunctionDef.profile stays null: SHOW FUNCTIONS exposes no null-handling metadata
    (its columns are name/types/kind/deterministic/description) — honest UNKNOWN.
    Populating Trino profiles would require scraping engine sources (@SqlNullable /
    RETURNS NULL ON NULL INPUT on the java function implementations) — future work,
    see vendor/README.md.

Usage: python3 tools/generate_trino_functions.py [<tsv-path>]
       (default: vendor/data/trino-functions-481.tsv)
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_TSV = ROOT / "vendor" / "data" / "trino-functions-481.tsv"
OUT = ROOT / "brikk-sql-metadata" / "src" / "dev.brikk.house.sql.metadata" / "GeneratedTrinoFunctionCatalog.kt"

KIND_MAP = {
    "scalar": "SCALAR",
    "aggregate": "AGGREGATE",
    "window": "WINDOW",
    "table": "TABLE_VALUED",
}

KIND_ORDER = ["SCALAR", "AGGREGATE", "WINDOW", "TABLE_VALUED", "TABLE_GENERATING"]


def kstr(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def split_args(args: str) -> list[str]:
    """Split a SHOW FUNCTIONS arg-type list on top-level commas only
    (nested parens: row(x bigint, y double), map(K, V), decimal(p,s))."""
    out: list[str] = []
    depth = 0
    cur = ""
    for ch in args:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def main() -> None:
    tsv = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_TSV
    m = re.search(r"trino-functions-(\d+)\.tsv$", tsv.name)
    version = m.group(1) if m else "unknown"

    # (name, kind) -> set of (argTypes tuple, returnType). Grouped per kind: a name can
    # be registered under two kinds (e.g. `sequence` is both scalar and table).
    defs: dict[tuple[str, str], set[tuple[tuple[str, ...], str]]] = {}
    rows = 0
    for line in tsv.read_text().splitlines():
        if not line.strip():
            continue
        cols = line.split("\t")
        if len(cols) < 5:
            sys.exit(f"error: malformed row (need >=5 columns): {line!r}")
        name, ret, args, ftype = cols[0], cols[1], cols[2], cols[3]
        kind = KIND_MAP.get(ftype)
        if kind is None:
            sys.exit(f"error: unknown function type {ftype!r} for {name!r} (update KIND_MAP?)")
        rows += 1
        defs.setdefault((name, kind), set()).add((tuple(split_args(args)), ret))

    total_overloads = sum(len(v) for v in defs.values())

    lines = [
        "// GENERATED FILE — DO NOT EDIT.",
        f"// Generated by tools/generate_trino_functions.py from vendor/data/{tsv.name}:",
        f"// Trino {version}'s own `SHOW FUNCTIONS` registry, dumped via an in-JVM",
        "// DistributedQueryRunner harness pinned to that version (see vendor/README.md).",
        "// Trino is Apache-2.0 licensed. See ATTRIBUTIONS.md.",
        "//",
        "// Modeling notes (SHOW FUNCTIONS caveats):",
        "//  - variadic=false everywhere: SHOW FUNCTIONS does not flag variadics, so an",
        "//    overload's arity is a LOWER bound (concat/greatest/least/coalesce accept",
        "//    more arguments than the listed overloads suggest). Do not hard-enforce a",
        "//    max arity from this catalog.",
        "//  - parametric types (varchar(x), decimal(p,s)) and type variables (E, T, K, V,",
        "//    unknown) are kept as literal strings — treat as \"any\" when mapping.",
        "//  - operators (::, ||, %, subscript, ...) are grammar-level, not functions,",
        "//    and are intentionally absent. Function-SHAPED grammar-level names",
        "//    (COALESCE, CAST, EXTRACT, ...) are carried by the handwritten",
        "//    TrinoGrammarBuiltins.kt and wired in via grammarBuiltins below.",
        "//  - argNames=null and profile=null everywhere: SHOW FUNCTIONS exposes neither",
        "//    parameter names nor null-handling metadata (see the generator's header).",
        "package dev.brikk.house.sql.metadata",
        "",
        f"/** Trino {version} built-in functions: {len(defs)} definitions, {total_overloads} overloads. */",
    ]

    blocks: list[tuple[list[str], int]] = []
    for kind in KIND_ORDER:
        entries = sorted((name, v) for (name, k), v in defs.items() if k == kind)
        if not entries:
            continue
        first_of_kind = True
        for name, overloads in entries:
            block: list[str] = []
            if first_of_kind:
                block.append(f"    // {kind.lower()} ({len(entries)})")
                first_of_kind = False
            block.append(f'    FunctionDef("{name}", FunctionKind.{kind}, overloads = listOf(')
            for arg_types, ret in sorted(overloads):
                args = ", ".join(kstr(t) for t in arg_types)
                block.append(f"        FunctionOverload(listOf({args}), {kstr(ret)}),")
            block.append("    )),")
            blocks.append((block, 1 + len(overloads)))

    # Chunked private functions: a single top-level initializer risks the JVM's 64KB
    # method limit (same scheme as GeneratedDuckdbFunctionCatalog.kt).
    CHUNK_BUDGET = 400
    chunks: list[list[str]] = [[]]
    budget = 0
    for block, cost in blocks:
        if budget + cost > CHUNK_BUDGET and chunks[-1]:
            chunks.append([])
            budget = 0
        chunks[-1].extend(block)
        budget += cost

    lines.append("val TRINO_FUNCTION_CATALOG: FunctionCatalog = FunctionCatalog(")
    lines.append("    " + " + ".join(f"trinoChunk{i}()" for i in range(len(chunks))) + ",")
    # Grammar-level builtins (COALESCE, CAST, EXTRACT, ...) are absent from SHOW
    # FUNCTIONS by design; the handwritten, grammar-curated TrinoGrammarBuiltins.kt
    # carries them (see its header for the SqlBase.g4 / AstBuilder citations).
    lines.append("    grammarBuiltins = TRINO_GRAMMAR_BUILTINS,")
    lines.append(")")
    for i, chunk in enumerate(chunks):
        lines.append("")
        lines.append(f"private fun trinoChunk{i}(): List<FunctionDef> = listOf(")
        lines.extend(chunk)
        lines.append(")")
    OUT.write_text("\n".join(lines) + "\n")

    by_kind = {k: sum(1 for (_, dk) in defs if dk == k) for k in KIND_ORDER}
    print(
        f"wrote {len(defs)} defs / {total_overloads} overloads ({rows} TSV rows) from Trino {version} -> {OUT}\n"
        f"  per kind: {[f'{k}={v}' for k, v in by_kind.items() if v]}"
    )


if __name__ == "__main__":
    main()
