#!/usr/bin/env python3
"""Generates the Doris built-in function catalog for brikk-sql-metadata from Doris's own registry.

Adapted from doris-intellij-plugin/tools/generate_doris_functions.py (same extraction
approach, upgraded output: per-kind FunctionDefs as generated Kotlin instead of a flat
name list).

Source of truth: the committed Nereids registry lists
  fe/fe-core/src/main/java/org/apache/doris/catalog/Builtin{Scalar,Aggregate,Window,
  TableValued,TableGenerating}Functions.java
Each entry is `scalar(SomeFn.class, "name", "alias1", ...)` (or agg/window/tableValued/
tableGenerating variants) — the quoted strings after `.class,` are the function's primary
name followed by aliases. This is what Doris registers at runtime
(FunctionRegistry.registerBuiltinFunctions), so it's more complete and authoritative than
the docs. Re-run against a newer Doris checkout to refresh.

Signatures (arg/return types) are NOT extracted — they live on each function class's
static SIGNATURES field and require building fe-core. The Kotlin model is overload-ready
(FunctionDef.overloads defaults to empty) for a future signature-dumper pass.

Usage: python3 tools/generate_doris_functions.py [<doris-repo-root>]
       (default root: reference/doris)
"""

from __future__ import annotations

import glob
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_DORIS = ROOT / "reference" / "doris"
OUT = ROOT / "brikk-sql-metadata" / "src" / "dev.brikk.house.sql.metadata" / "GeneratedDorisFunctionCatalog.kt"

IDENT = re.compile(r"[A-Za-z][A-Za-z0-9_]*$")
QUOTED = re.compile(r'"([^"]+)"')

# Registry file -> FunctionKind enum member
KINDS = {
    "BuiltinScalarFunctions.java": "SCALAR",
    "BuiltinAggregateFunctions.java": "AGGREGATE",
    "BuiltinWindowFunctions.java": "WINDOW",
    "BuiltinTableValuedFunctions.java": "TABLE_VALUED",
    "BuiltinTableGeneratingFunctions.java": "TABLE_GENERATING",
}


def doris_version(doris_root: pathlib.Path) -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(doris_root), "describe", "--tags", "--always"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def collect(doris_root: pathlib.Path) -> dict[str, list[tuple[str, list[str]]]]:
    catalog = doris_root / "fe" / "fe-core" / "src" / "main" / "java" / "org" / "apache" / "doris" / "catalog"
    by_kind: dict[str, list[tuple[str, list[str]]]] = {k: [] for k in KINDS.values()}
    found = 0
    for path in sorted(glob.glob(str(catalog / "Builtin*Functions.java"))):
        base = os.path.basename(path)
        kind = KINDS.get(base)
        if kind is None:
            print(f"warning: unrecognized registry file {base} — skipped (update KINDS?)", file=sys.stderr)
            continue
        found += 1
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                idx = line.find(".class,")
                if idx == -1:
                    continue
                names = [n.strip().upper() for n in QUOTED.findall(line[idx:]) if IDENT.match(n.strip())]
                if names:
                    by_kind[kind].append((names[0], names[1:]))
    if found == 0:
        sys.exit(f"error: no Builtin*Functions.java under {catalog}")
    return by_kind


def main() -> None:
    doris_root = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DORIS
    version = doris_version(doris_root)
    by_kind = collect(doris_root)
    total_defs = sum(len(v) for v in by_kind.values())
    total_names = sum(1 + len(a) for v in by_kind.values() for (_, a) in v)

    lines = [
        "// GENERATED FILE — DO NOT EDIT.",
        f"// Generated by tools/generate_doris_functions.py from Apache Doris {version}",
        "// (fe/fe-core/.../catalog/Builtin*Functions.java — Doris's runtime function registry).",
        "// Apache Doris is Apache-2.0 licensed. See ATTRIBUTIONS.md and vendor/README.md.",
        "package dev.brikk.house.sql.metadata",
        "",
        f"/** Doris built-in functions: {total_defs} definitions, {total_names} names incl. aliases. */",
        "val DORIS_FUNCTION_CATALOG: FunctionCatalog = FunctionCatalog(listOf(",
    ]
    for kind in ("SCALAR", "AGGREGATE", "WINDOW", "TABLE_VALUED", "TABLE_GENERATING"):
        lines.append(f"    // {kind.lower()} ({len(by_kind[kind])})")
        for name, aliases in sorted(by_kind[kind]):
            if aliases:
                alias_list = ", ".join(f'"{a}"' for a in aliases)
                lines.append(f'    FunctionDef("{name}", FunctionKind.{kind}, listOf({alias_list})),')
            else:
                lines.append(f'    FunctionDef("{name}", FunctionKind.{kind}),')
    lines.append("))")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {total_defs} defs / {total_names} names from Doris {version} -> {OUT}")


if __name__ == "__main__":
    main()
